docs/index.asciidoc, docs/siem/index.asciidoc
Includes the SIEM index file, so SIEM docs are built and tested when PRs for 7.9 are opened.
[Preview](https://security-docs_20.docs-preview.app.elstc.co/guide/en/security/current/index.html)
=> [DOCS]Includes SIEM index file

docs/siem/detections/api/rules-api-export.asciidoc, docs/siem/detections/api/rules-api-prebuilt.asciidoc
Fixes pulled from the SIEM docs: https://github.com/elastic/stack-docs/pull/1200
=> [Docs]Fixes prebuilt rule terminology and a typo

docs/siem/detections/api/rules-api-export.asciidoc, docs/siem/detections/api/rules-api-prebuilt.asciidoc
- fixes prebuilt rule terminology and typo (#29)
=> [7.x] fixes prebuilt rule terminology and typo (#29)

docs/siem/installation.asciidoc
Updates links to reflect changes added in elastic/beats#19302.
This change applies to 7.9 and later.
=> Change links to refactored Beats getting started docs

docs/siem/index.asciidoc, docs/siem/reference/timeline-schema.asciidoc, docs/siem/timeline/api/timeline-api-create.asciidoc, docs/siem/timeline/api/timeline-api-import.asciidoc, docs/siem/timeline/api/timeline-api-index.asciidoc, docs/siem/timeline/api/timeline-api-overview.asciidoc
Adds Timeline schema and API documentation.
[Timeline schema preview](https://security-docs_50.docs-preview.app.elstc.co/guide/en/security/master/timeline-object-schema.html)
[Timeline API overview preview](https://security-docs_50.docs-preview.app.elstc.co/guide/en/security/master/timeline-api-overview.html)
[Timeline create endpoint](https://security-docs_50.docs-preview.app.elstc.co/guide/en/security/master/timeline-api-create.html)
[Timeline import endpoint](https://security-docs_50.docs-preview.app.elstc.co/guide/en/security/master/timeline-api-import.html)
Supersedes PR: https://github.com/elastic/security-docs/pull/18, which only makes structural changes to ToC.
Resolves: https://github.com/elastic/security-docs/issues/19
=> [Docs]Adds timeline schema and API

docs/siem/detections/api/rules-api-create.asciidoc, docs/siem/detections/api/rules-api-update.asciidoc, docs/siem/detections/api/signals-api-overview.asciidoc
Adds new 7.9 rule fields and objects to the detections API.
[Create rule preview](https://security-docs_70.docs-preview.app.elstc.co/guide/en/security/master/rules-api-create.html)
[Signals endpoint preview](https://security-docs_70.docs-preview.app.elstc.co/guide/en/security/master/signals-api-overview.html)
[Update rule preview](https://security-docs_70.docs-preview.app.elstc.co/guide/en/security/master/rules-api-update.html)
Reviewers, please ignore any `BEN ...` in the files, this is just to remind me to add links when other stuff is ready (docs won't build when there are broken links). Also, no need to worry about terminology (signals vs alerts), we'll clean that up in a separate PR before the 7.9 release.
=> [Docs]Updates detections API

docs/management/admin/admin-pg-ov.asciidoc
- makes admin overview a first-level section (#99)
=> [7.x] makes admin overview a first-level section (#99)

docs/management/admin/admin-pg-ov.asciidoc
- makes admin overview a first-level section (#99)
=> [7.9] makes admin overview a first-level section (#99)

docs/cases/cases-ui-integrations.asciidoc
Corrects the documentation after feedback from @MadameSheema 
Thanks!
=> [Docs]Cases UI connector corrections

docs/release-notes.asciidoc
- [Docs]Adds Timeline known issue (#161)
=> [7.x] [Docs]Adds Timeline known issue (#161)

docs/release-notes.asciidoc
- [Docs]Adds Timeline known issue (#161)
=> [7.9] [Docs]Adds Timeline known issue (#161)

docs/getting-started/install-endpoint.asciidoc
Elastic Endpoint Security can not be run with an agent in Standalone mode.
=> Remove standalone Endpoint installation instructions

docs/getting-started/install-endpoint.asciidoc
- Remove standalone Endpoint installation instructions (#158)
=> [7.9] Remove standalone Endpoint installation instructions (#158)

docs/getting-started/install-endpoint.asciidoc
- Remove standalone Endpoint installation instructions (#158)
=> [7.x] Remove standalone Endpoint installation instructions (#158)

docs/detections/detection-engine-intro.asciidoc
- [Docs]Updates link to detection requirements (#171)
=> [7.9] [Docs]Updates link to detection requirements (#171)

docs/es-overview.asciidoc
- Update es-overview.asciidoc (#166)
=> [7.x] Update es-overview.asciidoc (#166)

docs/es-overview.asciidoc
- Update es-overview.asciidoc (#166)
=> [7.9] Update es-overview.asciidoc (#166)

docs/detections/alerts-ui-manage.asciidoc
Removes the word `resolver` from the analyse events URL.
=> [Docs]Removes resolver from section URL

docs/detections/alerts-ui-manage.asciidoc
- removes resolver from section URL (#183)
=> [7.x] removes resolver from section URL (#183)

docs/detections/alerts-ui-manage.asciidoc
- removes resolver from section URL (#183)
=> [7.9] removes resolver from section URL (#183)

docs/getting-started/detections-req.asciidoc
- removes unnecessary tip (#198)
=> [7.x] removes unnecessary tip (#198)

docs/getting-started/detections-req.asciidoc
- removes unnecessary tip (#198)
=> [7.9] removes unnecessary tip (#198)

docs/detections/alerts-ui-manage.asciidoc
Removes a full stop mistakenly added to a title.
=> removes full stop from title

docs/detections/alerts-ui-manage.asciidoc
- removes full stop from title (#211)
=> [7.x] removes full stop from title (#211)

docs/detections/alerts-ui-manage.asciidoc
- removes full stop from title (#211)
=> [7.9] removes full stop from title (#211)

docs/post-upgrade-req.asciidoc, docs/release-notes.asciidoc, docs/template-script.asciidoc
Describes when remapping signals index is required.
[Reindex procedure preview](https://security-docs_223.docs-preview.app.elstc.co/guide/en/security/master/post-upgrade-req.html)
[RNs preview](https://security-docs_223.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
=> [Docs]Adds index post upgrade requirement clarifications

docs/post-upgrade-req.asciidoc, docs/release-notes.asciidoc, docs/template-script.asciidoc
- [Docs]Adds index post upgrade requirement clarifications (#223)
=> [7.9] [Docs]Adds index post upgrade requirement clarifications (#223)

docs/detections/api/rules/rules-api-overview.asciidoc
Fixes a typo on the rules API overview page.
=> [Docs]Fix signals index typo

docs/detections/api/rules/rules-api-overview.asciidoc
- fix signals index name (#228)
=> [7.x] fix signals index name (#228)

docs/detections/api/rules/rules-api-overview.asciidoc
- fix signals index name (#228)
=> [7.9] fix signals index name (#228)

docs/release-notes.asciidoc
- [Docs]Adds 7.9.1 fixed bugs (#231)
=> [7.9] [Docs]Adds 7.9.1 fixed bugs (#231)

docs/detections/api/lists/api-create-list-container.asciidoc
- [Docs]Adds list item value parsing (#237)
=> [7.9] [Docs]Adds list item value parsing (#237)

docs/detections/detection-engine-intro.asciidoc, docs/getting-started/detections-req.asciidoc, docs/getting-started/sec-app-requirements.asciidoc
- Changed all instances of "on-premises" to "self-managed".
- Replaced all instances of "Cloud deployments" with Elastic Cloud Deployments. Elastic Cloud covers a wider gamut of potential Elastic deployments beyond Elasticsearch.
=> Replace On-Prem with self-managed in Detections section

prebuilt-rules-scripts/create_documentation.py, prebuilt-rules-scripts/readme.md
- fixes asciidoc formatting (#303)
=> [7.x] fixes asciidoc formatting (#303)

prebuilt-rules-scripts/create_documentation.py, prebuilt-rules-scripts/readme.md
- fixes asciidoc formatting (#303)
=> [7.10] fixes asciidoc formatting (#303)

prebuilt-rules-scripts/create_documentation.py, prebuilt-rules-scripts/readme.md
- fixes asciidoc formatting (#303)
=> [7.9] fixes asciidoc formatting (#303)

docs/whats-new.asciidoc
Related to https://github.com/elastic/kibana/pull/76023 and https://github.com/elastic/stack-docs/pull/1363
This PR adds a blurb about the new prebuilt machine learning jobs in the "[What's New](https://www.elastic.co/guide/en/security/master/whats-new.html)" for 7.10
https://security-docs_319.docs-preview.app.elstc.co/guide/en/security/master/whats-new.html
=> [DOCS] Add machine learning jobs to Whats New

docs/whats-new.asciidoc
- [DOCS] Changes the title of the ML related highlight section. (#325)
=> [7.x] [DOCS] Changes the title of the ML related highlight section. (#325)

docs/whats-new.asciidoc
- [DOCS] Changes the title of the ML related highlight section. (#325)
=> [7.10] [DOCS] Changes the title of the ML related highlight section. (#325)

docs/cases/api/cases-api/case-api-update-connector.asciidoc, docs/cases/api/cases-api/cases-api-assign-connector.asciidoc, docs/cases/api/cases-api/cases-api-create.asciidoc, docs/cases/api/cases-api/cases-api-find-cases.asciidoc, docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc, docs/cases/api/cases-api/cases-api-get-case.asciidoc, docs/cases/api/cases-api/cases-api-get-connector.asciidoc, docs/cases/api/cases-api/cases-api-update.asciidoc
Updates the API docs with the new connectors' fields for 7.10.0.
=> [Docs] Adds 7.10 Cases API updates

docs/whats-new.asciidoc
- [DOCS] What's new in 7.10. (#352)
=> [7.x] [DOCS] What's new in 7.10. (#352)

docs/whats-new.asciidoc
- [DOCS] What's new in 7.10. (#352)
=> [7.10] [DOCS] What's new in 7.10. (#352)

docs/whats-new.asciidoc
=> [7.x] update to what's new (#361)

docs/release-notes.asciidoc
- [7.10]: Add upgrade requirements to 7.10 release notes (#369)
=> [7.10] [7.10]: Add upgrade requirements to 7.10 release notes (#369)

docs/release-notes.asciidoc
- [7.10]: Add upgrade requirements to 7.10 release notes (#369)
=> [7.x] [7.10]: Add upgrade requirements to 7.10 release notes (#369)

docs/es-overview.asciidoc, docs/getting-started/advanced-setting.asciidoc, docs/getting-started/install-endpoint.asciidoc, docs/management/admin/admin-pg-ov.asciidoc, docs/siem/overview.asciidoc
Fixes links to the Fleet documentation, which has moved in 7.10 and later.
Also renames Ingest Manager to Fleet (changed in 7.10, too)
Related PR: https://github.com/elastic/observability-docs/pull/257
=> Fix Fleet links and naming

docs/es-overview.asciidoc, docs/getting-started/advanced-setting.asciidoc, docs/getting-started/install-endpoint.asciidoc, docs/management/admin/admin-pg-ov.asciidoc, docs/siem/overview.asciidoc
- Fix Fleet links and naming (#375)
=> [7.x] Fix Fleet links and naming (#375)

docs/es-overview.asciidoc, docs/getting-started/advanced-setting.asciidoc, docs/getting-started/install-endpoint.asciidoc, docs/management/admin/admin-pg-ov.asciidoc, docs/siem/overview.asciidoc
- Fix Fleet links and naming (#375)
=> [7.10] Fix Fleet links and naming (#375)

docs/es-overview.asciidoc, docs/getting-started/sec-app-requirements.asciidoc
- Adding ECS note to docs. (#379)
=> [7.10] Adding ECS note to docs. (#379)

docs/es-overview.asciidoc, docs/getting-started/sec-app-requirements.asciidoc
- Adding ECS note to docs. (#379)
=> [7.x] Adding ECS note to docs. (#379)

docs/release-notes.asciidoc
- Issue #410: Add 7.10.1 release notes (#402)
=> [7.10] Issue #410: Add 7.10.1 release notes (#402)

docs/release-notes.asciidoc
- Issue #410: Add 7.10.1 release notes (#402)
=> [7.x] Issue #410: Add 7.10.1 release notes (#402)

docs/reference/timeline-schema.asciidoc
- Issue-395: Change Event Type for Timeline Schema (#400)
=> [7.10] Issue-395: Change Event Type for Timeline Schema (#400)

docs/reference/timeline-schema.asciidoc
- Issue-395: Change Event Type for Timeline Schema (#400)
=> [7.x] Issue-395: Change Event Type for Timeline Schema (#400)

docs/es-overview.asciidoc, docs/getting-started/advanced-setting.asciidoc, docs/getting-started/install-endpoint.asciidoc, docs/management/admin/admin-pg-ov.asciidoc
- Fix broken Fleet links (#420)
=> [7.x] Fix broken Fleet links (#420)

docs/es-overview.asciidoc, docs/getting-started/advanced-setting.asciidoc, docs/getting-started/install-endpoint.asciidoc, docs/management/admin/admin-pg-ov.asciidoc
- Fix broken Fleet links (#420)
=> [7.10] Fix broken Fleet links (#420)

docs/reference/field-ref.asciidoc
Change nested source/destination.as fields to the concrete sub fields as expected.
etc source.as -> source.as.number
=> Correct source/destination.as field listings

docs/reference/field-ref.asciidoc
- Correct source/destination.as field listings (#447)
=> [7.x] Correct source/destination.as field listings (#447)

docs/reference/field-ref.asciidoc
- Correct source/destination.as field listings (#447)
=> [7.10] Correct source/destination.as field listings (#447)

docs/detections/api/signals-migration-api.asciidoc, docs/post-upgrade-req.asciidoc, docs/siem-apis.asciidoc
- Document Signals Migration APIs (#435)
=> [7.x] Document Signals Migration APIs (#435)

docs/detections/api/signals-migration-api.asciidoc, docs/post-upgrade-req.asciidoc, docs/siem-apis.asciidoc
- Document Signals Migration APIs (#435)
=> [7.10] Document Signals Migration APIs (#435)

.backportrc.json
This PR updates the config file so that the 7.11 branch is one of the options in the backport tool.
=> Add 7.11 branch to backport config

docs/reference/field-ref.asciidoc
- Correct source/destination.as field listings (#447)
=> [7.11] Correct source/destination.as field listings (#447)

docs/detections/api/rules/rules-api-create.asciidoc
Adding `{{context.alerts}}`: Array of detected alerts to 7.x branch.
=> [DOCS] Adding alert array placeholder to 7.x.

docs/detections/api/signals-migration-api.asciidoc, docs/post-upgrade-req.asciidoc, docs/siem-apis.asciidoc
- Document Signals Migration APIs (#435)
=> [7.11] Document Signals Migration APIs (#435)

docs/siem-apis.asciidoc
- Issue #412 - Add warning about Kibana Dev Console (#489)
=> [7.x] Issue #412 - Add warning about Kibana Dev Console (#489)

docs/siem-apis.asciidoc
- Issue #412 - Add warning about Kibana Dev Console (#489)
=> [7.11] Issue #412 - Add warning about Kibana Dev Console (#489)

docs/detections/detection-engine-intro.asciidoc, docs/es-overview.asciidoc
- [DOCS] Detection engine/cold tier data - 7.11 (#487)
=> [7.x] [DOCS] Detection engine/cold tier data - 7.11 (#487)

docs/detections/detection-engine-intro.asciidoc, docs/es-overview.asciidoc
- [DOCS] Detection engine/cold tier data - 7.11 (#487)
=> [7.11] [DOCS] Detection engine/cold tier data - 7.11 (#487)

docs/release-notes.asciidoc
- Issue #429: 7.11 release notes (#458)
=> [7.11] Issue #429: 7.11 release notes (#458)

docs/release-notes.asciidoc
- Issue #429: 7.11 release notes (#458)
=> [7.x] Issue #429: 7.11 release notes (#458)

docs/detections/machine-learning/machine-learning.asciidoc
Related to https://github.com/elastic/kibana/pull/85065 and https://github.com/elastic/stack-docs/pull/1504
This PR removes the redundant introduction and adds mention of the Elastic Agent in https://www.elastic.co/guide/en/security/master/machine-learning.html
=> [DOCS] Removes redundant intro to prebuilt ML modules

docs/detections/machine-learning/machine-learning.asciidoc
Backports https://github.com/elastic/security-docs/pull/483
=> [7.x][DOCS] Removes redundant intro to prebuilt ML modules (#483)

docs/detections/machine-learning/machine-learning.asciidoc
Backports https://github.com/elastic/security-docs/pull/483
=> [7.11][DOCS] Removes redundant intro to prebuilt ML modules (#483)

docs/detections/detection-engine-intro.asciidoc
Fixes #518. No major changes made. Added a line under line 6 so could commit a change and create a pull request.
=> Issue #518: Remove beta tag from detections

docs/detections/detection-engine-intro.asciidoc
- Issue #518: Remove beta tag from detections (#521)
=> [7.x] Issue #518: Remove beta tag from detections (#521)

docs/detections/detection-engine-intro.asciidoc
- Issue #518: Remove beta tag from detections (#521)
=> [7.12] Issue #518: Remove beta tag from detections (#521)

docs/detections/detection-engine-intro.asciidoc
- Issue #518: Remove beta tag from detections (#521)
=> [7.11] Issue #518: Remove beta tag from detections (#521)

docs/getting-started/detections-req.asciidoc
- Issue 437: Maintenance permission (#492)
=> [7.11] Issue 437: Maintenance permission (#492)

docs/getting-started/detections-req.asciidoc
- Issue 437: Maintenance permission (#492)
=> [7.12] Issue 437: Maintenance permission (#492)

docs/getting-started/detections-req.asciidoc
- Issue 437: Maintenance permission (#492)
=> [7.x] Issue 437: Maintenance permission (#492)

docs/detections/api/rules/rules-api-create.asciidoc
This is a rough pass at updating the [Create Rule API docs](https://www.elastic.co/guide/en/security/current/rules-api-create.html#_request_body) for the recent changes surrounding `Threshold` and `Indicator Match` rules. @madirey and @rylnd if you could verify these changes and if any additional fields should be documented that would be greatly appreciated. 🙂 
Resolves: https://github.com/elastic/kibana/issues/91965
Note: The grouping of optional fields per rule type makes these docs difficult to maintain (for me at least 😅), as you need to cross reference each optional field from each type, plus I'd bargain our users might find it useful to be able to look at all fields per each rule type independently. Something to verify with users/discuss, but would be a nice add for maintaining …
=> [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules 

docs/detections/api/rules/rules-api-create.asciidoc
- [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules  (#522)
=> [7.x] [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules  (#522)

docs/release-notes.asciidoc
- Issue #538: 7.11.2 release notes (#542)
=> [7.12] Issue #538: 7.11.2 release notes (#542)

docs/detections/api/rules/rules-api-update.asciidoc
This ports the changes made in #522 to analogous updates to the Rule
Update API docs.
=> Updates Update Rule docs for Threshold + Indicator Match rules

docs/release-notes.asciidoc
Addresses #548. 
Opening PR for 7.12.0 RN.
Preview available [here.](https://security-docs_550.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
=> [DOCS] 7.12.0 release notes 

docs/release-notes.asciidoc
- [DOCS] 7.12.0 release notes  (#550)
=> [7.x] [DOCS] 7.12.0 release notes  (#550)

docs/release-notes.asciidoc
- Adding #91718 to 7.12 RNs. (#584)
=> [7.x] Adding #91718 to 7.12 RNs. (#584)

docs/release-notes.asciidoc
- Adding #91718 to 7.12 RNs. (#584)
=> [7.12] Adding #91718 to 7.12 RNs. (#584)

docs/getting-started/ingest-data.asciidoc
=> [7.x] Backport #592 7.x

docs/detections/detections-ui-exceptions.asciidoc
The exceptions that are `is in list`/`is not in list` do not show up for threshold and eql rules.
Please add links to Threshold rules and Event correlation rules.
=> Clarify large value list exceptions depend on rule type

docs/detections/detections-ui-exceptions.asciidoc
- Clarify large value list exceptions depend on rule type (#627)
=> [7.x] Clarify large value list exceptions depend on rule type (#627)

docs/detections/detections-ui-exceptions.asciidoc
- Clarify large value list exceptions depend on rule type (#627)
=> [7.12] Clarify large value list exceptions depend on rule type (#627)

docs/getting-started/sec-app-requirements.asciidoc
- [DOCS] Fleet and Endpoint Security require a Transform, appropriate configuration is needed (#693)
=> [7.x] [DOCS] Fleet and Endpoint Security require a Transform, appropriate configuration is needed (#693)

docs/getting-started/sec-app-requirements.asciidoc
- [DOCS] Fleet and Endpoint Security require a Transform, appropriate configuration is needed (#693)
=> [7.13] [DOCS] Fleet and Endpoint Security require a Transform, appropriate configuration is needed (#693)

docs/detections/alerts-ui-manage.asciidoc, docs/detections/rules-ui-manage.asciidoc
Per comment [here](https://github.com/elastic/security-team/issues/17#issuecomment-842552644): 
Moving this from [here](https://www.elastic.co/guide/en/security/master/alerts-ui-manage.html) to the correct place [here](https://www.elastic.co/guide/en/security/master/rules-ui-management.html). 
Related: #666, #650, and https://github.com/elastic/security-team/issues/17
=> [DOCS] Moving prebuilt rules update to the correct topic

docs/getting-started/install-endpoint.asciidoc
It doesn't make sense to include "Copy as curl" or "View in console" here because the commands are not cURL, and you can't run them from the Dev Tools console.
=> Remove "Copy as curl" and "View in console" links from examples

docs/getting-started/install-endpoint.asciidoc
- Remove copy as curl and run in console links (#723)
=> [7.x] Remove copy as curl and run in console links (#723)

docs/getting-started/install-endpoint.asciidoc
- Remove copy as curl and run in console links (#723)
=> [7.13] Remove copy as curl and run in console links (#723)

docs/cases/cases-overview.asciidoc
- Adding a step to the Open a new case section. (#757)
=> [7.13] Adding a step to the Open a new case section. (#757)

docs/cases/cases-overview.asciidoc
- Adding a step to the Open a new case section. (#757)
=> [7.x] Adding a step to the Open a new case section. (#757)

docs/release-notes.asciidoc
- [BUG] Add #102146 to the 7.13.2 RN as a known issue (#765)
=> [7.x] [BUG] Add #102146 to the 7.13.2 RN as a known issue (#765)

docs/release-notes.asciidoc
- [BUG] Add #102146 to the 7.13.2 RN as a known issue (#765)
=> [7.13] [BUG] Add #102146 to the 7.13.2 RN as a known issue (#765)

docs/detections/machine-learning/machine-learning.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1731
This PR updates links from the Security documentation to the Machine Learning anomaly detection pages.
=> [DOCS] Fixes links to anomaly detection overview

docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
Add release note to 0.13.2 summary (same note from the downloadable package index)
This needs to backport to 7.13
=> [Detection rules] Add release note to 0.13.2 summary

docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
- Update prebuilt-rules-0-13-2-summary.asciidoc (#799)
=> [7.13] Update prebuilt-rules-0-13-2-summary.asciidoc (#799)

docs/detections/machine-learning/tune-anomaly-results.asciidoc
Related to https://github.com/elastic/stack-docs/pull/1750
This PR fixes a link in the https://www.elastic.co/guide/en/security/master/tuning-anomaly-results.html page, since the target has moved in the machine learning guide.
=> [DOCS] Fixes link to ML custom rules

docs/events/index.asciidoc
- Correct typos in index.asciidoc (#817)
=> [7.13] Correct typos in index.asciidoc (#817)

docs/events/index.asciidoc
- Correct typos in index.asciidoc (#817)
=> [7.14] Correct typos in index.asciidoc (#817)

docs/events/index.asciidoc
- Correct typos in index.asciidoc (#817)
=> [7.x] Correct typos in index.asciidoc (#817)

docs/detections/rules-ui-create.asciidoc, docs/getting-started/detections-req.asciidoc
- [BUG] Detection Rule execution authorization model not outlined in security docs  (#889)
=> [7.14] [BUG] Detection Rule execution authorization model not outlined in security docs  (#889)

docs/detections/rules-ui-create.asciidoc, docs/getting-started/detections-req.asciidoc
- [BUG] Detection Rule execution authorization model not outlined in security docs  (#889)
=> [7.x] [BUG] Detection Rule execution authorization model not outlined in security docs  (#889)

docs/getting-started/security-ui.asciidoc
- Updated section title and incorrect x-ref. (#914)
=> [7.14] Updated section title and incorrect x-ref. (#914)

docs/getting-started/security-ui.asciidoc
- Updated section title and incorrect x-ref. (#914)
=> [7.x] Updated section title and incorrect x-ref. (#914)

docs/cases/api/cases-api/cases-api-create.asciidoc
Addresses #894.
Preview [here](https://security-docs_921.docs-preview.app.elstc.co/guide/en/security/master/cases-api-create.html).
=> [BUG] Round Closing bracket missing for under Create Case Doc

docs/getting-started/install-endpoint.asciidoc
- Remove beta tag from install-endpoint.asciidoc (#929)
=> [7.14] Remove beta tag from install-endpoint.asciidoc (#929)

docs/getting-started/install-endpoint.asciidoc
- Remove beta tag from install-endpoint.asciidoc (#929)
=> [7.x] Remove beta tag from install-endpoint.asciidoc (#929)

docs/getting-started/install-endpoint.asciidoc
Addresses #900. 
Remove section and screenshot for verifying enrollment, because currently not available. See [#102334](https://github.com/elastic/kibana/issues/102334).
Preview [here](https://security-docs_922.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html).
=> [BUG] New Security Navigation not present under Verify Elastic Endpoint Enrollment Doc Section

docs/cases/cases-ui-integrations.asciidoc
- [BUG] Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc (#917)
=> [7.14] [BUG] Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc (#917)

docs/cases/cases-ui-integrations.asciidoc
- [BUG] Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc (#917)
=> [7.x] [BUG] Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc (#917)

docs/detections/rules-ui-create.asciidoc
- [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
=> [7.12] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)

docs/detections/rules-ui-create.asciidoc
- [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
=> [7.13] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)

docs/detections/rules-ui-create.asciidoc
- [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
=> [7.14] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)

docs/detections/rules-ui-create.asciidoc
- [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
=> [7.x] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)

docs/detections/detections-ui-exceptions.asciidoc
- [BUG] Incorrect Type of value list name are displayed in value list  (#880)
=> [7.x] [BUG] Incorrect Type of value list name are displayed in value list  (#880)

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
- [DOCS] Add _bulk_action API route documentation (#952)
=> [7.x] [DOCS] Add _bulk_action API route documentation (#952)

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
- [DOCS] Add _bulk_action API route documentation (#952)
=> [7.14] [DOCS] Add _bulk_action API route documentation (#952)

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
- [DOCS] Add _bulk_action API route documentation (#952)
=> [7.15] [DOCS] Add _bulk_action API route documentation (#952)

docs/release-notes.asciidoc
- [DOCS] Release note cleanup (#974)
=> [7.14] [DOCS] Release note cleanup (#974)

docs/release-notes.asciidoc
- [DOCS] Release note cleanup (#974)
=> [7.15] [DOCS] Release note cleanup (#974)

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Small addendum to #952. 
Preview [here](https://security-docs_978.docs-preview.app.elstc.co/guide/en/security/master/bulk-actions-rules-api.html).
=> [EDIT] Add _bulk_action API route documentation

docs/detections/detection-engine-intro.asciidoc, docs/getting-started/advanced-setting.asciidoc
Addresses #1003. 
- [Limited support for indicator match rules](https://security-docs_1004.docs-preview.app.elstc.co/guide/en/security/master/detection-engine-overview.html#support-indicator-rules)
- [Update default Elastic Security threat intelligence indices](https://security-docs_1004.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html#update-threat-intel-indices)
=> [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules

docs/detections/detection-engine-intro.asciidoc, docs/getting-started/advanced-setting.asciidoc
- [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)
=> [7.x] [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)

docs/detections/detection-engine-intro.asciidoc, docs/getting-started/advanced-setting.asciidoc
- [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)
=> [7.15] [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)

docs/detections/detection-engine-intro.asciidoc, docs/getting-started/advanced-setting.asciidoc
- [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)
=> [7.14] [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)

docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
Looks like some extra lines were accidentally left from a previous merge-conflict resolution. 7.15 and main look fine.
=> [Detection-rules] Remove extra entries in rules update table

docs/detections/rules-ui-create.asciidoc
- Replace gsuite link with Google Workspace (#1036)
=> [7.x] Replace gsuite link with Google Workspace (#1036)

docs/detections/rules-ui-create.asciidoc
- Replace gsuite link with Google Workspace (#1036)
=> [7.14] Replace gsuite link with Google Workspace (#1036)

docs/detections/rules-ui-create.asciidoc
- Replace gsuite link with Google Workspace (#1036)
=> [7.15] Replace gsuite link with Google Workspace (#1036)

docs/detections/detection-engine-intro.asciidoc
- [DOCS] Add more context to indicator match rule restrictions (#1025)
=> [7.15] [DOCS] Add more context to indicator match rule restrictions (#1025)

docs/detections/detection-engine-intro.asciidoc
- [DOCS] Add more context to indicator match rule restrictions (#1025)
=> [7.x] [DOCS] Add more context to indicator match rule restrictions (#1025)

docs/detections/detections-ui-exceptions.asciidoc
- Add admonitions about wildcards (#1065)
=> [7.15] Add admonitions about wildcards (#1065)

docs/detections/detections-ui-exceptions.asciidoc
- Add admonitions about wildcards (#1065)
=> [7.x] Add admonitions about wildcards (#1065)

docs/post-upgrade-req-cti-alerts, docs/post-upgrade/post-upgrade-intro.asciidoc, docs/post-upgrade/post-upgrade-req.asciidoc, docs/post-upgrade/template-script.asciidoc
- [DOCS] Migrating Enriched CTI Alerts (#1035)
=> [7.15] [DOCS] Migrating Enriched CTI Alerts (#1035)

docs/post-upgrade-req-cti-alerts, docs/post-upgrade/post-upgrade-intro.asciidoc, docs/post-upgrade/post-upgrade-req-cti-alerts.asciidoc, docs/post-upgrade/post-upgrade-req.asciidoc, docs/post-upgrade/template-script.asciidoc
- [DOCS] Migrating Enriched CTI Alerts (#1035)
=> [7.x] [DOCS] Migrating Enriched CTI Alerts (#1035)

docs/post-upgrade/post-upgrade-req-cti-alerts.asciidoc, docs/release-notes/7.15.asciidoc
- [BUG] Update description for 1102 in the 7.15 RN (#1082)
=> [7.x] [BUG] Update description for 1102 in the 7.15 RN (#1082)

docs/detections/api/signals-migration-api.asciidoc
- Add query for finding outdated alerts with CTI data (#1090)
=> [7.15] Add query for finding outdated alerts with CTI data (#1090)

docs/detections/api/signals-migration-api.asciidoc
- Add query for finding outdated alerts with CTI data (#1090)
=> [7.x] Add query for finding outdated alerts with CTI data (#1090)

docs/management/admin/trusted-apps.asciidoc
- Clarify admin access to Trusted Applications page (#1062)
=> [7.x] Clarify admin access to Trusted Applications page (#1062)

docs/management/admin/trusted-apps.asciidoc
- Clarify admin access to Trusted Applications page (#1062)
=> [7.15] Clarify admin access to Trusted Applications page (#1062)

docs/whats-new.asciidoc
- Adds 7.15 ref link for what's new: https://www.elastic.co/guide/en/security/7.15/whats-new.html
=> [DOCS] Add 7.15 anchor for what's new to 7.x

docs/release-notes/7.15.asciidoc
Addresses #1115.
Preview [here](https://security-docs_1116.docs-preview.app.elstc.co/diff).
=> [BUG] Revise 7.15 release notes: host isolation Linux version support

docs/release-notes/7.15.asciidoc
- [BUG] Revise 7.15 release notes: host isolation Linux version support (#1116)
=> [7.x] [BUG] Revise 7.15 release notes: host isolation Linux version support (#1116)

docs/cases/cases-ui-integrations.asciidoc
- [BUG]Change "Email or Username" field to "Email address" for JIRA connector docs (#1127)
=> [7.x] [BUG]Change "Email or Username" field to "Email address" for JIRA connector docs (#1127)

docs/cases/cases-ui-integrations.asciidoc
- [BUG]Change "Email or Username" field to "Email address" for JIRA connector docs (#1127)
=> [7.15] [BUG]Change "Email or Username" field to "Email address" for JIRA connector docs (#1127)

docs/detections/rules-ui-create.asciidoc
- [DOCS] Clarify usage of field overrides with Threshold Rules (#1124)
=> [7.15] [DOCS] Clarify usage of field overrides with Threshold Rules (#1124)

docs/detections/rules-ui-create.asciidoc
- [DOCS] Clarify usage of field overrides with Threshold Rules (#1124)
=> [7.x] [DOCS] Clarify usage of field overrides with Threshold Rules (#1124)

docs/detections/rules-ui-create.asciidoc, docs/detections/rules-ui-monitor.asciidoc
- [DOCS] Clarify alert de-duplication logic around configured 'additional look-back time' (#1125)
=> [7.15] [DOCS] Clarify alert de-duplication logic around configured 'additional look-back time' (#1125)

docs/detections/rules-ui-create.asciidoc, docs/detections/rules-ui-monitor.asciidoc
- [DOCS] Clarify alert de-duplication logic around configured 'additional look-back time' (#1125)
=> [7.x] [DOCS] Clarify alert de-duplication logic around configured 'additional look-back time' (#1125)

docs/post-upgrade-req.asciidoc
- Small formatting and internal ref fixes. (#1198)
=> [7.14] Small formatting and internal ref fixes. (#1198)

docs/release-notes/7.15.asciidoc
Addresses #1267.
Preview here:
- [Release Notes](https://security-docs_1268.docs-preview.app.elstc.co/guide/en/security/7.15/release-notes.html#known-issue-7.15.0)
=> [DOCS] Github style markdown causes issues during upgrade

docs/release-notes.asciidoc, docs/release-notes/7.15.asciidoc
Addresses https://github.com/elastic/security-docs/issues/1299.
- Release notes page preview [here](https://security-docs_1300.docs-preview.app.elstc.co/guide/en/security/7.15/release-notes-header-7.15.0.html). 
- TOC preview [here](https://security-docs_1300.docs-preview.app.elstc.co/guide/en/security/7.15/index.html).
- 7.15 RN landing page [here](https://security-docs_1300.docs-preview.app.elstc.co/guide/en/security/7.15/release-notes.html).
=> [BUG] Remove discrete tags at the top of the 7.15 RN page

docs/release-notes/7.15.asciidoc
Addresses https://github.com/elastic/security-docs/issues/1285.
Preview:
- [Release notes](https://security-docs_1295.docs-preview.app.elstc.co/guide/en/security/7.15/release-notes.html)
=> [DOCS] Move Known issues section to top of page

docs/getting-started/ml-req.asciidoc
=> [7.9] [DOCS] Update security doc ML requirements (#1281)

docs/getting-started/ml-req.asciidoc
=> [7.10] [DOCS] Update security doc ML requirements (#1281)

docs/getting-started/ml-req.asciidoc
=> [7.11] [DOCS] Update security doc ML requirements (#1281)

docs/getting-started/ml-req.asciidoc
=> [7.12] [DOCS] Update security doc ML requirements (#1281)

docs/getting-started/ml-req.asciidoc
=> [7.14] [DOCS] Update security doc ML requirements (#1281)

docs/getting-started/ml-req.asciidoc
=> [7.15] [DOCS] Update security doc ML requirements (#1281)

docs/getting-started/ml-req.asciidoc
=> [7.16] [DOCS] Update security doc ML requirements (#1281)

docs/release-notes.asciidoc, docs/release-notes/7.16.asciidoc
Addresses https://github.com/elastic/security-docs/issues/1332.
Preview [here](https://security-docs_1333.docs-preview.app.elstc.co/guide/en/security/current/release-notes-7.16.0.html).
=> [DOCS] 7.16.1 Release Notes

docs/release-notes/7.15.asciidoc
- [DOCS] Github style markdown causes issues during upgrade (#1268)
=> [7.16] [DOCS] Github style markdown causes issues during upgrade (#1268)

docs/release-notes/7.15.asciidoc, package-lock.json
- [DOCS] Move Known issues section to top of page (#1295)
=> [7.16] [DOCS] Move Known issues section to top of page (#1295)

docs/release-notes.asciidoc, docs/release-notes/7.16.asciidoc
Addresses https://github.com/elastic/security-docs/issues/1380.
Previews:
- [7.16.3 Release notes](https://security-docs_1381.docs-preview.app.elstc.co/guide/en/security/7.16/release-notes-header-7.16.0.html#release-notes-7.16.3)
- [Updated index page for 7.16.3](https://security-docs_1381.docs-preview.app.elstc.co/guide/en/security/7.16/release-notes.html) 
- [7.16.0 Release Notes](https://security-docs_1381.docs-preview.app.elstc.co/guide/en/security/7.16/release-notes-header-7.16.0.html#release-notes-7.16.0)
- [Updated index page for 7.16.0](https://security-docs_1381.docs-preview.app.elstc.co/guide/en/security/7.16/release-notes.html)
=> [DOCS] 7.16.3 Release Notes

docs/release-notes.asciidoc, docs/release-notes/7.16.asciidoc
Backports the following commits to 7.17:
- [DOCS] 7.16.3 Release Notes (#1381)
=> [7.17] [DOCS] 7.16.3 Release Notes (#1381)

docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
Updates links to the [Filebeat Google Workspace module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-gsuite.html) so they don't break when we change the current Stack version to 8.0.
Relates to https://github.com/elastic/docs/pull/2312
https://security-docs_1441.docs-preview.app.elstc.co/diff
=> [DOCS] Fix links to the Filebeat Google Workspace module

docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
=> [7.11] [DOCS] Fix links to filebeat Google Workspace module (#1441)

docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
=> [7.12] [DOCS] Fix links to filebeat Google Workspace module (#1441)

docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
=> [7.13] [DOCS] Fix links to filebeat Google Workspace module (#1441)

docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
=> [7.14] [DOCS] Fix links to filebeat Google Workspace module (#1441)

docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc, docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc, docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc, docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
=> [7.16] [DOCS] Fix links to filebeat Google Workspace module (#1441)

docs/release-notes/8.0.asciidoc
Adds definition of the `pull` attribute to the breaking changes snippet that is included in the Elastic Installation and Upgrade Guide, as part of https://github.com/elastic/stack-docs/pull/2039.
Until this PR is merged, the attribute won't resolve within the stack-docs page.
=> [DOCS] Add pull attribute definition to breaking changes snippet

docs/release-notes/8.0.asciidoc
- [DOCS] Add snippet tags to 8.0 release notes file (#1564)
Also adds pull attribute definition to breaking changes snippet directly in this PR, instead of creating a separate backport PR of https://github.com/elastic/security-docs/pull/1572.
=> [8.0] [DOCS] Add snippet tags to 8.0 release notes file (#1564)

docs/release-notes/8.0.asciidoc
- [DOCS] Add snippet tags to 8.0 release notes file (#1564)
Also adds pull attribute definition to breaking changes snippet directly in this PR, instead of creating a separate backport PR of https://github.com/elastic/security-docs/pull/1572.
=> [8.1] [DOCS] Add snippet tags to 8.0 release notes file (#1564)

docs/whats-new.asciidoc
- Add snippet tags to What's New topic (#1575)
=> [8.0] Add snippet tags to What's New topic (#1575)

docs/whats-new.asciidoc
- Add snippet tags to What's New topic (#1575)
=> [8.1] Add snippet tags to What's New topic (#1575)

docs/whats-new.asciidoc
- [DOCS] Change links to full URLs on What's New page (#1578)
=> [8.0] [DOCS] Change links to full URLs on What's New page (#1578)

docs/release-notes.asciidoc, docs/release-notes/7.17.asciidoc
Addresses https://github.com/elastic/security-docs/issues/1611.
Previews:
- [Updated index page](https://security-docs_1612.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_1612.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html)
=> [DOCS] 7.17.1 Release Notes

docs/getting-started/detections-req.asciidoc
- Updates manage alerts permission reqs. (#1685)
=> [7.16] Updates manage alerts permission reqs. (#1685)

docs/getting-started/detections-req.asciidoc
- Updates manage alerts permission reqs. (#1685)
=> [7.15] Updates manage alerts permission reqs. (#1685)

docs/getting-started/detections-req.asciidoc
- Updates manage alerts permission reqs. (#1685)
=> [7.14] Updates manage alerts permission reqs. (#1685)

docs/getting-started/detections-req.asciidoc
- Updates manage alerts permission reqs. (#1685)
=> [7.13] Updates manage alerts permission reqs. (#1685)

docs/upgrade/upgrade-security.asciidoc
Addendum to  #1563 and PR #1642. 
Merge changes to `main` and backport to `8.0`, `8.1`.
=> [DOCS] Backport Upgrade Security topic to 8.0.1  

docs/getting-started/advanced-setting.asciidoc
=> Correct minor typo in advanced-setting.asciidoc (#1735)

docs/cases/api/cases-api/cases-api-find-connectors.asciidoc
- [BUG] Refresh the "Find connectors" cases API topic (#1743)
=> [8.1] [BUG] Refresh the "Find connectors" cases API topic (#1743)

docs/release-notes/8.1.asciidoc
Fixes https://github.com/elastic/security-docs/issues/1760.
Preview [here](https://security-docs_1763.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.1.0.html#release-notes-8.1.1).
=> [DOCS] Retroactive Endpoint 8.1.1 release notes

docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/1801.
Preview [here](https://security-docs_1810.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#breaking-changes-7.17.0). (Documented PR #120686 as a breaking change in 7.17.0)
=> [BUG] Missing breaking change notice for preconfigured connectors in cases

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
**Resolves https://github.com/elastic/security-docs/issues/1729**
Added warning messages to deprecated Detection APIs
=> [8.2][DOCS] Add warning messages to deprecated APIs

docs/detections/alerts-run-osquery.asciidoc
The structure of the Osquery section in the Kibana docs has changed with this PR: https://github.com/elastic/kibana/pull/130195. This update fixes the resulting broken link on the new alerts-run-osquery.asciidoc page.
=> [BUG] Fix broken link

docs/detections/detections-ui-exceptions.asciidoc, docs/detections/rules-ui-monitor.asciidoc, docs/management/admin/blocklist.asciidoc, docs/management/admin/event-filters.asciidoc, docs/management/admin/host-isolation-exceptions.asciidoc, docs/management/admin/trusted-apps.asciidoc, docs/troubleshooting/management/ts-management.asciidoc
Resolves #1826.
Previews:
- [Trusted applications | View and manage...
](https://security-docs_1930.docs-preview.app.elstc.co/guide/en/security/master/trusted-apps-ov.html#trusted-apps-list)
- [Event filters | View and manage...
](https://security-docs_1930.docs-preview.app.elstc.co/guide/en/security/master/event-filters.html#manage-event-filters)
- [Host isolation exceptions | View and manage...
](https://security-docs_1930.docs-preview.app.elstc.co/guide/en/security/master/host-isolation-exceptions.html#manage-host-isolation-exceptions)
- [Blocklist | View and manage...](https://security-docs_1930.docs-preview.app.elstc.co/guide/en/security/master/blocklist.html#manage-blocklist)
Incidental updates (other instances of "Actions button" renamed to "Actions menu"):
- [Rule exceptions and …
=> [DOCS] Endpoint Management docs: consistency fixes, prerequisite callout

docs/post-upgrade/post-upgrade-intro.asciidoc
Resolves #1512.
Removes outdated topic from the docs. As previously discussed, manually enabling data for the visual event analyzer was a task related to a specific upgrade scenario (from `7.9.x` to <`7.11`), and versions since then have not required a manual procedure. This topic is likely to be confusing to a customer upgrading to more recent version who wouldn't actually need to do anything extra to get event analyzer working.
Preview: [Updated landing page for Post-Upgrade section](https://security-docs_1938.docs-preview.app.elstc.co/guide/en/security/master/post-upgrade-intro.html) (confirm topic removed from navigation TOC on right side)
=> [DOCS] Remove procedure for manually enabling event analyzer

docs/getting-started/advanced-setting.asciidoc
We have started collecting alert telemetry on prebuilt detection rules.
Preview: [Configure advanced settings | Telemetry settings](https://security-docs_1990.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html#telemetry-settings)
=> Add note on detection rule alert telemetry privacy

docs/detections/rules-ui-monitor.asciidoc
Relates to https://github.com/elastic/stack-docs/pull/2140, https://github.com/elastic/kibana/pull/131166
The "Security:Auditbeat", "Security:Auditbeat authentication", "Security:Winlogbeat", and "Security:Winlogbeat authentication" anomaly detection jobs have been removed, so links to that content must be cleaned up.
=> [DOCS] Remove broken links to discontinued anomaly detection jobs

docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/1992.
Preview [here](https://security-docs_1997.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#known-issue-7.17.0).
=> [DOCS] [7.17] Add release note for networking on macOS with Endpoint enabled

docs/release-notes.asciidoc, docs/release-notes/8.2.asciidoc
Fixes https://github.com/elastic/security-docs/issues/1963.
Previews:
- [Index page](https://security-docs_2019.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_2019.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.2.0.html#release-notes-8.2.2)
=> [DOCS] 8.2.2 Release Notes

docs/whats-new.asciidoc
Fixes typo in heading: https://www.elastic.co/guide/en/security/current/whats-new.html#_wilcard_support_for_event_filters
=> [BUG] Fixes typo in 8.2 What's New page

docs/getting-started/sec-app-requirements.asciidoc
We're retiring the Stack GS in favor of the new onboarding content introduced in 8.2.
=> [DOCS] Removed ref to Stack GS

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Fixes the spec for the `BulkEditAction` parameters.
Background:
- https://github.com/elastic/security-docs/pull/2030#discussion_r903918687
- https://github.com/elastic/security-docs/pull/2030#discussion_r904795123
=> [DOCS] Fix the docs for `/api/detection_engine/rules/_bulk_action` endpoint

docs/detections/alerts-ui-manage.asciidoc
Noticed a minor typo in step 1 of [Add an alert to a new case](https://www.elastic.co/guide/en/security/8.2/alerts-ui-manage.html#signals-to-new-cases). This typo is only present in the 8.2 docs, so I branched from 8.2 and will merge into 8.2 only. 
Preview [here](https://security-docs_2174.docs-preview.app.elstc.co/guide/en/security/8.2/alerts-ui-manage.html#signals-to-new-cases).
=> [BUG] Fixes typo in the "Add an alert to a new case" docs

docs/release-notes/8.3.asciidoc
Addresses https://github.com/elastic/security-docs/issues/2180.
Previews:
- [8.3.0 release notes | Known issue](https://security-docs_2181.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.3.0.html#known-issue-8.3.0)
- [8.3.1 release notes | Known issue](https://security-docs_2181.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.3.0.html#known-issue-8.3.1)
=> [DOCS] Document bug where alerting rules created/edited in 8.2 will stop running on upgrade 

docs/release-notes.asciidoc, docs/release-notes/8.3.asciidoc
Addresses https://github.com/elastic/security-docs/issues/2173.
Previews:
- [Index page](https://security-docs_2179.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_2179.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.3.0.html#release-notes-8.3.2)
=> [DOCS] 8.3.2 Release notes

docs/release-notes/8.3.asciidoc
Minor editoral fixes. Preview here.
=> [BUG] Fixes typo in 8.3.2 release notes

docs/release-notes/8.3.asciidoc
Fixes https://github.com/elastic/security-docs/issues/2194. 
Preview [here](https://security-docs_2195.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.3.0.html#release-notes-8.3.2).
=> [BUG] Remove #135842 from the 8.3.2 release notes

docs/management/admin/response-actions.asciidoc, docs/management/manage-intro.asciidoc, docs/troubleshooting/management/ts-management.asciidoc
Endpoint & OLM teams need resolvable URLs for a couple of docs links in the UI. This PR creates the needed placeholder stubs, and I'll follow up with complete docs in these issues:
- https://github.com/elastic/security-docs/issues/2211
- https://github.com/elastic/security-docs/issues/2197
Note: These issues aren't necessarily related, but I combined the stub creation into a single PR for convenience. The complete docs will be added in separate PRs.
---
- [Endpoint response actions](https://security-docs_2282.docs-preview.app.elstc.co/guide/en/security/master/response-actions.html)
- [Troubleshooting | Management tools | Endpoints | Disabled to avoid potential system deadlock](https://security-docs_2282.docs-preview.app.elstc.co/guide/en/security/master/ts-management.html)
=> [DOCS] Add stub pages for endpoint docs links

docs/release-notes.asciidoc
Adding missing link. Preview [here](https://security-docs_2294.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html).
=> [BUG] Adding link to 8.3.3 release notes 

docs/detections/machine-learning/machine-learning.asciidoc, docs/getting-started/ml-req.asciidoc
This will backport the following commits from `main` to `8.3`:
- [[DOCS] Add notes about security for ML anomaly detection job results (#2288)](https://github.com/elastic/security-docs/pull/2288)
=> [8.3] [DOCS] Add notes about security for ML anomaly detection job results (#2288)

docs/detections/machine-learning/machine-learning.asciidoc, docs/getting-started/ml-req.asciidoc
This will backport the following commits from `main` to `7.17`:
- [[DOCS] Add notes about security for ML anomaly detection job results (#2288)](https://github.com/elastic/security-docs/pull/2288)
=> [7.17] [DOCS] Add notes about security for ML anomaly detection job results (#2288)

docs/release-notes.asciidoc, docs/release-notes/7.17.asciidoc
Addresses https://github.com/elastic/security-docs/issues/2334. 
Previews:
- [Index page](https://security-docs_2350.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_2350.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#bug-fixes-7.17.6)
=> [DOCS] 7.17.6 Release notes 

docs/getting-started/detections-req.asciidoc
Addresses https://github.com/elastic/security-docs/issues/2370. 
Preview [here](https://security-docs_2371.docs-preview.app.elstc.co/guide/en/security/7.17/detections-permissions-section.html#enable-detections-ui). (Scroll down to row that shows privs for managing rules)
=> [BUG] Leftover text in table for detection privs

docs/dashboards/kubernetes-dashboard.asciidoc
#2368 [DOCS] YAML url needs a correction for k8s dashboard docs
Description:
- Updated the YAML link to the proper link
- Added the source,console block
- Continued the bullet points
Test Cases:
Validated that the URL is correct
Validated that the code block is on a new line
Validated that bullet points continue afterwards
Preview: [Kubernetes dashboard](https://security-docs_2369.docs-preview.app.elstc.co/guide/en/security/master/kubernetes-dashboard.html)
=> Update K8s Dashboard Docs with the correct URL

.github/workflows/docs-preview-links.yml
This will backport the following commits from `main` to `8.3`:
=> [8.3] Adds GitHub action to create preview links (#2391)

.github/workflows/docs-preview-links.yml
This will backport the following commits from `main` to `8.2`:
=> [8.2] Adds GitHub action to create preview links (#2391)

.github/workflows/docs-preview-links.yml
This will backport the following commits from `main` to `8.1`:
=> [8.1] Adds GitHub action to create preview links (#2391)

.github/workflows/docs-preview-links.yml
This will backport the following commits from `main` to `8.0`:
=> [8.0] Adds GitHub action to create preview links (#2391)

.github/workflows/docs-preview-links.yml
This will backport the following commits from `main` to `7.17`:
=> [7.17] Adds GitHub action to create preview links (#2391)

docs/release-notes/8.4.asciidoc
Pull request [139461](https://github.com/elastic/kibana/pull/139461) did not make it to the **Build Candidate #2** for the 8.4.1 release, so it wasn't included in the Public Release.
Correcting the Release Notes to remove this change.
=> Correct 8.4.1 release notes

docs/management/admin/endpoint-artifacts.asciidoc, docs/management/manage-intro.asciidoc
OLM team's https://github.com/elastic/kibana/pull/142467 requires a live docs link URL to pass CI. This PR creates a stub page for that URL; the page will be completed with https://github.com/elastic/security-docs/pull/2516.
Preview [here](https://security-docs_2530.docs-preview.app.elstc.co/guide/en/security/master/endpoint-artifacts.html)
=> [DOCS] Create stub page for Endpoint artifacts clarification page

docs/release-notes.asciidoc, docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/2548.
Previews:
- [Index page](https://security-docs_2549.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_2549.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.7)
=> [DOCS] 7.17.7 Release notes 

docs/dashboards/kubernetes-dashboard.asciidoc
Fixes #2606 
Updates the DaemonSet manifest URL in the K8s Dashboard instructions (`curl` command) to refer to the latest version of the manifest, located at: https://raw.githubusercontent.com/elastic/endpoint/main/releases/8.5.0/kubernetes/deploy/elastic-defend.yaml
=> [DOCS] Updates DaemonSet manifest download URL

docs/upgrade/upgrade-security.asciidoc
Resolves #2443.
Replaces #2628 -- that PR was based on `main`, but we only want to update `8.1` and `8.0` branches.
Also replaces #2642, which attempted cherry-picking but created too many merge conflicts.
=> [DOCS] [RE-DO v2] Update prebuilt rules before upgrading Kibana to 8.x +

docs/upgrade/upgrade-security.asciidoc
This will backport the following commits from `8.1` to `8.0`:
- [All the changes from #2628 (#2643)](https://github.com/elastic/security-docs/pull/2643)
=> [8.0] [DOCS] [RE-DO v2] Update prebuilt rules before upgrading Kibana to 8.x +

docs/detections/alerts-run-osquery.asciidoc, docs/detections/invest-guide-run-osquery.asciidoc, docs/detections/osquery-response-action.asciidoc
Updates doc links to match changes in https://github.com/elastic/observability-docs/pull/2334.
=> Update links to agent monitoring docs

docs/dashboards/kubernetes-dashboard.asciidoc
Fixes #2729 by referencing the correct file name in the example commands on the K8s dashboard page.
[Preview](https://security-docs_2730.docs-preview.app.elstc.co/guide/en/security/master/kubernetes-dashboard.html)
=> [DOCS] Fixes K8s dashboard docs bug

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Relates to: https://github.com/elastic/security-docs/issues/2684
Feature tickets:  https://github.com/elastic/kibana/issues/145093 https://github.com/elastic/kibana/issues/139802
Implemented in PR: https://github.com/elastic/kibana/pull/144461
=> Document the new skipped response parameter of the _bulk_action endpoint

docs/detections/api/rules/signals-api-overview.asciidoc
Fixes #2798. Small bugfix.
[Preview](https://security-docs_2811.docs-preview.app.elstc.co/guide/en/security/master/signals-api-overview.html)
=> [8.6] Changes 'in-progress' to 'acknowledged'

docs/getting-started/install-endpoint.asciidoc
Resolves #2803.
Preview: [Configure and install the Elastic Defend integration](https://security-docs_2809.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html)
REVIEWERS: Please let me know if the new statement in the Requirements sidebar needs more detail — I was going for short & sweet for impact, but we can expand if necessary. The existing section [Configure and enroll the Elastic Agent](https://security-docs_2809.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html#enroll-security-agent) (lower on the same page) also explains the Fleet requirement with a bit more detail.
=> [BUG] Clarify that Elastic Defend requries Fleet

docs/release-notes.asciidoc, docs/release-notes/8.5.asciidoc
This will backport the following commits from `main` to `8.6`:
- [[DOCS] 8.5.3 Release notes (#2756)](https://github.com/elastic/security-docs/pull/2756)
=> [8.6] [DOCS] 8.5.3 Release notes (#2756)

docs/release-notes/8.6.asciidoc
There is a known issue in the 8.6.0 Agent that we found today that we want to add to the release notes for the 8.6.0 release.
=> [OSQuery] Add a known issue to the release notes for the 8.6.0 OSQuery Manager integration

docs/cloud-native-security/cloud-nat-sec-kubernetes-dashboard.asciidoc, docs/dashboards/kubernetes-dashboard.asciidoc
Fixes #2801 by adding a note that mentions that when Elastic Endpoint is running in Kubernetes, the Malware Prevention and Host Isolation features are disabled.
Preview: [Kubernetes dashboard ](https://security-docs_2890.docs-preview.app.elstc.co/guide/en/security/master/cloud-nat-sec-kubernetes-dashboard.html)
=> [DOCS] Adds note about disabled Endpoint features in K8s

docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rule-8-3-4-exchange-mailbox-export-via-powershell.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rule-8-3-4-exporting-exchange-mailbox-via-powershell.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rule-8-3-4-multiple-alerts-in-different-att-ck-tactics-on-a-single-host.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rule-8-3-4-multiple-alerts-involving-a-user.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rule-8-3-4-suspicious-werfault-child-process.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rules-8-3-4-appendix.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rules-8-3-4-summary.asciidoc, docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc, docs/index.asciidoc
Release Issue:
* https://github.com/elastic/ia-trade-team/issues/91
Security Doc updates for prebuilt security rule integration package version v8.3.4. Please note these are meant to merge into main for 8.x series only and backport to 8.3, 8.4, 8.5 and 8.6.
Important Checks:
For grammar, punctuation, spelling and related changes, please open a rule tuning PR in [detection rules](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md). When merged, security docs will be updated next OOB release.
=> [8.3] Adding Documents for v8.3.4 Pre-Built Detection Rules Integration Release

docs/es-overview.asciidoc, docs/getting-started/advanced-setting.asciidoc, docs/getting-started/install-endpoint.asciidoc, docs/management/admin/admin-pg-ov.asciidoc
This pre-emptively fixes broken links that will occur when the docs shared `ingest-guide` attribute is repurposed.
```
15:24:17 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/security/7.9/admin-page-ov.html contains broken links to:
15:24:17 INFO:build_docs:   - en/ingest/7.9/ingest-management-troubleshooting.html
15:24:17 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/security/7.9/advanced-settings.html contains broken links to:
15:24:17 INFO:build_docs:   - en/ingest/7.9/ingest-management-overview.html
15:24:17 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/security/7.9/es-overview.html contains broken links to:
15:24:17 INFO:build_docs:   - en/ingest/7.9/ingest-management-overview.html
15:24:17 INFO:build_docs: …
```
=> Replace outdated ingest-guide attribute

docs/getting-started/detections-req.asciidoc
Fixes https://github.com/elastic/security-docs/issues/2937.
Preview [here](https://security-docs_2938.docs-preview.app.elstc.co/guide/en/security/master/detections-permissions-section.html#enable-detections-ui).
=> [BUG] Update .alerts-security.alerts-default index name

docs/getting-started/offline-endpoint.asciidoc
During testing I found an error in the sample command we provide as part of these new 8.6 docs. The previous script downloaded some files to an incorrect file path which caused Elastic Endpoint to ignore the artifact update.
Also during testing, I found an Endpoint bug https://github.com/elastic/endpoint-dev/issues/12382 which causes Endpoint to reject some requests from nginx artifact servers. So I updated the example configuration with a workaround.
I tested these updated commands as well as the nginx configuration and httpd configuration on a Windows 10 VM and confirmed Endpoint downloads and installed the updated artifacts using this download script 🚀
=> fix air-gapped artifact download commands

docs/reference/alert-schema.asciidoc
Fixes #3007 by adding missing fields to the Alerts schema
Preview: [Alert schema](https://security-docs_3008.docs-preview.app.elstc.co/guide/en/security/master/alert-schema.html)
=> [bug] Add 5 missing fields to Alerts schema

docs/detections/shared-exception-lists.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3219.
Preview [here](https://security-docs_3249.docs-preview.app.elstc.co/guide/en/security/master/shared-exception-lists.html#manage-exception-lists).
=> Shared exception lists can be duplicated 

docs/getting-started/cases-req.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3239.
Added note to the Cases topic that tells users they might need additional feature privs manage case attachments. Preview [here](https://security-docs_3261.docs-preview.app.elstc.co/guide/en/security/master/case-permissions.html).
=> [BUG] Document required Security privs for cases

docs/detections/add-exceptions.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3301.
Preview [here](https://security-docs_3302.docs-preview.app.elstc.co/guide/en/security/master/add-exceptions.html) - Updates description for the `matches | does not match` options and re-adds the note after the description.
=> [BUG] Re-add note about escaping special characters

docs/cases/cases-manage.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3206.
Preview [here](https://security-docs_3311.docs-preview.app.elstc.co/guide/en/security/8.7/cases-open-manage.html#cases-export-import): Added note to convey that alerts aren't exported with cases.
=> [BUG][8.3-8.7] Add note that alerts attached to cases are not exported

docs/cases/cases-manage.asciidoc
Backports the following commits to 8.6:
- [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)
=> [8.6] [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)

docs/cases/cases-manage.asciidoc
Backports the following commits to 8.3:
- [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)
=> [8.3] [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)

docs/cases/cases-manage.asciidoc
Backports the following commits to 8.4:
- [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)
=> [8.4] [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)

docs/cases/cases-manage.asciidoc
Backports the following commits to 8.5:
- [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)
=> [8.5] [BUG][8.8] Add note that alerts attached to cases are not exported (#3310)

docs/release-notes/8.8.asciidoc
Adds a discrete tag so the 8.8 release notes don't appear as a sub-page in the TOC.
=> [BUG] Adding discrete tag to 8.0 header

docs/detections/api/rules/rules-api-bulk-actions.asciidoc
I made a mistake when drafting these docs for @nastasha-solomon, timezone names like `Europe/Madrid` or `America/New_York` are actually called IANA timezones, not ISO. Small error but we want to be clear on this.
=> Change 'ISO timezone' to 'IANA timezone' in conditional actions docs

docs/release-notes/8.8.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3375.
Preview [here](https://security-docs_3376.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.8.0.html#known-issue-8.8.0).
=> Fields browser is causing all field types to display as the "unknown"

docs/release-notes/8.8.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3391.
Preview [here](https://security-docs_3393.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.8.0.html#enhancements-8.8.0).
=> Users can now use FQDN names for their hosts

docs/assistant/security-assistant.asciidoc, docs/index.asciidoc
Adds stub page for Security Assistant (https://github.com/elastic/security-docs/issues/3420). Docs to follow in a separate PR.
=> Add stub page for Security Assistant

docs/getting-started/ingest-data.asciidoc
Updates the name and URL of the Splunk topic.
Fixes link error in https://github.com/elastic/observability-docs/pull/2990
=> Fix link to obs guide topic about Splunk

docs/release-notes/8.8.asciidoc
Removes the breaking changes tag from the 8.8.0 breaking changes section in the Security release notes. This ensures the 8.8 [Elastic Security breaking changes](https://www.elastic.co/guide/en/elastic-stack/current/security-breaking-changes.html) page reflects the 8.8.1 breaking changes tagged region in the `8.8.asciidoc` file.
=> Remove 8.8.0 BC tag

docs/detections/rules-ui-manage.asciidoc
Fixes 8.0 for #3462.
Preview: [Manage detection rules](https://security-docs_3463.docs-preview.app.elstc.co/guide/en/security/8.0/rules-ui-management.html)
=> [BUG] Remove advanced sorting toggle on Rules page [8.0]

docs/detections/rules-ui-manage.asciidoc
This will backport the following commits from `8.0` to `7.17`:
- [Remove advanced sorting toggle on Rules page (#3463)](https://github.com/elastic/security-docs/pull/3463)
=> [7.17] Remove advanced sorting toggle on Rules page (#3463)

docs/getting-started/offline-endpoint.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3429.
NOTE: The note I added to both sections is the same, so you really only need to review one. I'll apply whatever feedback you have to the other section.
Preview:
- [Host an Elastic Endpoint artifact mirror | Step 1](https://security-docs_3476.docs-preview.app.elstc.co/guide/en/security/master/offline-endpoint.html#_step_1_deploy_an_http_reverse_proxy_server)
- [Host an air-gapped Elastic Endpoint artifact server | Step 1](https://security-docs_3476.docs-preview.app.elstc.co/guide/en/security/master/offline-endpoint.html#_step_1_deploy_an_http_file_server)
=> Add ETag information to self-hosted artifact sections

docs/events/timeline-templates.asciidoc
Fixes [#3526](https://github.com/elastic/security-docs/issues/3526).
Adds two missing timeline templates to 'About Timeline templates' page.
Preview: [About Timeline Templates](https://security-docs_3534.docs-preview.app.elstc.co/guide/en/security/master/timeline-templates-ui.html)
=> [BUG] Adds missing timeline templates

docs/cases/cases-manage.asciidoc
Relates to https://github.com/elastic/kibana/issues/132209, https://github.com/elastic/security-docs/issues/3480
This PR updates https://www.elastic.co/guide/en/security/master/cases-open-manage.html#cases-lens-visualization to include information about the new ability to attach visualizations to cases from within dashboards.
=> [DOCS] Add lens visualizations to cases from dashboards

docs/detections/rules-ui-manage.asciidoc
Backports the following commits to 8.6:
- add prebuilt rules tags section (#3625)
=> [8.6] Prebuilt rules tags documentation (backport #3625)

docs/experimental-features/investigation-guide-actions.asciidoc
Backports the revised compatibility callout as part of #3188.
Doing this manually because the file `investigation-guide-actions.asciidoc` was moved in the main/8.9 PR (#3503), along with several other non-backportable changes that make it difficult to use Mergify or backport tool. Once this PR is merged to `8.8`, then I should be able to use the backport tool to update `8.7` and `8.6`. 🤞
[Preview](https://security-docs_3505.docs-preview.app.elstc.co/guide/en/security/8.8/interactive-investigation-guides.html)
=> Backport updates to compatibility callout - investigation guides

docs/release-notes/8.0.asciidoc, docs/release-notes/8.1.asciidoc, docs/release-notes/8.2.asciidoc, docs/release-notes/8.3.asciidoc, docs/release-notes/8.4.asciidoc, docs/release-notes/8.5.asciidoc, docs/release-notes/8.6.asciidoc, docs/release-notes/8.8.asciidoc, docs/release-notes/8.9.asciidoc
With https://github.com/elastic/stack-docs/pull/2495 merged, we no longer need tags to reuse breaking changes in the Stack Install/Upgrade guide.
=> Remove breaking changes tags

docs/management/api/get-endpoint-api.asciidoc, docs/management/api/list-endpoints-api.asciidoc
fixes #3684 
Update the docs with the modifications of PR https://github.com/elastic/kibana/pull/162142.
It adds:
- sorting to the list endpoints API
- ~`enrolled_at` field to the response of the list endpoints API and get endpoint API~
=> Add sorting to Endpoint Metadata routes

docs/cases/cases-manage.asciidoc, docs/index.asciidoc
This PR removes a tagged region to err on the side of simplicity as we migrate our content.
=> [DOCS] Remove content reuse for cases

docs/release-notes/8.9.asciidoc
Adds a reference to the [missing events](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-syntax.html#eql-missing-events) section of the EQL syntax reference docs.
Preview
=> Adds cross ref to 8.9.1 release notes 

docs/detections/alerts-view-details.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3041.
[Preview](https://security-docs_3681.docs-preview.app.elstc.co/guide/en/security/8.6/view-alert-details.html#alert-details-insights) - Re-added the beta tag to docs for the Alerts related by process ancestry section.
=> [BUG][8.6] Re-add the beta tag to docs for the Alerts related by process ancestry section

docs/detections/alerts-view-details.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3041.
[Preview](https://security-docs_3682.docs-preview.app.elstc.co/guide/en/security/8.5/view-alert-details.html#alert-details-insights) - Re-added the beta tag to docs for the Alerts related by process ancestry section.
=> [BUG][8.5] Re-add the beta tag to docs for the Alerts related by process ancestry section

docs/detections/api/exceptions/api-create-exception-item.asciidoc, docs/detections/api/exceptions/api-update-exception-container.asciidoc
Fixes the first item in https://github.com/elastic/security-docs/issues/3160 and adds the changes being made in https://github.com/elastic/security-docs/pull/3756 and in https://github.com/elastic/security-docs/pull/3419.
- [Update exception container](https://security-docs_3819.docs-preview.app.elstc.co/guide/en/security/master/exceptions-api-update-container.html): Updates the endpoint's request URL from `PUT <kibana host>:<port>/api/lists` to `PUT <kibana host>:<port>/api/exception_lists`
- [Create exception item](https://security-docs_3819.docs-preview.app.elstc.co/guide/en/security/master/exceptions-api-create-exception-item.html): Fixes the URL used in the examples. Changes `POST api/lists/exception_lists/items` to `POST api/exception_lists/items`.
=> [API docs] Fixes URLs in the update exception container docs and create exception item docs

docs/whats-new.asciidoc
- Resolves #3941 
Preview: [What’s new in 8.10](https://security-docs_3942.docs-preview.app.elstc.co/guide/en/security/master/whats-new.html)
=> Adds a blog post link to release highlights

docs/upgrade/upgrade-security.asciidoc
- Resolves #3924 
Preview: [Upgrade Elastic Security to 8.10.0](https://security-docs_3959.docs-preview.app.elstc.co/guide/en/security/master/upgrade-intro.html)
=> Fixes breaking changes links in Upgrade guide

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
- Resolves #3987.
Previews: 
- [Create rule](https://security-docs_3994.docs-preview.app.elstc.co/guide/en/security/8.5/rules-api-create.html#req-fields-new-terms)
- [Update rule](https://security-docs_3994.docs-preview.app.elstc.co/guide/en/security/8.5/rules-api-create.html#req-fields-new-terms)
=> Modifies description of `new_terms_fields`

docs/release-notes/8.10.asciidoc
Resolves #4055 
Preview: [8.10.4 RNs](https://security-docs_4056.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.10.1.html)
=> adds note about security update to 8.10.4 RNs

docs/detections/api/rules/rules-api-create.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4082.
[Preview](https://security-docs_4085.docs-preview.app.elstc.co/guide/en/security/8.10/rules-api-create.html#opt-fields-all) - Removed the `investigation_fields` parameter from the Create rule API docs.
=> [Docs][Rules] Remove custom highlighted fields params from Rule Creation API Docs in 8.10 

docs/detections/rules-ui-create.asciidoc
Applies changes from https://github.com/elastic/security-docs/pull/4197 to 8.11 branch.
=> [8.11] Remove note that's in progress

docs/release-notes/8.11.asciidoc, docs/whats-new.asciidoc
Fixes #4210 by adding beta tag to release notes & What's New highlights.
Previews:
- [What's new | Elastic AI Assistant enhancements](https://security-docs_4211.docs-preview.app.elstc.co/guide/en/security/master/whats-new.html#_elastic_ai_assistant_enhancements)
- [8.11 release notes](https://security-docs_4211.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.11.0.html)
=> Add beta tag for AI Assistant knowledge base

docs/release-notes/8.11.asciidoc
We discovered an issue in the Protection Updates feature released in `8.11.0` that we will fix for `8.11.1`.  We'd like to add another entry to known issues for `8.11.0` before the fix goes out in the next patch.
The issue is that if the user picks the current date, it's possible that we haven't released a protection update yet for that date, so the Agent will go to an Unhealthy state.  The workaround is to pick a previous date like the day before.  The upcoming fix will simply disallow users from selecting the current date from the UI to reduce the user confusion
Related bug ticket: https://github.com/elastic/kibana/issues/170847
=> [Security Solution] Add known issue for date selection in Protection Updates

docs/release-notes/8.11.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4247
[Preview](https://security-docs_4248.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.11.0.html#features-8.11.0) - Links and issue numbers removed for the last four features
=> [BUG] 8.11.0 release notes include links to private repository

docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 7.10

docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 7.11

docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 7.12

docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 7.15

docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 7.14

docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-account-configured-with-never-expiring-password.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-suspicious-werfault-child-process.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-3/prebuilt-rule-7-16-3-account-configured-with-never-expiring-password.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-3/prebuilt-rule-7-16-3-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-3/prebuilt-rule-7-16-3-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-4/prebuilt-rule-7-16-4-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-4/prebuilt-rule-7-16-4-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-4/prebuilt-rule-7-16-4-suspicious-werfault-child-process.asciidoc, docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 7.16

docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-account-configured-with-never-expiring-password.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-16-2/prebuilt-rule-0-16-2-suspicious-werfault-child-process.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-3/prebuilt-rule-7-16-3-account-configured-with-never-expiring-password.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-3/prebuilt-rule-7-16-3-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-3/prebuilt-rule-7-16-3-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-4/prebuilt-rule-7-16-4-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-4/prebuilt-rule-7-16-4-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/7-16-4/prebuilt-rule-7-16-4-suspicious-werfault-child-process.asciidoc, docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 7.17

docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc, docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc, docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
=> Update Prebuilt Rule Links for Malicious Site in 8.0

docs/detections/machine-learning/machine-learning.asciidoc, docs/experimental-features/experimental-features-intro.asciidoc
Resolves #4169.
Removes [Network Beaconing](https://www.elastic.co/guide/en/security/current/network-beaconing-framework.html) from the Technical Preview section. Adds a link to [Network Beaconing Identification](https://docs.elastic.co/integrations/beaconing) under [Anomaly detection with machine learning](https://www.elastic.co/guide/en/security/current/machine-learning.html#ml-integrations).
Also updates integrations docs links to use attribute.
Preview: [Anomaly detection with machine learning](https://security-docs_4192.docs-preview.app.elstc.co/guide/en/security/master/machine-learning.html#ml-integrations)
=> Replaces Network Beaconing docs

docs/management/admin/response-actions-config.asciidoc, docs/management/manage-intro.asciidoc
Contributes to #4312 by creating a stub page for the configuration docs.
Preview: https://security-docs_4317.docs-preview.app.elstc.co/guide/en/security/master/response-actions-config.html
=> Create stub page for bi-directional integration response actions (SentinelOne) 

docs/detections/api/exceptions-api-index.asciidoc, docs/detections/api/exceptions/api-export-exception-list.asciidoc
This will backport the following commits from `main` to `7.13`:
- [Adds Export exception list API docs (#4316)](https://github.com/elastic/security-docs/pull/4316)
=> [7.13] Adds Export exception list API docs (#4316)

docs/detections/api/exceptions-api-index.asciidoc, docs/detections/api/exceptions/api-export-exception-list.asciidoc
This will backport the following commits from `main` to `7.12`:
- [Adds Export exception list API docs (#4316)](https://github.com/elastic/security-docs/pull/4316)
=> [7.12] Adds Export exception list API docs (#4316)

docs/detections/api/exceptions-api-index.asciidoc, docs/detections/api/exceptions/api-export-exception-list.asciidoc
This will backport the following commits from `main` to `7.11`:
- [Adds Export exception list API docs (#4316)](https://github.com/elastic/security-docs/pull/4316)
=> [7.11] Adds Export exception list API docs (#4316)

docs/getting-started/advanced-setting.asciidoc
Contributes to https://github.com/elastic/staging-serverless-security-docs/pull/213 by updating classic docs to remove the advanced setting `enableGroupedNav`. This setting was actually removed from the product in 8.9 and we never updated the docs, so we need to backport to that version.
Preview: [Advanced settings](https://security-docs_4362.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html)
* If you're reviewing this PR, you should probably also review https://github.com/elastic/staging-serverless-security-docs/pull/213 to see the serverless docs changes
=> Remove enableGroupedNav advanced setting

docs/detections/api/exceptions/api-export-exception-list.asciidoc
Resolves #3061 by adding the `include_expired_exceptions` to versions `8.7` and newer.
Preview: [Export exception list](https://security-docs_4360.docs-preview.app.elstc.co/guide/en/security/master/exceptions-api-export-exception-list.html)
=> Adds `include_expired_exceptions` to Export exception list API

.github/workflows/docs-preview.yml
Contributes to https://github.com/elastic/security-docs/issues/4313 by adding a new GitHub action that provides links to both Buildkite and Jenkins build previews.
=> Add Buildkite preview links to PRs

docs/advanced-entity-analytics/behavioral-detection-use-cases.asciidoc
Fixes the requirement statement on the [Behavioral detection use cases](https://www.elastic.co/guide/en/security/8.11/behavioral-detection-use-cases.html) page, since not all Elastic integrations require a Platinum subscription.
Preview: [Behavioral detection use cases](https://security-docs_bk_4470.docs-preview.app.elstc.co/guide/en/security/master/behavioral-detection-use-cases.html)
=> Fixes requirement statement on Behavioral detection use cases page

docs/detections/visual-event-analyzer.asciidoc, docs/getting-started/advanced-setting.asciidoc
Contributes to #4387.
Corresponding serverless PR: https://github.com/elastic/staging-serverless-security-docs/pull/250
Previews:
* [Exclude cold and frozen tier data from analyzer queries](https://security-docs_bk_4484.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html#exclude-cold-frozen-tiers)
* [Visual event analyzer](https://security-docs_bk_4484.docs-preview.app.elstc.co/guide/en/security/master/visual-event-analyzer.html)
=> Exclude cold and frozen tiers advanced setting

docs/assistant/security-assistant.asciidoc, docs/detections/about-rules.asciidoc, docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/rules-ui-create.asciidoc, docs/events/timeline-ui-overview.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4538
Previews: Updates the tech preview note to match the wording used in https://github.com/elastic/elasticsearch/pull/103797
- [Use ES|QL to investigate events](https://security-docs_bk_4554.docs-preview.app.elstc.co/guide/en/security/master/timelines-ui.html#esql-in-timeline)
- [Configure AI Assistant | Knowledge base](https://security-docs_bk_4554.docs-preview.app.elstc.co/guide/en/security/master/security-assistant.html#ai-assistant-knowledge-base)
- [About detection rules](https://security-docs_bk_4554.docs-preview.app.elstc.co/guide/en/security/master/about-rules.html)
- [Create an ES|QL rule](https://security-docs_bk_4554.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#create-esql-rule)
- [Create …
=> [Request][REDO] Add warning against using ES|QL on production environmentsFirst draft

docs/management/api/get-file-api.asciidoc
Per https://github.com/elastic/security-docs/pull/4500, fixes the 'Get a file from a host' endpoint to `get_file`.
Preview: [Get a file from a host](https://security-docs_bk_4526.docs-preview.app.elstc.co/guide/en/security/master/get-file-api.html)
cc @nathandh22
=> Fixes get file API typo

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
Backports the following commits to 8.10:
=> [8.10] Backport query rule alert suppression to API docs (#4496)

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
Backports the following commits to 8.9:
=> [8.9] Backport query rule alert suppression to API docs (#4496)

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
Backports the following commits to 8.8:
=> [8.8] Backport query rule alert suppression to API docs (#4496)

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
Backports the following commits to 8.7:
=> [8.7] Backport query rule alert suppression to API docs (#4496)

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
Backports the following commits to 8.6:
=> [8.6] Backport query rule alert suppression to API docs (#4496)

docs/detections/api/rules/signals-api-overview.asciidoc
Fixes #4567 by updating the `tags` parameter's data type in the description to object.
Preview: [Signals endpoint](https://security-docs_bk_4581.docs-preview.app.elstc.co/guide/en/security/master/signals-api-overview.html#_apply_alert_tags)
=> Fixes data type inconsitency in Apply alert tags API

docs/getting-started/advanced-setting.asciidoc
Contributes to #4541 by removing the list of default Elastic Security index patterns.
Preview: [Update default Elastic Security indices](https://security-docs_bk_4558.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html#update-sec-indices)
Serverless PR: https://github.com/elastic/staging-serverless-security-docs/pull/257
=> Removes list of default index patterns

docs/release-notes/8.11.asciidoc
[Preview](https://security-docs_bk_4597.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.11.0.html#release-notes-8.11.4) - Fixes minor typos in the first bullet
=> [ESS][BUG][8.14.11]Fixes minor typos in the 8.11.4 release notes

docs/advanced-entity-analytics/machine-learning.asciidoc
Resolves https://github.com/elastic/security-docs/issues/3997 by removing the outdated tip about custom ML jobs, in classic docs. No twin PR needed; serverless docs have already been updated.
Backport to 8.10.
=> [BUG] Remove outdated note in ML docs

docs/management/api/execute-api.asciidoc
Manually backporting changes made in https://github.com/elastic/security-docs/pull/4236 due to an error in the [mergify backport](https://github.com/elastic/security-docs/pull/4654).
=> [8.12] Correct bugs in Execute action API docs (backport #4236)

docs/osquery/alerts-run-osquery.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/4626
[Preview](https://security-docs_bk_4658.docs-preview.app.elstc.co/guide/en/security/master/alerts-run-osquery.html) - Updated step 5
Twin Serverless PR: https://github.com/elastic/staging-serverless-security-docs/pull/274
=> [BUG][ESS] Outdated information mentioned in the step 5 for Osquery

docs/management/admin/endpoint-artifacts.asciidoc, docs/management/admin/trusted-apps.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/3489 by updating the classic docs with additional explanation of how process events are still created for trusted applications.
Previews:
- [Trusted applications](https://security-docs_bk_4640.docs-preview.app.elstc.co/guide/en/security/master/trusted-apps-ov.html) — New paragraph explains process events.
- [Optimize Elastic Defend](https://security-docs_bk_4640.docs-preview.app.elstc.co/guide/en/security/master/endpoint-artifacts.html) — Expands trusted apps bullet for additional context.
- https://github.com/elastic/staging-serverless-security-docs/pull/272
=> [BUG] Endpoint Trusted Applications docs need to mention that process events will always be generated (Classic docs)

docs/detections/rules-ui-create.asciidoc
Resolves #4119 by adding a note that says you can't use nested fields for "group by" to the doc about how to make a threshold rule.
Please let me know if you think we should add any other details. One thing we could consider adding a link to this page: https://www.elastic.co/guide/en/elasticsearch/reference/8.12/nested.html
Preview: Create a threshold rule
=> Documents that nested fields aren't supported for Theshold rules "Group by" operations

docs/assistant/security-assistant.asciidoc
Fixes #4735 
Minor change to remove references to an implementation detail that users don't need to know about
Preview: [AI Assistant](https://security-docs_bk_4736.docs-preview.app.elstc.co/guide/en/security/master/security-assistant.html)
=> Removes references to RAG from AI Assistant docs

docs/assistant/security-assistant.asciidoc, docs/release-notes.asciidoc, docs/release-notes/8.12.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4712
Previews:
- [Index page](https://security-docs_bk_4719.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_bk_4719.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.12.0.html#release-notes-8.12.1)
=> 8.12.1 Release notes

docs/detections/add-exceptions.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/4757
[Preview](https://security-docs_bk_4758.docs-preview.app.elstc.co/guide/en/security/master/add-exceptions.html): Updated note at the top of the page
Serverless twin PR: https://github.com/elastic/staging-serverless-security-docs/pull/288
=> [BUG][8.6-8.12]Fix note that describes how exceptions work with EQL rules 

README.md
Very minor fix removing a broken link in the repo's README.
=> removes broken link in README

docs/getting-started/agent-tamper-protection.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/4741 by adding an OS support statement to the classic docs.
Preview:
- [Prevent Agent uninstallation](https://security-docs_bk_4751.docs-preview.app.elstc.co/guide/en/security/master/agent-tamper-protection.html)
Twin PR for serverless docs:
- https://github.com/elastic/staging-serverless-security-docs/pull/286
=> [BUG] Add supported operating system to the tamper protection page [classic]

README.md
Following the migration from Jenkins to Buildkite, docs previews are now available at <repo>_bk_<PR>.
More context in https://github.com/elastic/docs/pull/2898
=> Update docs-preview link

docs/assistant/ai-alert-triage.asciidoc, docs/assistant/security-assistant.asciidoc
Fixes #4791. Adds a link to James Spiteri's demo video that shows several uses of AI Assistant.
Preview:[ Triage Alerts with AI Assistant](https://security-docs_bk_4792.docs-preview.app.elstc.co/guide/en/security/master/assistant-triage.html)
=> Adds demo video to the AI Assistant docs

docs/assistant/security-assistant.asciidoc
Fixes #4799 
Minor language update to refer to LLMs instead of just OpenAI in one place.
Preview: [AI Assistant](https://security-docs_bk_4800.docs-preview.app.elstc.co/guide/en/security/master/security-assistant.html)
=> Removes model-specific (OpenAI) language from AI Assistant intro

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/rules-ui-create.asciidoc
Related to https://github.com/elastic/security-docs/pull/4813
Re-attempting the backports that failed [here](https://github.com/elastic/security-docs/pull/4813#issuecomment-1947340400).
=> [Known Issue][8.10-8.5] Add docs to describe a known issue/limitation of EQL rule cross-cluster search

docs/cloud-native-security/cspm-get-started-aws.asciidoc, docs/cloud-native-security/cspm-get-started-azure.asciidoc, docs/cloud-native-security/cspm-get-started-gcp.asciidoc, docs/cloud-native-security/cspm.asciidoc
Fixes #4809 - clarifies CSPM's support for commercial vs government cloud products.
Previews: 
[CSPM for Azure](https://security-docs_bk_4812.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started-azure.html)
[CSPM for AWS](https://security-docs_bk_4812.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started.html)
[CSPM for GCP](https://security-docs_bk_4812.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started-gcp.html)
[CSPM](https://security-docs_bk_4812.docs-preview.app.elstc.co/guide/en/security/master/cspm.html)
=> Clarify GovCloud/commercial cloud support for CSPM 

docs/detections/detections-ui-exceptions.asciidoc
Applies changes from https://github.com/elastic/security-docs/pull/3860 to the 7.17-8.5 docs.
Previews:
- [Add exceptions to a rule](https://security-docs_bk_4806.docs-preview.app.elstc.co/guide/en/security/8.5/detections-ui-exceptions.html#detection-rule-exceptions)
- [Add Elastic endpoint exceptions](https://security-docs_bk_4806.docs-preview.app.elstc.co/guide/en/security/8.5/detections-ui-exceptions.html#endpoint-rule-exceptions)
=> [Redo][7.17-8.5] Highlight that rule exceptions are case-sensitive

docs/management/api/_common-reusable-content.asciidoc, docs/management/api/_response-actions-api-reusable-content.asciidoc, docs/management/api/execute-api.asciidoc, docs/management/api/get-action-api.asciidoc, docs/management/api/get-file-api.asciidoc, docs/management/api/host-isolation-api.asciidoc, docs/management/api/host-isolation-release-api.asciidoc, docs/management/api/kill-process-api.asciidoc, docs/management/api/list-actions-api.asciidoc, docs/management/api/running-procs-api.asciidoc, docs/management/api/suspend-process-api.asciidoc, docs/management/api/upload-api.asciidoc
- Adds `agentType` to all response action create APIs
- Adjust response examples to include a new `agentType` property
- Response action list API: adds missing docs for `types` and `withOutputs` query parameters
> [!NOTE]
> Because the response action create APIs share most of the attributes in the request body, some refactoring was done to re-use that content across all API docs
=> [8.13] Update Response Actions APIs as a result of introducing `agentType`

docs/detections/add-exceptions.asciidoc
Preview:
- [Add and manage exceptions](https://security-docs_bk_4835.docs-preview.app.elstc.co/guide/en/security/master/add-exceptions.html) - Slight update to https://github.com/elastic/security-docs/pull/4805. Moved note about exceptions being case-sensitive to Endpoint exceptions section. 
Note: No need to backport this to 8.13. Have already done this with https://github.com/elastic/security-docs/pull/4825.
=> [BUG] Minor ordering fix

docs/troubleshooting/management/ts-management.asciidoc
Contributes to #2353.
Preview: [Endpoint management](https://security-docs_bk_4870.docs-preview.app.elstc.co/guide/en/security/master/ts-management.html)
Serverless twin PR: https://github.com/elastic/staging-serverless-security-docs/pull/295
=> Adds Agent–Endpoint troubleshooting doc

docs/detections/detections-ui-exceptions.asciidoc
- [Redo][7.17-8.5] Highlight that rule exceptions are case-sensitive (#4806)
=> [8.1] [Redo][7.17-8.5] Highlight that rule exceptions are case-sensitive (#4806)

docs/detections/detections-ui-exceptions.asciidoc
- [Redo][7.17-8.5] Highlight that rule exceptions are case-sensitive (#4806)
=> [8.0] [Redo][7.17-8.5] Highlight that rule exceptions are case-sensitive (#4806)

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/rules-ui-create.asciidoc
Backports the following commits to 8.9:
=> [8.9] [Known Issue] Add docs to describe a known issue/limitation of EQL rule cross-cluster search (#4813)

docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/rules-ui-create.asciidoc
Backports the following commits to 8.5:
=> [8.5] [Known Issue] Add docs to describe a known issue/limitation of EQL rule cross-cluster search (#4813)

docs/detections/api/rules/rules-api-bulk-actions.asciidoc, docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3004
Updated description for the `action_type_id` param on the following pages:
- [Create rule](https://security-docs_bk_4935.docs-preview.app.elstc.co/guide/en/security/master/rules-api-create.html#actions-object-schema)
- [Update rule](https://security-docs_bk_4935.docs-preview.app.elstc.co/guide/en/security/master/rules-api-update.html#actions-object-schema-update)
- [Bulk rule actions](https://security-docs_bk_4935.docs-preview.app.elstc.co/guide/en/security/master/bulk-actions-rules-api.html#actions-object-schema-bulk)
=> [ESS][8.12&8.13] Updating list of available rule actions

docs/cloud-native-security/kspm-get-started.asciidoc, docs/cloud-native-security/kspm.asciidoc
Small change to add a requirement for the KSPM integration
Twin PR: https://github.com/elastic/staging-serverless-security-docs/pull/302 
Previews: [here](https://security-docs_bk_4942.docs-preview.app.elstc.co/guide/en/security/master/kspm.html) and [here](https://security-docs_bk_4942.docs-preview.app.elstc.co/guide/en/security/master/get-started-with-kspm.html)
=> Adds note that KSPM doesn't support govcloud

docs/detections/prebuilt-rules-management.asciidoc, docs/upgrade/upgrade-security.asciidoc
Resolves https://github.com/elastic/security-docs/issues/3622 by adding a note explaining how automatic updates for prebuilt rule are supported per Stack version.
- [Upgrade Elastic Security](https://security-docs_bk_4934.docs-preview.app.elstc.co/guide/en/security/master/upgrade-intro.html#_support_for_elastic_prebuilt_detection_rule_automatic_updates) — New subsection
- [Install and manage Elastic prebuilt rules](https://security-docs_bk_4934.docs-preview.app.elstc.co/guide/en/security/master/prebuilt-rules-management.html) — Add new Note
No serverless docs needed, since it's versionless and always on the latest version.
Backport this all the way back. At some point the Mergify backports will fail because we reorganized both pages; use the backport tool or manually open PRs for the …
=> Manual prebuilt rule updates support notice

docs/advanced-entity-analytics/entity-risk-scoring.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/4940 by documenting that the risk scoring engine takes into account up to 10K alerts per entity when calculating risk scores.
Twin serverless PR: https://github.com/elastic/staging-serverless-security-docs/pull/308
Preview: [Entity risk scoring](https://security-docs_bk_4989.docs-preview.app.elstc.co/guide/en/security/master/entity-risk-scoring.html)
=> Max number of alerts per entity processed by risk scoring engine

docs/advanced-entity-analytics/asset-criticality.asciidoc, docs/dashboards/entity-dashboard.asciidoc, docs/getting-started/users-page.asciidoc, docs/management/hosts/hosts-overview.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/4902 by documenting that clicking on a host/user name in the EA dashboard now opens the host/user details flyout instead of the host/user details page.
Also includes a few minor terminology tweaks and typo fixes.
Twin serverless PR: https://github.com/elastic/staging-serverless-security-docs/pull/307
Previews:
* [Entity Analytics dashboard](https://security-docs_bk_4988.docs-preview.app.elstc.co/guide/en/security/master/detection-entity-dashboard.html)
* [Hosts page](https://security-docs_bk_4988.docs-preview.app.elstc.co/guide/en/security/master/hosts-overview.html)
* [Users page](https://security-docs_bk_4988.docs-preview.app.elstc.co/guide/en/security/master/users-page.html)
=> Updates EA dashboard behavior

docs/detections/prebuilt-rules/downloadable-packages/8-4-3/prebuilt-rule-8-4-3-host-files-system-changes-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-4-3/prebuilt-rule-8-4-3-suspicious-execution-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-4-3/prebuilt-rules-8-4-3-summary.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-5-1/prebuilt-rule-8-5-1-host-files-system-changes-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-5-1/prebuilt-rule-8-5-1-suspicious-execution-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-5-1/prebuilt-rules-8-5-1-summary.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-6-1/prebuilt-rule-8-6-1-host-files-system-changes-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-6-1/prebuilt-rule-8-6-1-suspicious-execution-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-6-1/prebuilt-rules-8-6-1-summary.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-7-1/prebuilt-rule-8-7-1-host-files-system-changes-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-7-1/prebuilt-rule-8-7-1-suspicious-execution-via-windows-subsystem-for-linux.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-7-1/prebuilt-rules-8-7-1-summary.asciidoc, docs/release-notes/8.13.asciidoc
Fixes #5014, resolving the problem identified in this PR: https://github.com/elastic/security-docs/pull/5011
Removes extra "the"s from docs. Found a number of places this double word is present.
=> [bugfix] Removes extra "the"s

docs/release-notes.asciidoc, docs/release-notes/7.10.asciidoc, docs/release-notes/7.11.asciidoc, docs/release-notes/7.12.asciidoc, docs/release-notes/7.13.asciidoc, docs/release-notes/7.14.asciidoc, docs/release-notes/7.15.asciidoc, docs/release-notes/7.16.asciidoc, docs/release-notes/7.17.asciidoc, docs/release-notes/7.9.asciidoc, docs/whats-new.asciidoc
Changes all instances of book/section-scoped attributes `{pull}` and `{issue}` to global attributes `{kibana-pull}` and `{kibana-issue}`, within the 7.17 branch.
Also removes the book/section-scoped definitions from the index file `release-notes.asciidoc`.
=> [7.17] Switch to global attributes and remove section-scoped `pull` and `issue`

docs/cases/cases-manage.asciidoc, docs/detections/alerts-add-to-cases.asciidoc
This PR updates https://www.elastic.co/guide/en/security/current/signals-to-cases.html and https://www.elastic.co/guide/en/security/current/cases-open-manage.html#cases-examine-alerts with details about the maximum number of alerts that can be attached to a case.
=> Add limit for number of alerts per case

docs/advanced-entity-analytics/asset-criticality.asciidoc, docs/getting-started/ers-req.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5084.
Previews:
* [Asset criticality](https://security-docs_bk_5096.docs-preview.app.elstc.co/guide/en/security/master/asset-criticality.html)
* [Entity risk scoring prerequisites](https://security-docs_bk_5096.docs-preview.app.elstc.co/guide/en/security/master/ers-requirements.html)
Twin serverless PR: https://github.com/elastic/staging-serverless-security-docs/pull/326
=> Updates docs for ability to unassign asset criticality

docs/assistant/connect-to-bedrock.asciidoc, docs/assistant/security-assistant.asciidoc
Fixes #5113 by adding a page with step by step details for how to set up an Amazon Bedrock connector.
Preview:[Set up an Amazon Bedrock connector](https://security-docs_bk_5148.docs-preview.app.elstc.co/guide/en/security/master/assistant-connect-to-bedrock.html)
=> Creates new page detailing Bedrock connector setup

docs/detections/prebuilt-rules/downloadable-packages/8-12-11/prebuilt-rules-8-12-11-appendix.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-12-11/prebuilt-rules-8-12-11-summary.asciidoc, docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc, docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.12.11. Please note these are meant to merge into 8.12 only and not backport.
=> [Detection Rules] Adding Documents for v8.12.11 Pre-Built Detection Rules

docs/detections/prebuilt-rules/downloadable-packages/8-10-18/prebuilt-rules-8-10-18-appendix.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-10-18/prebuilt-rules-8-10-18-summary.asciidoc, docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc, docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.10.18. Please note these are meant to merge into 8.10 only and not backport.
=> [Detection Rules] Adding Documents for v8.10.18 Pre-Built Detection Rules

docs/detections/prebuilt-rules/downloadable-packages/8-11-15/prebuilt-rules-8-11-15-appendix.asciidoc, docs/detections/prebuilt-rules/downloadable-packages/8-11-15/prebuilt-rules-8-11-15-summary.asciidoc, docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc, docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.11.15. Please note these are meant to merge into 8.11 only and not backport.
=> [Detection Rules] Adding Documents for v8.11.15 Pre-Built Detection Rules

docs/cloud-native-security/cspm-get-started-aws.asciidoc, docs/cloud-native-security/cspm-get-started-azure.asciidoc, docs/cloud-native-security/cspm-get-started-gcp.asciidoc, docs/cloud-native-security/cspm.asciidoc, docs/cloud-native-security/vuln-management-get-started.asciidoc, docs/cloud-native-security/vuln-management-overview.asciidoc
Fixes #5107 
A small change on several pages. I reviewed the [previews](https://security-docs_bk_5154.docs-preview.app.elstc.co/diff) already.
=> Adds kibana namespace requirement to CNVM and CSPM

docs/detections/api/rules/rules-api-bulk-actions.asciidoc, docs/detections/api/rules/rules-api-create.asciidoc, docs/detections/api/rules/rules-api-find.asciidoc, docs/detections/api/rules/rules-api-get.asciidoc, docs/detections/api/rules/rules-api-update.asciidoc
**Epic: https://github.com/elastic/security-team/issues/1974**
**Related to: https://github.com/elastic/kibana/issues/173594**
API updates for https://github.com/elastic/kibana/pull/180682.
Updates related API docs with `required_field` changes made in https://github.com/elastic/kibana/pull/180682.
=> Update API docs for `required_fields`

docs/experimental-features/host-risk-score.asciidoc, docs/experimental-features/user-risk-score.asciidoc
Resolves https://github.com/elastic/security-docs/issues/5191.
Previews:
* [Host risk score](https://security-docs_bk_5209.docs-preview.app.elstc.co/guide/en/security/master/host-risk-score.html)
* [User risk score](https://security-docs_bk_5209.docs-preview.app.elstc.co/guide/en/security/master/user-risk-score.html)
No twin serverless PR since these docs don't exist in serverless.
=> Adds note to legacy risk scoring docs

docs/cloud-native-security/cspm-get-started-aws.asciidoc, docs/cloud-native-security/cspm-get-started-azure.asciidoc, docs/cloud-native-security/cspm-get-started-gcp.asciidoc, docs/cloud-native-security/cspm.asciidoc, docs/cloud-native-security/kspm-get-started.asciidoc, docs/cloud-native-security/kspm.asciidoc
Fixes #5102. Twin PR of [353](https://github.com/elastic/staging-serverless-security-docs/pull/353)
Minor changes, directly ported from the twin PR with no differences other than asciidoc / MDX syntax.
=> [8.14] Introduces AWS GovCloud support for CSPM

docs/getting-started/elastic-endpoint-reqs.asciidoc, docs/serverless/edr-install-config/deploy-endpoint-reqs.mdx
Resolves https://github.com/elastic/security-docs/issues/4636. Adds Endpoint system requirements to ESS and serverless docs.
Previews:
- ESS: [Elastic Endpoint requirements](https://security-docs_bk_5271.docs-preview.app.elstc.co/guide/en/security/master/elastic-endpoint-deploy-reqs.html)
- Serverless: [Install Elastic Endpoint manually](https://docs-elastic-bwb08rn5e-elastic-dev.vercel.app/serverless/security/elastic-endpoint-deploy-reqs)
=> Endpoint system requirements

docs/attack-discovery/attack-discovery.asciidoc, docs/serverless/attack-discovery/attack-discovery.mdx
Fixes #5336 by adding a video demo to the AD docs as requested by James S. The video gives an overview of how AD works and shows it in action. I added it at the top of the page. This update affects both ESS and serverless docs.
Also fixes #5361 by making a minor change to how we discuss AD's 24-hour lookback window for alerts.
Preview: [ESS](https://security-docs_bk_5362.docs-preview.app.elstc.co/guide/en/security/master/attack-discovery.html), [Serverless](https://docs-elastic-8f8lv4mbt-elastic-dev.vercel.app/serverless/security/attack-discovery)
=> Adds a video demo to the AD docs

docs/assistant/azure-openai-setup.asciidoc, docs/assistant/connect-to-openai.asciidoc, docs/serverless/assistant/connect-to-azure-openai.mdx, docs/serverless/assistant/connect-to-openai.mdx
Fixes #5357 by making some minor updates to the OpenAI connector setup guide and the Azure OpenAI setup guide.
Previews: [connect to Azure OpenAI](https://docs-elastic-9676w7w6c-elastic-dev.vercel.app/serverless/security/connect-to-azure-openai)
[Connect to OpenAI](https://docs-elastic-9676w7w6c-elastic-dev.vercel.app/serverless/security/connect-to-openai)
=> Update OpenAI and Azure OpenAI connector setup guides

docs/serverless/what-is-security-serverless.mdx
This is a non-visible change to indicate that the new build pipeline is successful and live on https://www.elastic.co/docs. Safe to merge this once out of draft
=> Update what-is-security-serverless.mdx to force a build

docs/events/timeline-templates.asciidoc, docs/events/timeline-ui-overview.asciidoc, docs/getting-started/siem-ui.asciidoc
=> [7.10] fix: remove ndjson.org (#5376)

docs/events/timeline-templates.asciidoc, docs/events/timeline-ui-overview.asciidoc, docs/getting-started/siem-ui.asciidoc
=> [7.11] fix: remove ndjson.org (#5376)

docs/events/timeline-templates.asciidoc, docs/events/timeline-ui-overview.asciidoc, docs/getting-started/siem-ui.asciidoc
=> [7.12] fix: remove ndjson.org (#5376)

docs/events/timeline-templates.asciidoc, docs/events/timeline-ui-overview.asciidoc, docs/getting-started/siem-ui.asciidoc
=> [7.13] fix: remove ndjson.org (#5376)

docs/events/timeline-templates.asciidoc, docs/events/timeline-ui-overview.asciidoc, docs/getting-started/siem-ui.asciidoc
=> [7.9] fix: remove ndjson.org (#5376) 

.backportrc.json, docs/es-overview.asciidoc
This PR updates the backport tool's config file (`.backportrc.json`) with these fixes:
- Adds missing 7.9 branch
- Makes 7.17 the default/checked branch
(I accidentally called this the .gitignore file in the commit message 🙃 )
=> Fix backport config file in 7.17 branch

docs/detections/api/exceptions/api-update-exception-item.asciidoc
This will backport the following commits from `main` to `7.12`:
- [Fixes &#x60;comments&#x60; description in Update exception item API (#5365)](https://github.com/elastic/security-docs/pull/5365)
=> [7.12] Fixes `comments` description in Update exception item API (#5365)

docs/detections/api/exceptions/api-update-exception-item.asciidoc
Backports the following PR to 7.13:
* https://github.com/elastic/security-docs/pull/5365
=> [7.13] Fixes `comments` description in Update exception item API (#5365)

docs/detections/api/exceptions/api-update-exception-item.asciidoc
Backports the following PR to 7.11:
* https://github.com/elastic/security-docs/pull/5365
=> [7.11] Fixes `comments` description in Update exception item API (#5365)

docs/detections/api/exceptions/api-update-exception-item.asciidoc
Backports the following PR to 7.10:
* https://github.com/elastic/security-docs/pull/5365
=> [7.10] Fixes comments description in Update exception item API (#5365)

docs/detections/api/exceptions/api-update-exception-item.asciidoc
Backports the following PR to 7.9:
* https://github.com/elastic/security-docs/pull/5365
=> [7.9] Fixes comments description in Update exception item API (#5365)

docs/release-notes/8.8.asciidoc
This link points to a setting that I accidently put into the wrong area of the Fleet & Agent docs. I plan to [fix that](https://github.com/elastic/ingest-docs/pull/1092), but before I can, I need to update this link in order not to bust up our docs build.
This link originates in version 8.8 so I hope it's okay to backport to there.
=> Update link in 8.8 release notes

docs/management/admin/response-actions.asciidoc, docs/management/admin/third-party-actions.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5359.
Not looking for any further changes, just code owner approval to unblock. This is a twin of the serverless PR: https://github.com/elastic/security-docs/pull/5444, which has already been approved and merged.
=> SentinelOne `get-file` response action [classic]

docs/serverless/cloud-native-security/d4c-get-started.mdx, docs/serverless/cloud-native-security/d4c-overview.mdx
Fixes #5454 by updating the tech preview badge to beta for D4C docs (serverless)
Previews: [D4C overview](https://elastic-dot-co-docs-production-3icqoy3dk-elastic-dev.vercel.app/current/serverless/security/d4c-overview), [get started with D4C](https://elastic-dot-co-docs-production-3icqoy3dk-elastic-dev.vercel.app/current/serverless/security/d4c-get-started)
=> [Serverless] Updates D4C badge from tech preview to beta 

docs/index.asciidoc, docs/upgrade/upgrade-7.17-8.x.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302.
Preview: [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_5502.docs-preview.app.elstc.co/guide/en/security/7.17/upgrade-7.17-8x.html)
=> Backports upgrade guide to 7.17

docs/cloud-native-security/cspm-get-started-gcp.asciidoc
It's not needed anymore, GCP has removed it.
Can be removed from all versions.
=> Remove cloud shell editor deprecation notification

docs/serverless/cloud-native-security/vuln-management-faq.mdx, docs/serverless/cloud-native-security/vuln-management-get-started.mdx
Fixes #5304. Adds a requirement to the CNVM serverless docs. The language was already approved for the ESS version.
Previews: 
[Get started with CNVM](https://elastic-dot-co-docs-production-h60pov5n9-elastic-dev.vercel.app/current/serverless/security/vuln-management-get-started)
[CNVM FAQ](https://elastic-dot-co-docs-production-h60pov5n9-elastic-dev.vercel.app/current/serverless/security/vuln-management-faq)
=> Serverless twin PR - adds CNVM requirement

docs/AI-for-security/ai-for-security.asciidoc, docs/AI-for-security/connect-to-vertex.asciidoc, docs/AI-for-security/connector-guides-landing-pg.asciidoc
Fixes #5373, adds an llm connector guide for Google Vertex.
Previews: [Connect to Google Vertex](https://security-docs_bk_5549.docs-preview.app.elstc.co/guide/en/security/master/connect-to-vertex.html)
[LLM connector guides](https://security-docs_bk_5549.docs-preview.app.elstc.co/guide/en/security/master/llm-connector-guides.html)
=> [8.15] creates Google vertex guide for ESS

docs/getting-started/data-views-in-sec.asciidoc, docs/serverless/explore/data-views-in-sec.mdx
* Serverless twin follow-up to https://github.com/elastic/security-docs/pull/5513
Adds admonition about data view picker in the Alerts page.
* Updates the **Data views in Elastic Security** serverless page to match its ESS counterpart. It appears the serverless page was never updated to match ESS changes in https://github.com/elastic/security-docs/pull/4695, so this gets ESS + serverless back in sync.
* Fixes URL variable/attribute usage: a few links used `apm-app-ref` instead of `kibana-ref` to point to Kibana docs. Currently the two variables have the same value, so _technically_ the links still go to the right place, but I think that in itself is an error. We should just use the Kibana variable if we want to point to Kibana docs.
* Backports: The errant `apm-app-ref` attribute appears …
=> (Doc+) Alerts UI cannot be CCS [serverless] + bonus fixes

docs/serverless/projects-create/create-project.mdx
Added docs for serverless cloud regions [here](https://github.com/elastic/docs-content/pull/47) - this PR adds an informational link for regions to the security project creation doc. 
I also removed the region proximity guidance from this [on request](https://github.com/elastic/docs-content/pull/47#issuecomment-2250601601). the linked region page provides some similar guidance, just a little less prescriptive
Won't merge until the core doc is merged
=> Add link to region docs

docs/management/admin/allowlist-endpoint-3rd-party-av.asciidoc, docs/management/admin/trusted-apps.asciidoc, docs/serverless/edr-manage/allowlist-endpoint-3rd-party-av.mdx, docs/serverless/edr-manage/trusted-apps-ov.mdx, docs/serverless/serverless-security.docnav.json
Resolves https://github.com/elastic/security-docs/issues/3433, which is a duplicate of https://github.com/elastic/security-docs/issues/3535.
This PR adds the [Allowlist Elastic Endpoint in third-party antivirus apps](https://www.elastic.co/guide/en/security/master/allowlist-endpoint-3rd-party-av-apps.html) page to serverless docs and a disambiguation note to the [Trusted applications](https://www.elastic.co/guide/en/security/master/trusted-apps-ov.html) page.
Previews:
* ESS: 
* [Allowlist Elastic Endpoint in third-party antivirus apps](https://security-docs_bk_5639.docs-preview.app.elstc.co/guide/en/security/master/allowlist-endpoint-3rd-party-av-apps.html)
* [Trusted applications](https://security-docs_bk_5639.docs-preview.app.elstc.co/guide/en/security/master/trusted-apps-ov.html)
* …
=> Adds Allowlist Elastic Endpoint in third-party antivirus apps page to serverless docs

docs/whats-new.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5508.
Adds a link to the Elastic AI Assistant API page in the release highlights now that https://github.com/elastic/security-docs/pull/5620 is merged.
Preview: [What’s new in 8.15](https://security-docs_bk_5690.docs-preview.app.elstc.co/guide/en/security/master/whats-new.html)
=> Adds AI Assistant APIs link to release highlights

docs/management/api/kill-process-api.asciidoc
- Updates the `kill-process` response action API to include `parameters.process_name` for use only with SentinelOne `agent_type`
=> [Response Actions][kill-process] Update API docs for `kill-process` to include `process_name` parameter for SentinelOne

docs/release-notes/8.15.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5713
Preview: https://security-docs_bk_5714.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.15.0.html#known-issue-8.15.0
=> [Known Issue] In bulk action menu we show manual rule run, but it's not available 

docs/es-overview.asciidoc, docs/serverless/rules/rules-ui-create.mdx, docs/serverless/security-overview.mdx, docs/serverless/serverless-security.docnav.json
Resolves https://github.com/elastic/security-docs/issues/5716, by updating the serverless docs with the changes started in ESS in https://github.com/elastic/security-docs/pull/4528. The serverless overview page now matches the [ESS overview page](https://www.elastic.co/guide/en/security/master/es-overview.html).
Click [the link below](https://github.com/elastic/security-docs/pull/5738#issuecomment-2307242302), then navigate to the **Elastic Security overview** page in the serverless docs (not the landing page).
These two bullets were omitted from the "Learn more" section, because the target pages don't exist in serverless docs:
- [Get started](https://www.elastic.co/guide/en/security/8.15/getting-started.html): Learn about system requirements, workspaces, configuration, and data …
=> Serverless changes to rework main overview landing page

docs/release-notes/8.14.asciidoc, docs/release-notes/8.15.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5765 by documenting the known issue for all releases between 8.14-8.15. 
Previews:
- [8.14.0-8.14.3 release notes](https://security-docs_bk_5786.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.14.0.html) - Adds the known issue to each version
- [8.15.0-8.15.1 release notes](https://security-docs_bk_5786.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.15.0.html) - Adds the known issue to 8.15 and updates the fixed bug description in 8.15.1 to show that the bug was discovered in 8.14.0.
=> [Known Issue] Doc Elastic Defend bug that stopped security events from populating the user.name field

docs/serverless/cloud-native-security/session-view.mdx, docs/serverless/investigate/investigate-events.mdx, docs/serverless/investigate/timeline-templates-ui.mdx, docs/serverless/investigate/timelines-ui.mdx, docs/serverless/osquery/use-osquery.mdx, docs/serverless/serverless-security.docnav.json
Fixes https://github.com/elastic/security-docs/issues/5761 by applying the changes in https://github.com/elastic/security-docs/pull/5736 to the Serverless TOC.
Preview: [Investigation tools](https://elastic-dot-co-docs-production-dge6mz0b3-elastic-dev.vercel.app/current/serverless/security/investigate-events)
=> [Docs IA][Serverless] Create Investigation Tools section

docs/detections/rules-ui-monitor.asciidoc, docs/serverless/rules/alerts-ui-monitor.mdx
Follow-up of https://github.com/elastic/security-docs/pull/5774 to apply same update to `main` and serverless docs.
=> Update ML jobs list on rule monitoring page

docs/management/admin/endpoint-command-ref.asciidoc, docs/management/manage-intro.asciidoc, docs/serverless/edr-manage/endpoint-command-ref.mdx, docs/serverless/serverless-security.docnav.json
Resolves https://github.com/elastic/security-docs/issues/5097 by adding a new page that documents the commands for managing and troubleshooting Elastic Endpoint.
* ESS: [Elastic Endpoint command reference](https://security-docs_bk_5778.docs-preview.app.elstc.co/guide/en/security/master/endpoint-command-ref.html)
* Serverless: Open the link in [this comment](https://github.com/elastic/security-docs/pull/5778#issuecomment-2331314083) and navigate to Security -> View serverless docs -> Manage Elastic Defend -> Elastic Endpoint command reference
=> Adds Elastic Endpoint command reference

docs/cloud-native-security/cspm-get-started-aws.asciidoc, docs/cloud-native-security/cspm-get-started-gcp.asciidoc, docs/serverless/cloud-native-security/cspm-get-started-gcp.mdx, docs/serverless/cloud-native-security/cspm-get-started.mdx
Fixes #5794 - the British English form of "Enrol" (instead of "Enroll") was used in Get started with CSPM docs
=> Fixes "Enrol"/"Enroll" typo

docs/AI-for-security/ai-security-assistant.asciidoc, docs/AI-for-security/connect-to-azure-openai.asciidoc, docs/serverless/AI-for-security/ai-assistant.mdx, docs/serverless/AI-for-security/connect-to-azure-openai.mdx
Fixes #5764 by updating the language that's used to refer to which models are supported for different LLM use-cases.
Previews:
=> Updates refs to LLMs

docs/serverless/AI-for-security/llm-performance-matrix.mdx, docs/serverless/serverless-security.docnav.json
Fixes #5818 by adding an IA change to serverless that is already present in ESS docs - moves the LLM Performance matrix to a different subsection. Also opportunistically fixes a minor formatting issue on the LLM Performance matrix page.
Preview:[ LLM performance matrix](https://elastic-dot-co-docs-production-p3mevbzfo-elastic-dev.vercel.app/current/serverless/security/llm-performance-matrix)
=> LLM performance matrix Serverless IA update

docs/getting-started/index.asciidoc
Fixes #5832 by updating the get started page and adding tutorial links. Removed the old sidebar (and outdated reference to a video). 
Preview: [Get started](https://security-docs_bk_5854.docs-preview.app.elstc.co/guide/en/security/master/getting-started.html)
=> Updates ESS get started page with tutorial links

docs/dashboards/kubernetes-dashboard.asciidoc, docs/serverless/dashboards/kubernetes-dashboard-dash.mdx
Fixes #5880 by updating the supporting matrix on the K8s dashboard page (ESS and serverless)
Preview:[ K8s dashboard](https://elastic-dot-co-docs-production-bicwo4vmm-elastic-dev.vercel.app/current/serverless/security/kubernetes-dashboard-dash)
=> [bug] Fixes support matrix bug in k8s dashboard doc

docs/detections/rules-ui-create.asciidoc, docs/serverless/rules/rules-ui-create.mdx
Fixes https://github.com/elastic/security-docs/issues/5844 by adding a new section that explains how to use the new **Show Elasticsearch requests, ran during rule executions** option in the rule preview.
Previews:
- ESS: https://security-docs_bk_5871.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#view-rule-es-queries
- Serverless: https://elastic-dot-co-docs-production-7pe5v3ygb-elastic-dev.vercel.app/current/serverless/security/rules-create#view-your-rules-es-queries-optional
=> [Serverless][8.16] Logs request during preview rule execution

docs/detections/rules-ui-manage.asciidoc
Fixes [list formatting](https://www.elastic.co/guide/en/security/master/rules-ui-management.html#manually-run-rules) issue in the note at the end of the ESS manual run docs: 
[Preview](https://security-docs_bk_5942.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-management.html#manually-run-rules)
=> Fixes list formatting for note in manual run docs

docs/advanced-entity-analytics/ers-req.asciidoc
Resolves https://github.com/elastic/security-docs/issues/5913 by removing the known limitation about risk scoring availability in multiple spaces.
No changes needed to serverless docs, since spaces weren't available in serverless when those docs were written, so that limitation was not documented.
Preview: [Entity risk scoring requirements](https://security-docs_bk_5931.docs-preview.app.elstc.co/guide/en/security/master/ers-requirements.html)
=> Entity risk scoring available in multiple Kibana spaces

docs/advanced-entity-analytics/asset-criticality.asciidoc, docs/serverless/advanced-entity-analytics/asset-criticality.mdx
Resolves https://github.com/elastic/security-docs/issues/5912 by updating the information about risk scoring recalculation when using the file upload feature. Users can now manually trigger an immediate recalculation of risk scores after uploading asset criticality using file upload.
ESS: [Asset criticality](https://security-docs_bk_5924.docs-preview.app.elstc.co/guide/en/security/master/asset-criticality.html)
Serverless: Open the link in [this comment](https://github.com/elastic/security-docs/pull/5924#issuecomment-2414311992) and navigate to Security -> View serverless docs -> Advanced Entity Analytics -> Entity risk scoring -> Asset criticality
=> Risk scoring recalculation after file upload

docs/advanced-entity-analytics/asset-criticality.asciidoc, docs/serverless/advanced-entity-analytics/asset-criticality.mdx
Resolves https://github.com/elastic/security-docs/issues/5976 by updating the name of the Asset criticality page to Entity Store. 
ESS: [Asset criticality | Bulk assign asset criticality](https://security-docs_bk_5990.docs-preview.app.elstc.co/guide/en/security/master/asset-criticality.html#bulk-assign-asset-criticality)
Serverless: Open the link in [this comment](https://github.com/elastic/security-docs/pull/5990#issuecomment-2435574319), then navigate to Security -> View serverless docs -> Advanced Entity Analytics -> Entity risk scoring -> Asset criticality.
=> Asset criticality navigation change

docs/advanced-entity-analytics/api/asset-criticality-api-overview.asciidoc, docs/advanced-entity-analytics/asset-criticality.asciidoc, docs/advanced-entity-analytics/entity-risk-scoring.asciidoc, docs/advanced-entity-analytics/ers-req.asciidoc, docs/getting-started/advanced-setting.asciidoc, docs/getting-started/users-page.asciidoc, docs/management/hosts/hosts-overview.asciidoc, docs/serverless/advanced-entity-analytics/asset-criticality.mdx, docs/serverless/advanced-entity-analytics/entity-risk-scoring.mdx, docs/serverless/advanced-entity-analytics/ers-req.mdx, docs/serverless/explore/hosts-overview.mdx, docs/serverless/explore/users-page.mdx, docs/serverless/settings/advanced-settings.mdx
Resolves https://github.com/elastic/security-docs/issues/5975. Removes all references to the asset criticality advanced setting. The setting has been removed and asset criticality is now available by default.
ESS:
- [Asset criticality API](https://security-docs_bk_5991.docs-preview.app.elstc.co/guide/en/security/master/asset-criticality-api-overview.html)
- [Configure advanced settings](https://security-docs_bk_5991.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html)
- [Hosts page](https://security-docs_bk_5991.docs-preview.app.elstc.co/guide/en/security/master/hosts-overview.html)
- [Users page](https://security-docs_bk_5991.docs-preview.app.elstc.co/guide/en/security/master/users-page.html)
- [Entity risk scoring requirements | Asset …
=> Asset criticality advanced setting removed

docs/serverless/advanced-entity-analytics/turn-on-risk-engine.asciidoc, docs/serverless/investigate/cases-settings.asciidoc
As Liam reported in [this thread](https://elastic.slack.com/archives/C05PP2LEC1X/p1730884542702359), some attributes were incorrect post migration of serverless docs from mdx to asciidoc. This PR updates the occurrences of the `{security}` attribute to `{elastic-sec}`.
Previews:
* [Turn on risk scoring](https://security-docs_bk_6069.docs-preview.app.elstc.co/guide/en/serverless/current/security-turn-on-risk-engine.html)
* [Configure case settings](https://security-docs_bk_6069.docs-preview.app.elstc.co/guide/en/serverless/current/security-cases-settings.html)
Related PR that fixes the same issue in the `docs-content` repo: https://github.com/elastic/docs-content/pull/174
=> Fixes incorrect attribute

docs/detections/prebuilt-rules-management.asciidoc
Follow up fix for image reference bug introduced in https://github.com/elastic/security-docs/pull/6051.
The bug doesn't manifest in the `main` branch, but will become a problem for future backport branches created off of `main`. I noticed this in the backport PRs https://github.com/elastic/security-docs/pull/6051 and https://github.com/elastic/security-docs/pull/6093 and fixed the errors in those PRs, but then realized that the problem might re-emerge again any time another backport branch gets created.
The problem is that the `images/icons` subdirectory won't exist for those ESS-only backport branches, because the location only exists in serverless docs.
=> Fix image reference bug

docs/release-notes/8.15.asciidoc
Fixes the ref so it links to the correct Kibana issue.
[Preview](https://security-docs_bk_6126.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.15.0.html#bug-fixes-8.15.4)
=> Fixes incorrect ref in the 8.15.4 release notes 

docs/management/admin/deploy-with-mdm.asciidoc, docs/serverless/edr-install-config/deploy-with-mdm.asciidoc
Resolves https://github.com/elastic/security-docs/issues/6057.
The same fix has been applied to ESS docs.
Serverless: [Deploy on macOS with MDM | Enable notifications](https://security-docs_bk_6163.docs-preview.app.elstc.co/guide/en/serverless/main/security-deploy-with-mdm.html#security-deploy-with-mdm-enable-notifications)
ESS: [Deploy on macOS with MDM | Enable notifications](https://security-docs_bk_6163.docs-preview.app.elstc.co/guide/en/security/master/deploy-with-mdm.html#notifications-jamf)
=> [Serverless bug bash] Fixes style issue on Deploy with MDM page

docs/release-notes/8.16.asciidoc
Fixes https://github.com/elastic/security-docs-internal/issues/53
Preview: [8.16 known issues](https://security-docs_bk_6169.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.16.0.html#release-notes-8.16.0)
=> [Known Issue] Error on Alert Page when upgrading to 8.16.0

docs/serverless/investigate/timelines-ui.asciidoc, docs/serverless/security-ui.asciidoc
👋 We're de-duplicating content in the Elasticsearch serverless docs, and this is an example of a feature that will have its single-source-of-truth in the Kibana docs. I'll need this change merged, in order to get a green build on my PR in the `docs-content` repo.
=> Update serverless Discover URL

docs/cloud-native-security/cspm-get-started-aws.asciidoc, docs/serverless/cloud-native-security/cspm-get-started.asciidoc
Fixes #5636 
Adds OrganizationalUnitIDs field to the agentless CSPM AWS guides, edits the field's description in agent-based method.
Preview: CSPM for AWS ([ESS](https://security-docs_bk_6155.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started.html)), ([Serverless](https://security-docs_bk_6155.docs-preview.app.elstc.co/guide/en/serverless/current/security-cspm-get-started.html))
=> [ESS & Serverless] Adds OrganizationUnitIDs description to agentless section of AWS CSPM guide

docs/AI-for-security/knowledge-base.asciidoc
Fixes #6157 — Adds a new section to the ESS Knowledge Base doc that shows how to add a threat intelligence feed to Knowledge Base using an Elasticsearch web crawler.
Preview: [Knowledge Base](https://security-docs_bk_6176.docs-preview.app.elstc.co/guide/en/security/master/ai-assistant-knowledge-base.html) (new section is at the bottom)
=> Adds web crawler example to Knowledge Base doc

docs/release-notes/8.16.asciidoc
Addresses [this comment](https://github.com/elastic/security-docs/pull/6178#discussion_r1851598802) and removes 199791 from the 8.16.1 release notes.
Preview:https://security-docs_bk_6207.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.16.0.html
=> Removes 199791 from the 8.16.1 release notes

.mergify.yml
Updates `8.x` mergify backport to change `8.17` target from `8.x` to `8.17`.
=> [8.x] Update .mergify.yml

docs/release-notes.asciidoc
Updates the release notes landing page for [`8.17`](https://github.com/elastic/security-docs/blob/8.17/docs/release-notes.asciidoc?plain=1) and [`8.x`](https://github.com/elastic/security-docs/blob/8.x/docs/release-notes.asciidoc?plain=1) so they're no longer missing the reference to the 8.16.1 release notes. 
Previews: [8.x RN landing page](https://security-docs_bk_6225.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes.html)
=> Adds missing ref to the 8.16.1 release notes 

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x upgrade guide to the 8.0 branch.
Previews:
* [Upgrade Elastic Security to 8.0.1](https://security-docs_bk_6235.docs-preview.app.elstc.co/guide/en/security/8.0/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6235.docs-preview.app.elstc.co/guide/en/security/8.0/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.0

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.1 branch.
Previews:
* [Upgrade Elastic Security to 8.1.3](https://security-docs_bk_6234.docs-preview.app.elstc.co/guide/en/security/8.1/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6234.docs-preview.app.elstc.co/guide/en/security/8.1/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.1

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.2 branch.
Previews:
* [Upgrade Elastic Security to 8.2.3](https://security-docs_bk_6233.docs-preview.app.elstc.co/guide/en/security/8.2/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6233.docs-preview.app.elstc.co/guide/en/security/8.2/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.2

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.3 branch.
Previews:
* [Upgrade Elastic Security to 8.3.3](https://security-docs_bk_6232.docs-preview.app.elstc.co/guide/en/security/8.3/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6232.docs-preview.app.elstc.co/guide/en/security/8.3/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.3

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.4 branch.
Previews:
* [Upgrade Elastic Security to 8.4.3](https://security-docs_bk_6231.docs-preview.app.elstc.co/guide/en/security/8.4/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6231.docs-preview.app.elstc.co/guide/en/security/8.4/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.4

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.5 branch.
Previews:
* [Upgrade Elastic Security to 8.5.3](https://security-docs_bk_6206.docs-preview.app.elstc.co/guide/en/security/8.5/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6206.docs-preview.app.elstc.co/guide/en/security/8.5/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.5

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.6 branch.
Previews:
* [Upgrade Elastic Security to 8.6.2](https://security-docs_bk_6205.docs-preview.app.elstc.co/guide/en/security/8.6/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6205.docs-preview.app.elstc.co/guide/en/security/8.6/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.6

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.7 branch.
Previews:
* [Upgrade Elastic Security to 8.7.1](https://security-docs_bk_6204.docs-preview.app.elstc.co/guide/en/security/8.7/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6204.docs-preview.app.elstc.co/guide/en/security/8.7/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.7

docs/upgrade/upgrade-7.17-8.x.asciidoc, docs/upgrade/upgrade-security.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/5302 by backporting the updated 7.17–8.x and 8.x–8.x upgrade guides to the 8.8 branch.
Previews:
* [Upgrade Elastic Security to 8.8.2](https://security-docs_bk_6203.docs-preview.app.elstc.co/guide/en/security/8.8/upgrade-intro.html)
* [Upgrade from 7.17 to an 8.x version](https://security-docs_bk_6203.docs-preview.app.elstc.co/guide/en/security/8.8/upgrade-7.17-8x.html)
=> Backport updated upgrade guides to 8.8

docs/serverless/billing.asciidoc
Resolves https://github.com/elastic/security-docs-internal/issues/52. 
Preview [here](https://security-docs_bk_6247.docs-preview.app.elstc.co/guide/en/serverless/current/security-billing.html).
=> [Serverless] Updates billing docs 

docs/release-notes.asciidoc, docs/release-notes/9.0.asciidoc
Fixes https://github.com/elastic/security-docs/issues/6039 by creating placeholder sections for the 9.0 breaking changes and deprecations. This PR also:
- Re-adds the release notes folder and creates a new page for the 9.0 release notes
- Creates placeholders for the other 9.0 release notes
- Adds a link to the 9.0 release notes from the release notes landing page  
Previews:
- [Release notes index page](https://security-docs_bk_6274.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [9.0 release notes](https://security-docs_bk_6274.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-9.0.0.html)
=> [ESS][9.0] Create breaking changes and deprecations placeholder for 9.0

docs/serverless/investigate/case-permissions.asciidoc, docs/serverless/investigate/cases-open-manage.asciidoc
Fixes https://github.com/elastic/security-docs/issues/6015 by changing **Project settings → Management** to **Project Settings → Stack Management**. 
Previews:
- [Create and manage cases](https://security-docs_bk_6283.docs-preview.app.elstc.co/guide/en/serverless/current/security-cases-open-manage.html)
- [Cases requirements](https://security-docs_bk_6283.docs-preview.app.elstc.co/guide/en/serverless/current/security-cases-requirements.html)
=> [Serverless]: Security - Cases nav steps are slightly incorrect 

docs/release-notes.asciidoc, docs/release-notes/8.17.asciidoc
This will backport the following commits from `8.x` to `8.17`:
- [8.17.0 Release notes  (#6224)](https://github.com/elastic/security-docs/pull/6224)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [8.17] 8.17.0 Release notes  (#6224)

docs/release-notes/8.17.asciidoc, docs/whats-new.asciidoc
Removes the line about alert suppression on EQL sequence alerts from 8.17 release notes and highlights, per [this comment](https://github.com/elastic/security-docs/pull/6224/files#r1883951350).
Previews:
* [What’s new in 8.17](https://security-docs_bk_6313.docs-preview.app.elstc.co/guide/en/security/8.x/whats-new.html)
* [8.17](https://security-docs_bk_6313.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.17.0.html)
=> Removes alert suppression line from RN and highlights

docs/AI-for-security/llm-performance-matrix.asciidoc, docs/serverless/AI-for-security/llm-performance-matrix.asciidoc
Fixes #6285 by adding a legend to the LLM Performance Matrix that specifies which of the possible ratings are superior to which.
Preview:[ LLM Performance matrix](https://security-docs_bk_6297.docs-preview.app.elstc.co/guide/en/security/master/llm-performance-matrix.html)
=> Adds legend to LLM perf matrix

.mergify.yml
This PR makes two changes to our Mergify config file:
- Moves the entry for 8.0 above 7.17 so it's in the correct order
- Updates the conditions for the 8.0 branch so that the only criteria that need to be met are: PR is merged and the `v8.0.0` version label exists
=> Updates conditions for the 8.0 branch

docs/getting-started/configure-integration-policy.asciidoc, docs/getting-started/endpoint-data-volume.asciidoc, docs/management/endpoint-protection-index.asciidoc
Backports https://github.com/elastic/security-docs/pull/5881 to 8.15.
Replaces https://github.com/elastic/security-docs/pull/6413, which has been closed due to [cla-checker-service failure](https://github.com/elastic/security-docs/pull/6413#issuecomment-2580605516).
=> [8.15] Endpoint data volume reduction mechanisms [ESS] (backport #5881)

docs/release-notes/8.15.asciidoc, docs/release-notes/8.16.asciidoc
Fixes https://github.com/elastic/security-docs/issues/6428.
Previews:
- [8.16.0 release notes](https://security-docs_bk_6429.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.16.0.html#bug-fixes-8.16.0) - See list item no. 14
- [8.15.4 release notes](https://security-docs_bk_6429.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.15.0.html#bug-fixes-8.15.4) - See last list item
=> [Request][8.15.4 & 8.16.0] Add RN summary about Defend bug fix 

docs/release-notes/8.16.asciidoc
Updates the 8.16.2 and 8.16.3 release notes to include the known issues about the manual rule run feature. 
Previews: [8.16.x release notes](https://security-docs_bk_6440.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.16.0.html)
=> Re-adds known issues to 8.16.2 and 8.16.3 release notes

docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
As part of the PR - https://github.com/elastic/security-docs/pull/6447 there was some indetation issues like below 
This PR fixes that issue
=> Fix doc indentation 8.14

docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
As part of the PR https://github.com/elastic/security-docs/pull/6451 there was some indetation issues like below 
This PR fixes that issue
=> Fix doc indentation 8.15

docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
As part of the PR https://github.com/elastic/security-docs/pull/6452 there was some indentation issues like below 
This PR fixes that issue
=> Fix doc indentation 8.16

docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
As part of the PR https://github.com/elastic/security-docs/pull/6456 there was some indentation issues like below
This PR fixes that issue
=> Fix doc indentation 8.17

docs/release-notes/8.17.asciidoc
Adds 202063 to the 8.17.1 release notes and updates the known issue description in 8.17.0 release notes. Related issue: https://github.com/elastic/security-docs/issues/6275
Preview:
- [8.17.1 bug fixes](https://security-docs_bk_6475.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.17.0.html#bug-fixes-8.17.1) - See eighth list item
- [8.17.0 known issues](https://security-docs_bk_6475.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.17.0.html#known-issue-8.17.0) - Updated the workaround for the first known issue so users know they can either upgrade to 8.7.1 or use the provided workarounds.
=> Adds 202063 to the 8.17.1 release notes

docs/dashboards/dashboards-overview.asciidoc
Context: https://discuss.elastic.co/t/unable-to-add-tag-security-solution-in-elastic-security-serverless/373206
The default "Security Solution" tag is now a `managed` tag, so users won't be able to assign it to a dashboard.
Suggesting to remove the tips in the document to avoid confusion.
=> Update custom dashboard docs

docs/release-notes/8.17.asciidoc
Fixes #6462 by adding a known issue to the 8.17.0 release notes. This branch was opened based on 8.17, and this PR proposes to merge it directly to 8.17, and we can backport it to 8.18, if I'm understanding our current setup correctly.
Preview: [8.17.0 RNs (minor addition)](https://security-docs_bk_6481.docs-preview.app.elstc.co/guide/en/security/8.17/release-notes-header-8.17.0.html)
=> 8.17.0 known issue — D4C broken

docs/management/admin/response-actions-config.asciidoc, docs/management/admin/third-party-actions.asciidoc, docs/serverless/endpoint-response-actions/response-actions-config.asciidoc, docs/serverless/endpoint-response-actions/third-party-actions.asciidoc
Resolves https://github.com/elastic/security-docs/issues/6397.
ESS:
* [Third-party response actions](https://security-docs_bk_6471.docs-preview.app.elstc.co/guide/en/security/master/third-party-actions.html)
* [Configure third-party response actions](https://security-docs_bk_6471.docs-preview.app.elstc.co/guide/en/security/master/response-actions-config.html)
Serverless:
* [Third-party response actions](https://security-docs_bk_6471.docs-preview.app.elstc.co/guide/en/serverless/main/security-third-party-actions.html)
* [Configure third-party response actions](https://security-docs_bk_6471.docs-preview.app.elstc.co/guide/en/serverless/main/security-response-actions-config.html)
=> [Jan 28] GA for third-party response actions

docs/management/admin/response-actions-config.asciidoc
Resolves https://github.com/elastic/security-docs/issues/6398.
Preview: [Configure third-party response actions](https://security-docs_bk_6434.docs-preview.app.elstc.co/guide/en/security/master/response-actions-config.html): Updated second bullet point in the prerequisites callout.
=> [Jan 28] Updates RBAC requirements for 3rd-party response actions

docs/getting-started/automatic-import.asciidoc, docs/serverless/ingest/auto-import.asciidoc
Fixes #6383. Automatic import can new help create integrations to consume data from an addition source, CEL, which has some quirks. This PR notes those quirks in the automatic import documentation.
Preview: Automatic Import ([serverless](https://security-docs_bk_6492.docs-preview.app.elstc.co/guide/en/serverless/current/security-automatic-import.html)) ([ESS](https://security-docs_bk_6492.docs-preview.app.elstc.co/guide/en/security/master/automatic-import.html))
=> Automatic Import: CEL Input

.mergify.yml
Per typical protocol, adds `8.18` and points `8.x` backports to `8.19` branch.
=> [Main] Update .mergify.yml

docs/release-notes/8.17.asciidoc
Fixes https://github.com/elastic/docs-content/issues/360
Previews:
- [8.17.0 known issues](https://security-docs_bk_6512.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.17.0.html#known-issue-8.17.0)
- [8.17.1 known issues](https://security-docs_bk_6512.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.17.0.html#known-issue-8.17.1)
=> [Known Issue][8.17.0 & 8.17.1]: Elastic Security crashes in ECH on Kibana instances with 1 GB of RAM

docs/release-notes.asciidoc, docs/release-notes/7.17.asciidoc
Writes the 7.17.28 release notes 
Preview: [7.17.28 release notes](https://security-docs_bk_6540.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.28)
=> 7.17.28 release notes

docs/cloud-native-security/cspm-get-started-aws.asciidoc, docs/cloud-native-security/cspm-get-started-azure.asciidoc, docs/cloud-native-security/cspm-get-started-gcp.asciidoc, docs/getting-started/agentless-troubleshooting.asciidoc, docs/getting-started/index.asciidoc
Fixes #[500](https://github.com/elastic/docs-content/issues/500)
Updates the agentless intergation FAQ and the CSPM getting started guides for AWS, Azure, and GCP, to inform users that agentless integrations don't work in environments where traffic filtering is present.
Previews: [Agentless FAQ](https://security-docs_bk_6549.docs-preview.app.elstc.co/guide/en/security/current/agentless-integration-troubleshooting.html) (new FAQ item)
[Get started with CSPM for AWS](https://security-docs_bk_6549.docs-preview.app.elstc.co/guide/en/security/current/cspm-get-started.html#cspm-aws-agentless) (new note at the end of the agentless deployment section — changes to Azure and GCP guides are identical)
=> Doc incompatibility between agentless integration and traffic filtering

docs/reference/endpoint-command-reference.md
This PR fixes some links in the Endpoint command reference to point to the appropriate section of the Solutions content (https://docs-v3-preview.elastic.dev/elastic/docs-content/tree/main/solutions/security/manage-elastic-defend).
The duplicated pages that exist in the Reference section will be removed in a separate PR.
=> Fix links to Elastic Defend content

docs/release-notes/8.17.asciidoc
Adds 212130 to the 8.17.3 release notes. This PR was initially skipped because it has the `release_notes:skip` label.
Preview: [8.17.3 release notes](https://security-docs_bk_6570.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.17.0.html#release-notes-8.17.3) - Added 212130 to the bug fixes section
=> Adds 212130 to the 8.17.3 release notes

docs/release-notes/8.16.asciidoc
Adds 212130 to the 8.16.5 release notes. This PR was initially skipped because it has the `release_notes:skip` label.
Preview: [8.16.5 release notes](https://security-docs_bk_6571.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.16.0.html#release-notes-8.16.5) - Added 212130 to the bug fixes section
=> Adds 212130 to the 8.16.5 release notes

docs/serverless/index.asciidoc
🧀  Pairs with https://github.com/elastic/docs-content/pull/665
Use `current` attributes in serverless docs to avoid 404s to `master` pages.
=> [serverless] Use `current` attributes in serverless docs

docs/cloud-native-security/cspm-get-started-aws.asciidoc, docs/cloud-native-security/cspm-get-started-azure.asciidoc, docs/cloud-native-security/cspm-get-started-gcp.asciidoc, docs/getting-started/agentless-integrations.asciidoc
Fixes #[277](https://github.com/elastic/docs-content/issues/277) by removing all references to agentless CSPM being in beta.
=> CSPM agentless goes GA

docs/AI-for-security/ai-security-assistant.asciidoc
Fixes docs-content/267, minor edit to remove references to an AI Assistant tab in Timeline.
=> Removes outdated timeline reference from AI Assistant page

docs/getting-started/index.asciidoc, docs/getting-started/siem-migration.asciidoc
This PR creates a blank page in 8.x and 8.18 for the SIEM migrations feature, so that in-app links can point to it. This will enable Sergi to merge some PRs that are currently failing because the doc links don't exist yet. I will add content to these pages before the 8.18 release.
=> Adds placeholder pages for in-app linking purposes

docs/advanced-entity-analytics/entity-store.asciidoc, docs/dashboards/entity-dashboard.asciidoc
Resolves https://github.com/elastic/docs-content/issues/268 by removing the tech preview label for entity store feature.
Previews:
- [Entity store](https://security-docs_bk_6622.docs-preview.app.elstc.co/guide/en/security/8.x/entity-store.html)
- [Entity Analytics dashboard | Entities](https://security-docs_bk_6622.docs-preview.app.elstc.co/guide/en/security/8.x/detection-entity-dashboard.htmlentity-entities)
=> Entity store GA in 8.18

docs/cases/cases-req.asciidoc
Partially addresses https://github.com/elastic/docs-content/issues/333. Makes minor changes to future-proof docs for giving full access to manage cases and settings.
Preview: [Cases requirements](https://security-docs_bk_6641.docs-preview.app.elstc.co/guide/en/security/8.x/case-permissions.html)
- 9.0 and Serverless docs (all): https://github.com/elastic/docs-content/pull/831
- Kibana docs: https://github.com/elastic/kibana/pull/215162
- Observability docs: https://github.com/elastic/observability-docs/pull/4850
=> [8.18] New sub-feature priv for case assignees

docs/detections/rules-cross-cluster-search.asciidoc
Partially addresses https://github.com/elastic/docs-content/issues/346 by adding a note describing the reqs for using CCS with ES|QL rules.
Preview: [Cross-cluster search and detection rules](https://security-docs_bk_6640.docs-preview.app.elstc.co/guide/en/security/8.x/rules-cross-cluster-search.html)
Corresponding 9.0 and Serverless docs: https://github.com/elastic/docs-content/pull/828
=> [8.18] CCS and ES|QL rule reqs

docs/AI-for-security/llm-performance-matrix.asciidoc
Fixes docs-content/#738. Updates the LLM performance matrix to reflect new testing.
Preview: [LLM Performance matrix](https://security-docs_bk_6648.docs-preview.app.elstc.co/guide/en/security/8.x/llm-performance-matrix.html)
=> updates LLM performance matrix

docs/release-notes/8.17.asciidoc
What the title says.
Preview: [8.17.4 release notes](https://security-docs_bk_6667.docs-preview.app.elstc.co/guide/en/security/8.x/release-notes-header-8.17.0.html)
=> Removes 214495 from the 8.17.4 release notes
