- .gitignore
- docs/data-visibility/data-visibility.asciidoc
Add a tentative directory structure so we can start adding content.
> [DOCS]: Add repo directory structure

- docs/index.asciidoc
- docs/siem/index.asciidoc
- [DOCS]Includes SIEM index file (#20)
> [7.x] [DOCS]Includes SIEM index file (#20)

- docs/siem/installation.asciidoc
> [7.x] Change links to refactored Beats getting started docs

- docs/siem/index.asciidoc
- docs/siem/reference/timeline-schema.asciidoc
- docs/siem/timeline/api/timeline-api-create.asciidoc
- docs/siem/timeline/api/timeline-api-import.asciidoc
- docs/siem/timeline/api/timeline-api-index.asciidoc
- docs/siem/timeline/api/timeline-api-overview.asciidoc
- [Docs]Adds timeline schema and API (#50)
> [7.x] [Docs]Adds timeline schema and API (#50)

- docs/siem/detections/machine-learning/machine-learning.asciidoc
Backports https://github.com/elastic/security-docs/pull/48
> [7.x][DOCS] Updates location of machine learning source file

- docs/siem/detections/api/rules-api-create.asciidoc
- docs/siem/detections/api/rules-api-update.asciidoc
- docs/siem/detections/api/signals-api-overview.asciidoc
- [Docs]Updates detections API (#70)
> [7.x] [Docs]Updates detections API (#70)

- docs/siem/detections/api/rules-api-create.asciidoc
- docs/siem/detections/api/rules-api-update.asciidoc
- docs/siem/detections/api/signals-api-overview.asciidoc
- [Docs]Updates detections API (#70)
> [7.9] [Docs]Updates detections API (#70)

- docs/management/admin/admin-pg-ov.asciidoc
Just fixes the TOC in the HTML.
FYI - @jmikell821 @DonNateR
> [Docs]Makes admin overview a first-level section

- docs/siem-apis.asciidoc
Fixes API TOC introduced here: https://github.com/elastic/security-docs/pull/90/commits/65773ab49c633aec4a7f5db8011a58a253e1d0d3#diff-b6998990f39b4f00fe0189e6b6e36d42
> [Docs]Fixes API TOC 7.x

- docs/siem-apis.asciidoc
Fixes API TOC issues introduced here: https://github.com/elastic/security-docs/pull/90/commits/65773ab49c633aec4a7f5db8011a58a253e1d0d3#diff-b6998990f39b4f00fe0189e6b6e36d42
> [Docs]Fixes API TOC 7.9

- docs/cases/cases-ui-integrations.asciidoc
- [Docs]Cases UI connector corrections (#115)
> [7.x] [Docs]Cases UI connector corrections (#115)

- docs/cases/cases-ui-integrations.asciidoc
- [Docs]Cases UI connector corrections (#115)
> [7.9] [Docs]Cases UI connector corrections (#115)

- docs/es-overview.asciidoc
- docs/whats-new.asciidoc
- [DOCS]: Fixes to what's new/Security overview (#132)
> [7.x] [DOCS]: Fixes to what's new/Security overview (#132)

- docs/es-overview.asciidoc
- docs/whats-new.asciidoc
- [DOCS]: Fixes to what's new/Security overview (#132)
> [7.9] [DOCS]: Fixes to what's new/Security overview (#132)

- docs/getting-started/security-ui.asciidoc
Adding in <xref> links; fixing some formatting.
> [DOCS] UI updates

- docs/getting-started/security-ui.asciidoc
> [7.9] [DOCS] UI updates (#139)

- docs/getting-started/security-ui.asciidoc
> [7.x] [DOCS] UI updates (#139)

- docs/es-overview.asciidoc
- docs/events/index.asciidoc
- docs/getting-started/detections-req.asciidoc
- docs/getting-started/index.asciidoc
- docs/getting-started/ingest-data.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- [Docs]General corrections (#147)
> [7.x] [Docs]General corrections (#147)

- docs/es-overview.asciidoc
- docs/events/index.asciidoc
- docs/getting-started/detections-req.asciidoc
- docs/getting-started/index.asciidoc
- docs/getting-started/ingest-data.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- [Docs]General corrections (#147)
> [7.9] [Docs]General corrections (#147)

- docs/detections/alerts-ui-manage.asciidoc
- docs/detections/api/exceptions/api-create-exception-item.asciidoc
- docs/detections/detection-engine-intro.asciidoc
- docs/index.asciidoc
- docs/release-notes.asciidoc
Adds RNs to the Security docs.
[Preview](https://security-docs_144.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
> [Docs]7.9 Release notes and minor fixes

- docs/detections/alerts-ui-manage.asciidoc
- docs/detections/api/exceptions/api-create-exception-item.asciidoc
- docs/detections/detection-engine-intro.asciidoc
- docs/index.asciidoc
- docs/release-notes.asciidoc
- [Docs]7.9 Release notes and minor fixes (#144)
> [7.9] [Docs]7.9 Release notes and minor fixes (#144)

- docs/detections/alerts-ui-manage.asciidoc
- docs/detections/api/exceptions/api-create-exception-item.asciidoc
- docs/detections/detection-engine-intro.asciidoc
- docs/index.asciidoc
- docs/release-notes.asciidoc
- [Docs]7.9 Release notes and minor fixes (#144)
> [7.x] [Docs]7.9 Release notes and minor fixes (#144)

- docs/whats-new.asciidoc
- [DOCS] What's changed in 7.9 (#123)
> [7.x] [DOCS] What's changed in 7.9 (#123)

- docs/whats-new.asciidoc
- [DOCS] What's changed in 7.9 (#123)
> [7.9] [DOCS] What's changed in 7.9 (#123)

- docs/getting-started/ingest-data.asciidoc
- Add clarification on Elastic Endpoint installation (#154)
> [7.x] Add clarification on Elastic Endpoint installation (#154)

- docs/getting-started/ingest-data.asciidoc
- Add clarification on Elastic Endpoint installation (#154)
> [7.9] Add clarification on Elastic Endpoint installation (#154)

- docs/getting-started/ingest-data.asciidoc
- docs/getting-started/install-endpoint.asciidoc
Improves the endpoint agent's description in the ingest data section.
> [Docs]Updates endpoint ingest description

- docs/getting-started/ingest-data.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- [Docs]Updates endpoint ingest description (#155)
> [7.x] [Docs]Updates endpoint ingest description (#155)

- docs/getting-started/ingest-data.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- [Docs]Updates endpoint ingest description (#155)
> [7.9] [Docs]Updates endpoint ingest description (#155)

- docs/release-notes.asciidoc
> [Docs]Adds Timeline known issue

- docs/release-notes.asciidoc
The issue is expected behavior and does not fit the requirements for a known issue.
> Remove issue 75192 from release notes

- docs/release-notes.asciidoc
- Remove issue 75192 from release notes (#167)
> [7.9] Remove issue 75192 from release notes (#167)

- docs/release-notes.asciidoc
- Remove issue 75192 from release notes (#167)
> [7.x] Remove issue 75192 from release notes (#167)

- docs/detections/detection-engine-intro.asciidoc
- [Docs]Updates link to detection requirements (#171)
> [7.x] [Docs]Updates link to detection requirements (#171)

- docs/es-overview.asciidoc
Added Endpoint Security to hosts data sources.
> [DOCS] Add Endpoint Security to Hosts Data

- docs/detections/rules-ui-create.asciidoc
- docs/es-overview.asciidoc
- docs/release-notes.asciidoc
- docs/siem/overview.asciidoc
- docs/whats-new.asciidoc
Adds a post upgrade requirement to the RNs, and clarifies the values sent in alert notifications.
[Post upgrade requirement preview](https://security-docs_170.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
[Alert placeholders note](https://security-docs_170.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#rule-action-variables)
> [Docs]Post upgrade requirement and alert notifications 

- docs/detections/rules-ui-create.asciidoc
- docs/es-overview.asciidoc
- docs/release-notes.asciidoc
- docs/siem/overview.asciidoc
- docs/whats-new.asciidoc
- [Docs]Post upgrade requirement and alert notifications  (#170)
> [7.x] [Docs]Post upgrade requirement and alert notifications  (#170)

- docs/detections/rules-ui-create.asciidoc
- docs/es-overview.asciidoc
- docs/release-notes.asciidoc
- docs/siem/overview.asciidoc
- docs/whats-new.asciidoc
- [Docs]Post upgrade requirement and alert notifications  (#170)
> [7.9] [Docs]Post upgrade requirement and alert notifications  (#170)

- docs/page_header.html
Adda banner to legacy SIEM docs.
> [Docs]Adds banner 7.9

- docs/getting-started/detections-req.asciidoc
Removes tooltip, as requirement is described in getting started.
> [Docs]Removes unnecessary tip

- docs/detections/prebuilt-rules/rule-details/anomalous-process-for-a-linux-population.asciidoc
- docs/detections/prebuilt-rules/rule-details/anomalous-process-for-a-windows-population.asciidoc
- docs/detections/prebuilt-rules/rule-details/anomalous-windows-process-creation.asciidoc
- docs/detections/prebuilt-rules/rule-details/dns-tunneling.asciidoc
- docs/detections/prebuilt-rules/rule-details/rare-aws-error-code.asciidoc
- docs/detections/prebuilt-rules/rule-details/spike-in-aws-error-messages.asciidoc
- docs/detections/prebuilt-rules/rule-details/suspicious-powershell-script.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-aws-command-for-a-user.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-city-for-an-aws-command.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-country-for-an-aws-command.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-dns-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-port-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-service.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-username.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-web-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-login-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-network-destination-domain-name.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-process-for-a-linux-host.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-process-for-a-windows-host.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-web-request.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-web-user-agent.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-network-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-path-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-remote-user.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-service.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-user-privilege-elevation-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-username.asciidoc
Now we have `current` security docs, updated the ref.
> [Docs]Updates ML prebuilt rules ref url

- docs/detections/prebuilt-rules/rule-details/anomalous-process-for-a-linux-population.asciidoc
- docs/detections/prebuilt-rules/rule-details/anomalous-process-for-a-windows-population.asciidoc
- docs/detections/prebuilt-rules/rule-details/anomalous-windows-process-creation.asciidoc
- docs/detections/prebuilt-rules/rule-details/dns-tunneling.asciidoc
- docs/detections/prebuilt-rules/rule-details/rare-aws-error-code.asciidoc
- docs/detections/prebuilt-rules/rule-details/spike-in-aws-error-messages.asciidoc
- docs/detections/prebuilt-rules/rule-details/suspicious-powershell-script.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-aws-command-for-a-user.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-city-for-an-aws-command.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-country-for-an-aws-command.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-dns-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-port-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-service.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-username.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-web-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-login-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-network-destination-domain-name.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-process-for-a-linux-host.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-process-for-a-windows-host.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-web-request.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-web-user-agent.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-network-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-path-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-remote-user.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-service.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-user-privilege-elevation-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-username.asciidoc
- updates ml prebuilt rules ref url (#202)
> [7.x] updates ml prebuilt rules ref url (#202)

- docs/detections/prebuilt-rules/rule-details/anomalous-process-for-a-linux-population.asciidoc
- docs/detections/prebuilt-rules/rule-details/anomalous-process-for-a-windows-population.asciidoc
- docs/detections/prebuilt-rules/rule-details/anomalous-windows-process-creation.asciidoc
- docs/detections/prebuilt-rules/rule-details/dns-tunneling.asciidoc
- docs/detections/prebuilt-rules/rule-details/rare-aws-error-code.asciidoc
- docs/detections/prebuilt-rules/rule-details/spike-in-aws-error-messages.asciidoc
- docs/detections/prebuilt-rules/rule-details/suspicious-powershell-script.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-aws-command-for-a-user.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-city-for-an-aws-command.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-country-for-an-aws-command.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-dns-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-port-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-network-service.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-username.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-linux-web-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-login-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-network-destination-domain-name.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-process-for-a-linux-host.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-process-for-a-windows-host.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-web-request.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-web-user-agent.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-network-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-path-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-remote-user.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-service.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-user-privilege-elevation-activity.asciidoc
- docs/detections/prebuilt-rules/rule-details/unusual-windows-username.asciidoc
- updates ml prebuilt rules ref url (#202)
> [7.9] updates ml prebuilt rules ref url (#202)

- docs/es-overview.asciidoc
- docs/getting-started/ingest-data.asciidoc
- docs/index.asciidoc
- Overview and Ingest page updates (#182)
> [7.x] Overview and Ingest page updates (#182)

- docs/es-overview.asciidoc
- docs/getting-started/ingest-data.asciidoc
- docs/index.asciidoc
- Overview and Ingest page updates (#182)
> [7.9] Overview and Ingest page updates (#182)

- docs/index.asciidoc
- docs/post-upgrade-req.asciidoc
- docs/release-notes.asciidoc
- docs/template-script.asciidoc
Adds reindexing the signals index as a post upgrade requirement.
[Preview](https://security-docs_217.docs-preview.app.elstc.co/guide/en/security/master/post-upgrade-req.html)
> [Docs]Post upgrade reindex requirement

- docs/index.asciidoc
- docs/post-upgrade-req.asciidoc
- docs/release-notes.asciidoc
- docs/template-script.asciidoc
- [Docs]Post upgrade reindex requirement (#217)
> [7.x] [Docs]Post upgrade reindex requirement (#217)

- docs/index.asciidoc
- docs/post-upgrade-req.asciidoc
- docs/release-notes.asciidoc
- docs/template-script.asciidoc
- [Docs]Post upgrade reindex requirement (#217)
> [7.9] [Docs]Post upgrade reindex requirement (#217)

- docs/post-upgrade-req.asciidoc
- docs/release-notes.asciidoc
- docs/template-script.asciidoc
- [Docs]Adds index post upgrade requirement clarifications (#223)
> [7.x] [Docs]Adds index post upgrade requirement clarifications (#223)

- docs/release-notes.asciidoc
Adds fixed bugs to the RNs.
[Preview](https://security-docs_231.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
> [Docs]Adds 7.9.1 fixed bugs

- docs/release-notes.asciidoc
- [Docs]Adds 7.9.1 fixed bugs (#231)
> [7.x] [Docs]Adds 7.9.1 fixed bugs (#231)

- docs/detections/rules-ui-manage.asciidoc
- docs/getting-started/detections-req.asciidoc
> [Docs]fixes a couple of typos

- docs/detections/rules-ui-manage.asciidoc
- docs/getting-started/detections-req.asciidoc
- fixes a couple of typos (#234)
> [7.x] fixes a couple of typos (#234)

- docs/detections/rules-ui-manage.asciidoc
- docs/getting-started/detections-req.asciidoc
- fixes a couple of typos (#234)
> [7.9] fixes a couple of typos (#234)

- docs/detections/api/lists/api-create-list-container.asciidoc
Adds info on how to parse list item values and use custom value presentations.
[Preview](https://security-docs_237.docs-preview.app.elstc.co/guide/en/security/master/lists-api-create-container.html)
> [Docs]Adds list item value parsing

- docs/detections/api/lists/api-create-list-container.asciidoc
- [Docs]Adds list item value parsing (#237)
> [7.x] [Docs]Adds list item value parsing (#237)

- docs/detections/detection-engine-intro.asciidoc
- docs/getting-started/detections-req.asciidoc
- docs/getting-started/sec-app-requirements.asciidoc
- Replace On-Prem with self-managed in Detections section (#255)
> [7.9] Replace On-Prem with self-managed in Detections section (#255)

- docs/detections/detection-engine-intro.asciidoc
- docs/getting-started/detections-req.asciidoc
- docs/getting-started/sec-app-requirements.asciidoc
- Replace On-Prem with self-managed in Detections section (#255)
> [7.x] Replace On-Prem with self-managed in Detections section (#255)

- prebuilt-rules-scripts/create-json-from-docs.py
- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.8.0.json
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0-new.json
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0.json
- prebuilt-rules-scripts/get-rule-diff.py
- prebuilt-rules-scripts/orig-rules-json-files/7.6-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.6.1-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.6.2-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.7.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.8.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.9.0-prebuilt-rule-new.json
- prebuilt-rules-scripts/orig-rules-json-files/7.9.0-prebuilt-rule.json
- prebuilt-rules-scripts/readme.md
- prebuilt-rules-scripts/update_current_text.py
Adds scripts for generating prebuilt detection rule documentation.
> [Docs]Adds prebuilt rule scripts

- prebuilt-rules-scripts/create-json-from-docs.py
- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.8.0.json
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0-new.json
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0.json
- prebuilt-rules-scripts/get-rule-diff.py
- prebuilt-rules-scripts/orig-rules-json-files/7.6-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.6.1-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.6.2-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.7.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.8.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.9.0-prebuilt-rule-new.json
- prebuilt-rules-scripts/orig-rules-json-files/7.9.0-prebuilt-rule.json
- prebuilt-rules-scripts/readme.md
- prebuilt-rules-scripts/update_current_text.py
- [Docs]Adds prebuilt rule scripts (#265)
> [7.x] [Docs]Adds prebuilt rule scripts (#265)

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/get-rule-diff.py
- [Docs]Minor rule script edits (#274)
> [7.x] [Docs]Minor rule script edits (#274)

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/get-rule-diff.py
- [Docs]Minor rule script edits (#274)
> [7.10] [Docs]Minor rule script edits (#274)

- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.8.0.json
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0.json
- prebuilt-rules-scripts/orig-rules-json-files/7.10.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.6-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.6.1-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.6.2-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.7.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/7.8.0-prebuilt-rule.json
Adds missing prebuilt rule scripts
> [Docs]Add prebuilt rule scripts

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.1.json
- prebuilt-rules-scripts/get-rule-diff.py
- prebuilt-rules-scripts/readme.md
- prebuilt-rules-scripts/update_current_text.py
- minor script corrections (#295)
> [7.x] minor script corrections (#295)

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.1.json
- prebuilt-rules-scripts/get-rule-diff.py
- prebuilt-rules-scripts/readme.md
- prebuilt-rules-scripts/update_current_text.py
- minor script corrections (#295)
> [7.10] minor script corrections (#295)

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.1.json
- prebuilt-rules-scripts/get-rule-diff.py
- prebuilt-rules-scripts/readme.md
- prebuilt-rules-scripts/update_current_text.py
- minor script corrections (#295)
> [7.9] minor script corrections (#295)

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/readme.md
- adds list of rules with changed names (#299)
> [7.x] adds list of rules with changed names (#299)

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/readme.md
- adds list of rules with changed names (#299)
> [7.10] adds list of rules with changed names (#299)

- prebuilt-rules-scripts/create_documentation.py
- prebuilt-rules-scripts/readme.md
- adds list of rules with changed names (#299)
> [7.9] adds list of rules with changed names (#299)

- docs/whats-new.asciidoc
Backports https://github.com/elastic/security-docs/pull/319
> [7.x][DOCS] Add machine learning jobs to Whats New (#319)

- docs/whats-new.asciidoc
Backport https://github.com/elastic/security-docs/pull/319
> [7.10][DOCS] Add machine learning jobs to Whats New (#319)

- docs/whats-new.asciidoc
This PR changes the title of the ML related release highlight item in "What's new".
[What's new – ML](https://security-docs_325.docs-preview.app.elstc.co/guide/en/security/master/whats-new.html#sec-ml-7.10-changes)
> [DOCS] Changes the title of the ML related highlight section

- docs/getting-started/install-endpoint.asciidoc
- [DOCS] Updates to install endpoint page  (#331)
> [7.10] [DOCS] Updates to install endpoint page  (#331)

- docs/getting-started/install-endpoint.asciidoc
- [DOCS] Updates to install endpoint page  (#331)
> [7.x] [DOCS] Updates to install endpoint page  (#331)

- docs/getting-started/advanced-setting.asciidoc
- docs/getting-started/index.asciidoc
- Getting Started updates - 7.10  (#340)
> [7.x] Getting Started updates - 7.10  (#340)

- docs/getting-started/advanced-setting.asciidoc
- docs/getting-started/index.asciidoc
- Getting Started updates - 7.10  (#340)
> [7.10] Getting Started updates - 7.10  (#340)

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/api/rules/rules-api-update.asciidoc
Updates the API docs with new rule types for 7.10.0.
[Create rule API preview](https://security-docs_270.docs-preview.app.elstc.co/guide/en/security/master/rules-api-create.html)
[Update rule API preview](https://security-docs_270.docs-preview.app.elstc.co/guide/en/security/master/rules-api-update.html)
> [Docs]Adds 7.10 detection rule updates to API docs

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/api/rules/rules-api-update.asciidoc
- [Docs]Adds 7.10 detection rule updates to API docs (#270)
> [7.10] [Docs]Adds 7.10 detection rule updates to API docs (#270)

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/api/rules/rules-api-update.asciidoc
- [Docs]Adds 7.10 detection rule updates to API docs (#270)
> [7.x] [Docs]Adds 7.10 detection rule updates to API docs (#270)

- docs/whats-new.asciidoc
> [7.10] update to what's new (#361)

- docs/release-notes.asciidoc
Remove redundant upgrade requirements section
> Add known issue about value lists

- docs/release-notes.asciidoc
- Add known issue about value lists (#383)
> [7.10] Add known issue about value lists (#383)

- docs/release-notes.asciidoc
- Add known issue about value lists (#383)
> [7.x] Add known issue about value lists (#383)

- docs/reference/timeline-schema.asciidoc
> Issue-395: Change Event Type for Timeline Schema

- docs/es-overview.asciidoc
- docs/getting-started/advanced-setting.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- docs/management/admin/admin-pg-ov.asciidoc
Fixes attribute used to resolve fleet link. Needs to be backported to 7.10 and later.
> Fix broken Fleet links

- docs/es-overview.asciidoc
- docs/getting-started/advanced-setting.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- docs/management/admin/admin-pg-ov.asciidoc
- Fix broken Fleet links (#420)
> [7.11] Fix broken Fleet links (#420)

- docs/detections/rules-ui-create.asciidoc
using context.rule.filters is worth an example as it requires :
1- Understand that one should check the rule json representation to get an idea of which fields.
2- A bit of know-how on using mustache to iterate in an array and use a boolean condition
> DOCS: Clarification for using filters array

- docs/detections/rules-ui-create.asciidoc
> DOCS: Clarification for using filters array (#426)

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/rules-ui-create.asciidoc
Documents the changes in https://github.com/elastic/kibana/pull/85488
> Add context.alerts to rule creation UI and API docs

- docs/detections/api/rules/rules-api-create.asciidoc
Adding {{context.alerts}}: Array of detected alerts to 7.11 branch.
> [DOCS] Adding alert array placeholder to 7.11

- docs/es-overview.asciidoc
Addresses the following: 
- #468 
- #428
> [DOCS] Updates to Elastic Security Overview

- docs/es-overview.asciidoc
- [DOCS] Updates to Elastic Security Overview (#476)
> [7.10] [DOCS] Updates to Elastic Security Overview (#476)

- docs/es-overview.asciidoc
- [DOCS] Updates to Elastic Security Overview (#476)
> [7.11] [DOCS] Updates to Elastic Security Overview (#476)

- docs/es-overview.asciidoc
- [DOCS] Updates to Elastic Security Overview (#476)
> [7.x] [DOCS] Updates to Elastic Security Overview (#476)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
- docs/cases/api/cases-api/case-api-update-connector.asciidoc
- docs/cases/api/cases-api/cases-api-add-comment.asciidoc
- docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
- docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
- docs/cases/api/cases-api/cases-api-create.asciidoc
- docs/cases/api/cases-api/cases-api-find-cases.asciidoc
- docs/cases/api/cases-api/cases-api-find-connectors.asciidoc
- docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
- docs/cases/api/cases-api/cases-api-get-case-comments.asciidoc
- docs/cases/api/cases-api/cases-api-get-case.asciidoc
- docs/cases/api/cases-api/cases-api-get-comment.asciidoc
- docs/cases/api/cases-api/cases-api-get-connector.asciidoc
- docs/cases/api/cases-api/cases-api-get-status.asciidoc
- docs/cases/api/cases-api/cases-api-index.asciidoc
- docs/cases/api/cases-api/cases-api-push.asciidoc
- docs/cases/api/cases-api/cases-api-update-comment.asciidoc
- docs/cases/api/cases-api/cases-api-update.asciidoc
- docs/cases/cases-overview.asciidoc
- docs/cases/cases-ui-integrations.asciidoc
- docs/index.asciidoc
Updates the API docs for 7.11.
Ref: https://github.com/elastic/security-docs/issues/440
> [Docs] 7.11 Cases API updates

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
- docs/cases/api/cases-api/case-api-update-connector.asciidoc
- docs/cases/api/cases-api/cases-api-add-comment.asciidoc
- docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
- docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
- docs/cases/api/cases-api/cases-api-create.asciidoc
- docs/cases/api/cases-api/cases-api-find-cases.asciidoc
- docs/cases/api/cases-api/cases-api-find-connectors.asciidoc
- docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
- docs/cases/api/cases-api/cases-api-get-case-comments.asciidoc
- docs/cases/api/cases-api/cases-api-get-case.asciidoc
- docs/cases/api/cases-api/cases-api-get-comment.asciidoc
- docs/cases/api/cases-api/cases-api-get-connector.asciidoc
- docs/cases/api/cases-api/cases-api-get-status.asciidoc
- docs/cases/api/cases-api/cases-api-index.asciidoc
- docs/cases/api/cases-api/cases-api-push.asciidoc
- docs/cases/api/cases-api/cases-api-update-comment.asciidoc
- docs/cases/api/cases-api/cases-api-update.asciidoc
- docs/cases/cases-overview.asciidoc
- docs/cases/cases-ui-integrations.asciidoc
- docs/index.asciidoc
- [Docs] 7.11 Cases API updates (#445)
> [7.x] [Docs] 7.11 Cases API updates (#445)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
- docs/cases/api/cases-api/case-api-update-connector.asciidoc
- docs/cases/api/cases-api/cases-api-add-comment.asciidoc
- docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
- docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
- docs/cases/api/cases-api/cases-api-create.asciidoc
- docs/cases/api/cases-api/cases-api-find-cases.asciidoc
- docs/cases/api/cases-api/cases-api-find-connectors.asciidoc
- docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
- docs/cases/api/cases-api/cases-api-get-case-comments.asciidoc
- docs/cases/api/cases-api/cases-api-get-case.asciidoc
- docs/cases/api/cases-api/cases-api-get-comment.asciidoc
- docs/cases/api/cases-api/cases-api-get-connector.asciidoc
- docs/cases/api/cases-api/cases-api-get-status.asciidoc
- docs/cases/api/cases-api/cases-api-index.asciidoc
- docs/cases/api/cases-api/cases-api-push.asciidoc
- docs/cases/api/cases-api/cases-api-update-comment.asciidoc
- docs/cases/api/cases-api/cases-api-update.asciidoc
- docs/cases/cases-overview.asciidoc
- docs/cases/cases-ui-integrations.asciidoc
- docs/index.asciidoc
- [Docs] 7.11 Cases API updates (#445)
> [7.11] [Docs] 7.11 Cases API updates (#445)

- docs/management/admin/admin-pg-ov.asciidoc
> [DOCS] Trusted apps updates for 7.11

- docs/management/admin/admin-pg-ov.asciidoc
> [7.x] Updates for 7.11. (#484)

- docs/management/admin/admin-pg-ov.asciidoc
> [7.11] Updates for 7.11. (#484)

- docs/siem-apis.asciidoc
> Issue #412 - Add warning about Kibana Dev Console

- docs/detections/detection-engine-intro.asciidoc
- docs/es-overview.asciidoc
Addresses #446. 
[Preview link](https://security-docs_487.docs-preview.app.elstc.co/guide/en/security/master/detection-engine-overview.html#cold-tier-detections).
> [DOCS] Detection engine/cold tier data - 7.11

- docs/whats-new.asciidoc
> [DOCS] What's new in 7.11

- docs/whats-new.asciidoc
- [DOCS] What's new in 7.11 (#511)
> [7.x] [DOCS] What's new in 7.11 (#511)

- docs/whats-new.asciidoc
- [DOCS] What's new in 7.11 (#511)
> [7.11] [DOCS] What's new in 7.11 (#511)

- docs/cases/api/cases-api/case-api-update-connector.asciidoc
- docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
- docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
- docs/cases/api/cases-api/cases-api-create.asciidoc
- docs/cases/api/cases-api/cases-api-find-cases.asciidoc
- docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
- docs/cases/api/cases-api/cases-api-get-case.asciidoc
- docs/cases/api/cases-api/cases-api-get-connector.asciidoc
- docs/cases/api/cases-api/cases-api-update.asciidoc
PR https://github.com/elastic/kibana/pull/77327 changed the way a connector is being used. This PR updated the docs accordingly.
> [Docs][Cases] Fix docs for 7.10: Connector

- docs/release-notes.asciidoc
Fixing links to the known issues.
> [DOCS] Fixes know issue links to 7.11 release notes

- docs/detections/api/rules/rules-api-create.asciidoc
- [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules  (#522)
> [7.12] [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules  (#522)

- docs/release-notes.asciidoc
> [DOCS] Update 7.11 RNs

- docs/release-notes.asciidoc
Addresses #555 the second time.
> [DOCS] NEW - Update to 7.11 RNs

- docs/release-notes.asciidoc
- [DOCS] 7.12.0 release notes  (#550)
> [7.12] [DOCS] 7.12.0 release notes  (#550)

- docs/getting-started/install-endpoint.asciidoc
- [DOCS] UPDATED - Ransomware (7.12) (#567)
> [7.12] [DOCS] UPDATED - Ransomware (7.12) (#567)

- docs/getting-started/install-endpoint.asciidoc
- [DOCS] UPDATED - Ransomware (7.12) (#567)
> [7.x] [DOCS] UPDATED - Ransomware (7.12) (#567)

- docs/whats-new.asciidoc
> [DOCS] What's new (7.12)

- docs/whats-new.asciidoc
- Update whats-new.asciidoc (#583)
> [7.x] Update whats-new.asciidoc (#583)

- docs/whats-new.asciidoc
- Update whats-new.asciidoc (#583)
> [7.12] Update whats-new.asciidoc (#583)

- docs/release-notes.asciidoc
Hi @spong and @FrankHassanabad - please let me know if this change was for 7.12 only or 7.11 as well please. Thanks!
> [DOCS] Adding #91718 to 7.12 release notes

- docs/release-notes.asciidoc
> [DOCS] Release note fix (7.11.2)

- docs/detections/rules-ui-monitor.asciidoc
Fixes https://github.com/elastic/security-docs/issues/546
https://security-docs_553.docs-preview.app.elstc.co/guide/en/security/7.12/alerts-ui-monitor.html#ml-job-compatibility
> [DOCS] Add section for troubleshooting ML compatibility

- docs/detections/rules-ui-monitor.asciidoc
Backports https://github.com/elastic/security-docs/pull/553
> [7.11][DOCS] Add section for troubleshooting ML compatibility (#553)

- docs/detections/rules-ui-monitor.asciidoc
Forward-fits https://github.com/elastic/security-docs/pull/553 to 7.x to align with https://github.com/elastic/kibana/pull/94393
> [7.x][DOCS] Add section for troubleshooting ML compatibility (#553)

- docs/detections/rules-ui-monitor.asciidoc
Forward-fits #553 to master to align with elastic/kibana#94393
> [DOCS] Add section for troubleshooting ML compatibility (#553)

- docs/getting-started/ingest-data.asciidoc
> [8.0] Correcting spelling from Window to Windows (#592)

- docs/detections/api/rules/rules-api-export.asciidoc
> [DOCS] Update rules-api-export.asciidoc (#593)

- docs/release-notes.asciidoc
Added #91597 as a known issue.
> [DOCS] Updating 7.12.0 RN to include #91597 as a known issue

- docs/events/timeline-templates.asciidoc
Added a generic timeline template to the docs for this PR that adds the Indicator Match Timeline template. https://github.com/elastic/kibana/pull/95840
> [Timeline] Update Timeline Template Documentation

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
- docs/cases/api/cases-api/cases-api.asciidoc
- docs/cases/cases-overview.asciidoc
- docs/detections/api/rules/rules-api-overview.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
- docs/events/api/timeline-api-overview.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- [DOCS] Removed the beta tag from all docs about detections and cases (#637)
> [7.x] [DOCS] Removed the beta tag from all docs about detections and cases (#637)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
- docs/cases/api/cases-api/cases-api.asciidoc
- docs/cases/cases-overview.asciidoc
- docs/detections/api/rules/rules-api-overview.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
- docs/events/api/timeline-api-overview.asciidoc
- docs/getting-started/install-endpoint.asciidoc
- [DOCS] Removed the beta tag from all docs about detections and cases (#637)
> [7.12] [DOCS] Removed the beta tag from all docs about detections and cases (#637)

- .backportrc.json
Adding `7.13` branch to backport.
> [DOCS] Update .backportrc.json

- docs/release-notes.asciidoc
- [DOCS] 7.12.1 release notes (#607)
> [7.x] [DOCS] 7.12.1 release notes (#607)

- docs/release-notes.asciidoc
- [DOCS] 7.12.1 release notes (#607)
> [7.13] [DOCS] 7.12.1 release notes (#607)

- docs/release-notes.asciidoc
- [DOCS] 7.12.1 release notes (#607)
> [7.12] [DOCS] 7.12.1 release notes (#607)

- docs/cases/cases-overview.asciidoc
- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/detections-ui-exceptions.asciidoc
- docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
- docs/detections/rules-ui-create.asciidoc
- docs/events/timeline-templates.asciidoc
- Preview of editorial updates to the "Cases" topic is available [here](https://security-docs_644.docs-preview.app.elstc.co/guide/en/security/master/cases-overview.html).
- Preview of editorial updates to the "Configure external connections" topic is available [here](https://security-docs_644.docs-preview.app.elstc.co/guide/en/security/master/cases-ui-integrations.html).
- Preview of editorial updates to the "Rule exceptions and value lists" topic is available [here](https://security-docs_644.docs-preview.app.elstc.co/guide/en/security/master/detections-ui-exceptions.html).
- Preview of editorial updates to the "Create a detection rule" is available [here](https://security-docs_644.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html).
- Preview of editorial updates to …
> [DOCS] Editorial review of topics that were updated to resolve QA-reported doc bugs

- docs/cases/cases-overview.asciidoc
- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/detections-ui-exceptions.asciidoc
- docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
- docs/detections/rules-ui-create.asciidoc
- docs/events/timeline-templates.asciidoc
- [DOCS] Editorial review of topics that were updated to resolve QA-reported doc bugs (#644)
> [7.12] [DOCS] Editorial review of topics that were updated to resolve QA-reported doc bugs (#644)

- docs/cases/cases-overview.asciidoc
- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/detections-ui-exceptions.asciidoc
- docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
- docs/detections/rules-ui-create.asciidoc
- docs/events/timeline-templates.asciidoc
- [DOCS] Editorial review of topics that were updated to resolve QA-reported doc bugs (#644)
> [7.13] [DOCS] Editorial review of topics that were updated to resolve QA-reported doc bugs (#644)

- docs/cases/cases-overview.asciidoc
- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/detections-ui-exceptions.asciidoc
- docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
- docs/detections/rules-ui-create.asciidoc
- docs/events/timeline-templates.asciidoc
- [DOCS] Editorial review of topics that were updated to resolve QA-reported doc bugs (#644)
> [7.x] [DOCS] Editorial review of topics that were updated to resolve QA-reported doc bugs (#644)

- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/rules-ui-manage.asciidoc
- Adding e-learning videos to Detections and Cases docs (#594)
> [7.13] Adding e-learning videos to Detections and Cases docs (#594)

- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/rules-ui-manage.asciidoc
- Adding e-learning videos to Detections and Cases docs (#594)
> [7.x] Adding e-learning videos to Detections and Cases docs (#594)

- docs/detections/detections-ui-exceptions.asciidoc
- [DOCS] Exceptions updates 7.13 (#675)
> [7.13] [DOCS] Exceptions updates 7.13 (#675)

- docs/getting-started/ingest-data.asciidoc
Relates elastic/observability-docs#483
> Add link to ingest data with Splunk

- docs/getting-started/ingest-data.asciidoc
- Add link to ingest data with Splunk (#679)
> [7.13] Add link to ingest data with Splunk (#679)

- docs/getting-started/ingest-data.asciidoc
- Add link to ingest data with Splunk (#679)
> [7.x] Add link to ingest data with Splunk (#679)

- docs/detections/api/rules/rules-api-create.asciidoc
- [DOCS] Create rule API updates (7.13)  (#668)
> [7.x] [DOCS] Create rule API updates (7.13)  (#668)

- docs/detections/api/rules/rules-api-create.asciidoc
- [DOCS] Create rule API updates (7.13)  (#668)
> [7.13] [DOCS] Create rule API updates (7.13)  (#668)

- docs/events/api/timeline-api-create.asciidoc
- docs/events/api/timeline-api-delete.asciidoc
- docs/events/api/timeline-api-export.asciidoc
- docs/events/api/timeline-api-get.asciidoc
- docs/events/api/timeline-api-index.asciidoc
- docs/events/api/timeline-api-overview.asciidoc
- docs/events/api/timeline-api-update.asciidoc
> [7.x] Update timeline docs (#678)

- docs/events/api/timeline-api-create.asciidoc
- docs/events/api/timeline-api-delete.asciidoc
- docs/events/api/timeline-api-export.asciidoc
- docs/events/api/timeline-api-get.asciidoc
- docs/events/api/timeline-api-index.asciidoc
- docs/events/api/timeline-api-overview.asciidoc
- docs/events/api/timeline-api-update.asciidoc
> [7.13] Update timeline docs (#678)

- docs/release-notes.asciidoc
- [DOCS] 7.13 release notes (#671)
> [7.x] [DOCS] 7.13 release notes (#671)

- docs/release-notes.asciidoc
- [DOCS] 7.13 release notes (#671)
> [7.13] [DOCS] 7.13 release notes (#671)

- docs/detections/rules-ui-create.asciidoc
- [DOCS] Create rule updates (#684)
> [7.13] [DOCS] Create rule updates (#684)

- docs/detections/rules-ui-create.asciidoc
- [DOCS] Create rule updates (#684)
> [7.x] [DOCS] Create rule updates (#684)

- docs/whats-new.asciidoc
- [DOCS] What's new in 7.13?  (#702)
> [7.13] [DOCS] What's new in 7.13?  (#702)

- docs/whats-new.asciidoc
- [DOCS] What's new in 7.13?  (#702)
> [7.x] [DOCS] What's new in 7.13?  (#702)

- docs/getting-started/detections-req.asciidoc
> [DOCS] Fixing privs error 

- docs/getting-started/detections-req.asciidoc
Fixing typo in 7.x. 
Related to #717.
> [DOCS] Fixing privs error (7.x)

- docs/detections/alerts-ui-manage.asciidoc
- docs/detections/rules-ui-manage.asciidoc
- Moving prebuilt rules update to the correct topic. (#720)
> [7.13] Moving prebuilt rules update to the correct topic. (#720)

- docs/detections/alerts-ui-manage.asciidoc
- docs/detections/rules-ui-manage.asciidoc
- Moving prebuilt rules update to the correct topic. (#720)
> [7.x] Moving prebuilt rules update to the correct topic. (#720)

- docs/getting-started/install-endpoint.asciidoc
- Added beta tag to top of topic. (#724)
> [7.13] Added beta tag to top of topic. (#724)

- docs/getting-started/install-endpoint.asciidoc
- Added beta tag to top of topic. (#724)
> [7.x] Added beta tag to top of topic. (#724)

- docs/release-notes.asciidoc
Addresses #764.
Preview [here](https://security-docs_765.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html).
> [BUG] Add #102146 to the 7.13.2 RN as a known issue

- docs/release-notes.asciidoc
Addresses https://github.com/elastic/security-docs/issues/772
Preview [here](https://security-docs_784.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html).
> [DOCS] 7.13.3 Release Notes

- docs/release-notes.asciidoc
- [DOCS] 7.13.3 Release Notes (#784)
> [7.14] [DOCS] 7.13.3 Release Notes (#784)

- docs/release-notes.asciidoc
- [DOCS] 7.13.3 Release Notes (#784)
> [7.x] [DOCS] 7.13.3 Release Notes (#784)

- docs/release-notes.asciidoc
- [DOCS] 7.13.3 Release Notes (#784)
> [7.13] [DOCS] 7.13.3 Release Notes (#784)

- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-attempts-to-brute-force-a-microsoft-365-user-account.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-full-network-packet-capture-detected.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-vm-export-failure.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-instance-creation.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-creation.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-deletion.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-snapshot-export.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transfer-lock-disabled.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transferred-to-another-account.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-azure-service-principal-credentials-added.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-disabling-windows-defender-security-settings-via-powershell.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-enable-host-network-discovery-via-netsh.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-persistence-via-folder-action-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-dll-side-loading-via-microsoft-antimalware-service-executable.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-password-spraying-of-microsoft-365-user-accounts.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-exploit-registry-modification.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-file-modification.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-shell-execution-via-apple-scripting.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-smb-windows-file-sharing-activity-to-the-internet.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-suspicious-print-spooler-file-deletion.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-unusual-print-spooler-child-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
- Add docs for 0.13.2 rules integration package (#793)
> [7.13] Add docs for 0.13.2 rules integration package (#793)

- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
- Update prebuilt-rules-0-13-2-summary.asciidoc (#799)
> [7.x] Update prebuilt-rules-0-13-2-summary.asciidoc (#799)

- docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
- Update prebuilt-rules-0-13-2-summary.asciidoc (#799)
> [7.14] Update prebuilt-rules-0-13-2-summary.asciidoc (#799)

- docs/events/index.asciidoc
Addresses #816.
Preview link [here](https://security-docs_817.docs-preview.app.elstc.co/diff).
> [DOCS] Correct typos in Investigate events page (index.asciidoc)

- docs/detections/api/exceptions-api-index.asciidoc
- docs/detections/api/exceptions/api-summary-exception-container.asciidoc
- [Security solution] [Endpoint] Adds documentation for exceptions container summary (#824)
> [7.x] [Security solution] [Endpoint] Adds documentation for exceptions container summary (#824)

- docs/detections/api/exceptions-api-index.asciidoc
- docs/detections/api/exceptions/api-summary-exception-container.asciidoc
- [Security solution] [Endpoint] Adds documentation for exceptions container summary (#824)
> [7.14] [Security solution] [Endpoint] Adds documentation for exceptions container summary (#824)

- docs/release-notes.asciidoc
- [DOCS] 7.14.0 Release Notes (#811)
> [7.x] [DOCS] 7.14.0 Release Notes (#811)

- docs/release-notes.asciidoc
- [DOCS] 7.14.0 Release Notes (#811)
> [7.14] [DOCS] 7.14.0 Release Notes (#811)

- docs/es-overview.asciidoc
- docs/getting-started/index.asciidoc
- docs/getting-started/sensor-full-disk-access.asciidoc
- Committing - nav changes. (#861)
> [7.14] Committing - nav changes. (#861)

- docs/es-overview.asciidoc
- docs/getting-started/index.asciidoc
- docs/getting-started/sensor-full-disk-access.asciidoc
- Committing - nav changes. (#861)
> [7.x] Committing - nav changes. (#861)

- docs/whats-new.asciidoc
- [DOCS] What's new in 7.14  (#873)
> [7.x] [DOCS] What's new in 7.14  (#873)

- docs/whats-new.asciidoc
- [DOCS] What's new in 7.14  (#873)
> [7.14] [DOCS] What's new in 7.14  (#873)

- docs/release-notes.asciidoc
Preview [here](https://security-docs_879.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html).
> [DOCS] Add "Security update" section to 7.14 RN

- docs/detections/rules-ui-create.asciidoc
- [BUG] Update reported bugs (#881)
> [7.x] [BUG] Update reported bugs (#881)

- docs/detections/rules-ui-create.asciidoc
- [BUG] Update reported bugs (#881)
> [7.14] [BUG] Update reported bugs (#881)

- docs/getting-started/security-ui.asciidoc
Addresses #902.
Preview [here](https://security-docs_914.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html).
> [BUG] Incorrect reference of Trusted App under Event Filter Section Doc

- docs/cases/api/cases-api/cases-api-create.asciidoc
> [7.14] Fixed table issue. (#921)

- docs/cases/api/cases-api/cases-api-create.asciidoc
> [7.x] Fixed table issue. (#921)

- docs/getting-started/install-endpoint.asciidoc
No issue created for this change.
Preview [here](https://security-docs_929.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html).
> Remove beta tag from install-endpoint.asciidoc

- docs/getting-started/install-endpoint.asciidoc
- Remove section for verifying enrollment (#922)
> [7.14] Remove section for verifying enrollment (#922)

- docs/getting-started/install-endpoint.asciidoc
- Remove section for verifying enrollment (#922)
> [7.x] Remove section for verifying enrollment (#922)

- docs/detections/rules-ui-manage.asciidoc
Resolves #911. 
Preview [here](https://security-docs_938.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-management.html).
> [BUG] Updates to Manage detection rules

- docs/detections/rules-ui-manage.asciidoc
- Bug fix; small edits. (#938)
> [7.x] Updates to Manage detection rules (#938)

- docs/detections/rules-ui-manage.asciidoc
- Bug fix; small edits. (#938)
> [7.14] Updates to Manage detection rules (#938)

- docs/cases/cases-ui-integrations.asciidoc
- Fixed error for SN field. (#925)
> [7.14] Fixed error for SN field. (#925)

- docs/cases/cases-ui-integrations.asciidoc
- Fixed error for SN field. (#925)
> [7.x] Fixed error for SN field. (#925)

- docs/detections/detections-ui-exceptions.asciidoc
- [BUG] Incorrect Type of value list name are displayed in value list  (#880)
> [7.14] [BUG] Incorrect Type of value list name are displayed in value list  (#880)

- docs/release-notes.asciidoc
Addresses #924. 
Preview [here](https://security-docs_974.docs-preview.app.elstc.co/guide/en/security/7.x/release-notes.html).
> [DOCS] Release note cleanup

- docs/detections/api/rules/rules-api-bulk-actions.asciidoc
> [7.14] bulk_action API update (#978)

- docs/detections/api/rules/rules-api-bulk-actions.asciidoc
> [7.15] bulk_action API update (#978)

- docs/detections/api/rules/rules-api-bulk-actions.asciidoc
> [7.x] bulk_action API update (#978)

- docs/release-notes.asciidoc
- [DOCS] 7.14.1 Release Notes (#987)
> [7.15] [DOCS] 7.14.1 Release Notes (#987)

- docs/release-notes.asciidoc
- [DOCS] 7.14.1 Release Notes (#987)
> [7.14] [DOCS] 7.14.1 Release Notes (#987)

- docs/release-notes/7.14.asciidoc
Addresses #1059.
Preview [here](https://security-docs_1060.docs-preview.app.elstc.co/guide/en/security/7.14/release-notes.html).
> [DOCS] Release notes [7.14.2]

- docs/release-notes/7.14.asciidoc
- [DOCS] Release notes [7.14.2] (#1060)
> [7.x] [DOCS] Release notes [7.14.2] (#1060)

- docs/release-notes/7.14.asciidoc
- [DOCS] Release notes [7.14.2] (#1060)
> [7.15] [DOCS] Release notes [7.14.2] (#1060)

- docs/management/admin/host-isolation-ov.asciidoc
- [DOCS] Document Linux OS support for host isolation (#1054)
> [7.15] [DOCS] Document Linux OS support for host isolation (#1054)

- docs/management/admin/host-isolation-ov.asciidoc
- [DOCS] Document Linux OS support for host isolation (#1054)
> [7.x] [DOCS] Document Linux OS support for host isolation (#1054)

- docs/detections/detection-engine-intro.asciidoc
> [DOCS] Update detection-engine-intro.asciidoc (#1132)

- docs/getting-started/security-ui.asciidoc
- docs/troubleshooting/management/ts-management.asciidoc
- Fix relative links to images (#1141)
> [7.x] Fix relative links to images (#1141)

- docs/detections/rules-ui-manage.asciidoc
- Updates new option to select all rules in the All rules table. 
Preview [here](https://security-docs_1214.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-management.html).
> [BUG] Update to "Duplicate all prebuilt rules" section

- docs/management/api/get-endpoint-api.asciidoc
- docs/management/api/host-isolation-api.asciidoc
- docs/management/api/list-endpoints-api.asciidoc
- docs/management/api/management-api-index.asciidoc
- docs/management/api/remove-isolated-host-api.asciidoc
- docs/siem-apis.asciidoc
Addresses #1225. 
Preview starts [here](https://security-docs_1227.docs-preview.app.elstc.co/guide/en/security/master/management-api-overview.html).
> [DOCS] Add new endpoint management APIs

- docs/getting-started/install-endpoint.asciidoc
Updating link for changed URL introduced by elastic/observability-docs#1274.
(PR build will fail until elastic/observability-docs#1274 is merged)
> Update link to docs about adding a Fleet Server

- docs/getting-started/ml-req.asciidoc
> [7.13] [DOCS] Update security doc ML requirements (#1281)

- docs/getting-started/ml-req.asciidoc
> [8.0] [DOCS] Update security doc ML requirements (#1281)

- docs/release-notes.asciidoc
- docs/release-notes/7.16.asciidoc
Adds the release notes for 7.16.2.
> [DOCS] Add 7.16.2 release notes

- docs/release-notes.asciidoc
- docs/release-notes/7.16.asciidoc
Backports the following commits to 7.17:
- [DOCS] Add 7.16.2 release notes (#1362)
> [7.17] [DOCS] Add 7.16.2 release notes (#1362)

- docs/cases/api/cases-api/cases-api-create.asciidoc
> [DOCS] Updates create case API

- docs/management/api/list-endpoints-api.asciidoc
Updating management endpoints lists API docs from old POST method to new GET method.
Preview [here](https://security-docs_1376.docs-preview.app.elstc.co/guide/en/security/master/list-endpoints-api.html).
> [DOCS] update list endpoints documentation

- docs/detections/detections-ui-exceptions.asciidoc
- docs/detections/rules-ui-create.asciidoc
> [DOCS] EQL updates 

- docs/management/admin/trusted-apps.asciidoc
* Resolves #1467.
Preview [here](https://security-docs_1469.docs-preview.app.elstc.co/guide/en/security/master/trusted-apps-ov.html).
> [DOCS] Improve Trusted Apps "wildcard"/"matches" field documentation

- docs/index.asciidoc
- docs/upgrade/upgrade-security.asciidoc
Resolves #1374; however, this is an extremely rough draft and will be edited in subsequent PRs.
> [DOCS] Upgrade Elastic Security

- docs/detections/query-alert-indices.asciidoc
Adds a missing [discrete] tag to the query alert indices topic
> Add a missing [discrete tag]

- docs/detections/rules-ui-create.asciidoc
> [DOCS] Preview rules privilege update

- docs/events/timeline-ui-overview.asciidoc
Adding some feedback that I received after I had already merged https://github.com/elastic/security-docs/pull/1636
> Timeline overview topic — two minor fixes

- docs/getting-started/detections-req.asciidoc
Resolves #1570.  Applies to 7.13-7.17.
> [BUG] Updates manage alerts permission reqs in 7.x 

- docs/cases/cases-ui-integrations.asciidoc
> [8.0] Tiny typo (#1684)

- docs/upgrade/upgrade-security.asciidoc
> [8.0] Backport Upgrade Security topic (#1731)

- docs/upgrade/upgrade-security.asciidoc
> [8.1] Backport Upgrade Security topic (#1731)

- docs/getting-started/advanced-setting.asciidoc
> Correct minor typo in advanced-setting.asciidoc

- docs/detections/rules-ui-create.asciidoc
Fixes https://github.com/elastic/security-docs/issues/1429.
Preview [here](https://security-docs_1808.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#preview-rules).
> [DOCS] Indicator match rule preview

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/1802.
Previews:
- [Updated index page](https://security-docs_1805.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_1805.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.3)
> [DOCS] 7.17.3 Release Notes

- docs/release-notes.asciidoc
- docs/release-notes/8.1.asciidoc
- [DOCS] 8.1.3 Release Notes (#1806)
> [8.1] [DOCS] 8.1.3 Release Notes (#1806)

- docs/release-notes/8.1.asciidoc
Bolds the Hosts and Network page names.
> [BUG] Style fix for RN summary in 8.1.3 

- docs/getting-started/configure-integration-policy.asciidoc
- docs/management/admin/blocklist.asciidoc
> [DOCS] Blocklist follow-up

- docs/detections/alerts-runtime-fields.asciidoc
_Forward_-ports the following commits to main:
- [8.2] [DOCS] Field browser and runtime fields on Alerts table (55a23a85) (#1908)
> [main] [8.2] [DOCS] Field browser and runtime fields on Alerts table (55a23a85) (#1908)

- docs/detections/alerts-ui-manage.asciidoc
> [BUG] Rename alert status action to "Mark as open" 

- docs/detections/alerts-ui-manage.asciidoc
- Renames and reorders alert status actions (#1925)
> [8.0] Renames and reorders alert status actions (#1925)

- docs/release-notes/8.3.asciidoc
> [BUG] Fixing broken ref in breaking changes section 

- docs/getting-started/configure-integration-policy.asciidoc
Backports the following commits to 8.2:
- Update configure-integration-policy.asciidoc (#2176)
> [8.2] Update configure-integration-policy.asciidoc (#2176)

- docs/getting-started/configure-integration-policy.asciidoc
- Update configure-integration-policy.asciidoc (#2176)
> [8.1] Update configure-integration-policy.asciidoc (#2176)

- docs/getting-started/configure-integration-policy.asciidoc
- Update configure-integration-policy.asciidoc (#2176)
> [8.0] Update configure-integration-policy.asciidoc (#2176)

- docs/release-notes/8.2.asciidoc
> [DOCS] Added summary for 136340.

- docs/reference/ref-intro.asciidoc
> [BUG] Update jump list to include runtime fields topic

- docs/release-notes/8.3.asciidoc
Addresses https://github.com/elastic/security-docs/issues/2291.
Preview [here](https://security-docs_2292.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.3.0.html#release-notes-8.3.3).
> [DOCS] Endpoint high CPU known issue in 8.3.3

- README.md
- Adds information on how to preview the documentation changes once the build is complete
> Improve contribution instructions in README file

- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/rules-ui-manage.asciidoc
A couple of quick bug fixes so the directions match the new grouped nav.
> [BUG] Fix nav directions

- README.md
Addresses #2312.
Note: No preview links for this, because the changes aren't in published docs, just the readme file. Check out the **Files changed** diff tab for new changes.
> Revise preview section in README.md

- docs/release-notes/7.17.asciidoc
Updates the known issues sections in the 7.17.x release notes to include https://github.com/elastic/security-docs/issues/2490.
Previews:
- [7.17.6](https://security-docs_2492.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#known-issue-7.17.6)
- [7.17.5](https://security-docs_2492.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#known-issue-7.17.5)
> [DOCS] 7.17.6 & 7.17.5 Windows Endpoints may wind up in a non-running state

- docs/release-notes/8.4.asciidoc
Fixes https://github.com/elastic/security-docs/issues/2500.
Previews:
- [8.4.2 Release note | Bug fixes and enhancements](https://security-docs_2501.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.4.0.html#bug-fixes-8.4.2)
- [8.4.0 Release note | Bug fixes and enhancements](https://security-docs_2501.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.4.0.html#bug-fixes-8.4.0)
> [BUG] Minor typo in rn summary for 138331

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
Fixes https://github.com/elastic/security-docs/issues/2412
> [DOCS] Add Webhook - Case Management connector to cases API list

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
Backports https://github.com/elastic/security-docs/pull/2509
> [8.4][DOCS] Add Webhook - Case Management connector to cases API list (#2509)

- docs/release-notes/7.17.asciidoc
> Adds coming tags to the 7.17.7 release notes

- docs/release-notes/7.17.asciidoc
To be merged by docs release point person on release day.
Merge this PR to deploy the changes to the target docs branch on the live Elastic website. The changes should appear on the website within one hour. Automatic backports will merge automatically, after all checks pass.
To re-run a PR build, add a comment in the PR: `@elasticmachine run elasticsearch-ci/docs`
> [DOCS] Remove coming tags from 7.17.7 release notes 

- docs/detections/alerts-view-details.asciidoc
Preview [here](https://security-docs_2630.docs-preview.app.elstc.co/guide/en/security/master/view-alert-details.html#alerts-enrich-host-user-risk-score).
> [BUG] Fixed subscription link

- docs/detections/prebuilt-rules/rule-details/adversary-behavior-detected-elastic-endgame.asciidoc
- prebuilt-rules-scripts/orig-rules-json-files/8.3.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/8.4.0-prebuilt-rule.json
- prebuilt-rules-scripts/orig-rules-json-files/8.5.0-prebuilt-rule.json
* https://github.com/elastic/detection-rules/pull/2382
This PR adjusted the security rule docs to match a mistake found in the related PR above. Scope of this PR is main and backports to 8.5, 8.4, and 8.3.
> [8.5] Adjusted Adversary Behavior - Detected - Elastic Endgame

- docs/release-notes/8.5.asciidoc
fixes #2675 by adding a known issue with Endpoint to the 8.5 release notes.
Preview: [8.5 release notes](https://security-docs_2677.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.5.0.html)
> [DOCS] Adds known endpoint bug

- docs/getting-started/configure-integration-policy.asciidoc
- docs/getting-started/install-endpoint.asciidoc
Resolves #2733.
Previews:
- [Configure and install the Elastic Defend integration](https://security-docs_2736.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html)
- [Configure an integration policy for Elastic Defend](https://security-docs_2736.docs-preview.app.elstc.co/guide/en/security/master/configure-endpoint-integration-policy.html)
> [DOCS] Reformat requirements callouts in Elastic Defend topics

- docs/detections/query-alert-indices.asciidoc
PR #2781 was closed without merging, but it contained a couple small, unrelated edits that would still be good to fold into the docs. This PR adds those edits.
> Apply edits from #2781

- docs/release-notes.asciidoc
> [DOCS] Adding link to 8.6 RN to index page

- docs/release-notes/8.6.asciidoc
> [8.6][bugfix] Fixes breaking changes snippet in Stack docs

- docs/cloud-native-security/cloud-nat-sec-kubernetes-dashboard.asciidoc
- docs/dashboards/kubernetes-dashboard.asciidoc
fixes #2902 by updating the version of the Kubernetes manifest .yaml referenced in the K8s dashboard doc
> Updates elastic-defend.yaml version 

- docs/getting-started/users-page.asciidoc
- docs/management/hosts/hosts-overview.asciidoc
> [BUG] Hosts, Users pages: broken links to subscription pricing

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/2883
Previews:
- [Index page](https://security-docs_2915.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_2915.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.9)
> 7.17.9 release notes

- docs/management/api/_exceptions-api-reusable-content.asciidoc
- docs/management/api/event-filters-api.asciidoc
(cherry picked from commit 2aa9f82fe757c4cfe1f9ea090832354666ed40c6)
> [8.6][BUG] Fix errors in the Event filters topic (#2982)

- docs/management/api/_exceptions-api-reusable-content.asciidoc
- docs/management/api/event-filters-api.asciidoc
(cherry picked from commit 2aa9f82fe757c4cfe1f9ea090832354666ed40c6)
> [8.7][BUG] Fix errors in the Event filters topic (#2982)

- docs/release-notes/8.7.asciidoc
> [Bug]Fixes bug in breaking changes

- docs/release-notes/8.7.asciidoc
updating the 8.7 release notes to include the introduction of CSPM
> updating 8.7 release note to include CSPM

- docs/release-notes/8.7.asciidoc
> [DOCS] Reformats `8.7` release notes

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3135.
Previews:
- [Index page](https://security-docs_3138.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_3138.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.10)
> 7.17.10 Release notes

- docs/detections/rules-ui-manage.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3220. 
Preview here.
> Options in the duplicate rule modal updated

- docs/getting-started/install-endpoint.asciidoc
> Install / Configure — Minor change

- docs/cloud-native-security/cloud-native-security-index.asciidoc
- docs/release-notes.asciidoc
- docs/release-notes/8.8.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3411.
Previews:
- [Index page](https://security-docs_3418.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_3418.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.8.0.html#release-notes-8.8.1)
> 8.8.1 Release notes

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
Relates to https://github.com/elastic/stack-docs/pull/2432
> [DOCS] Fix Jira connector example

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
Backports #3435 to `8.2` branch.
> [DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.16][DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.15][DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.14][DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.13][DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.11][DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.10][DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.9][DOCS] Fix Jira connector example (#3435)

- docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
> [7.12][DOCS] Fix Jira connector example (#3435)

- docs/detections/prebuilt-rules/downloadable-packages/8-5-6/prebuilt-rule-8-5-6-remote-system-discovery-commands.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-6/prebuilt-rule-8-5-6-suspicious-powershell-engine-imageload.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-6/prebuilt-rule-8-5-6-unusual-file-creation-alternate-data-stream.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-6/prebuilt-rule-8-5-6-wmi-incoming-lateral-movement.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-6/prebuilt-rules-8-5-6-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-6/prebuilt-rules-8-5-6-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.5.6. Please note these are meant to merge into 8.5 only and not backport.
> [Detection Rules] Adding Documents for v8.5.6 Pre-Built Detection Rules

- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rule-8-6-6-cron-job-created-or-changed-by-previously-unknown-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rule-8-6-6-new-systemd-service-created-by-previously-unknown-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rule-8-6-6-new-systemd-timer-created.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rule-8-6-6-remote-system-discovery-commands.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rule-8-6-6-suspicious-powershell-engine-imageload.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rule-8-6-6-unusual-file-creation-alternate-data-stream.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rule-8-6-6-wmi-incoming-lateral-movement.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rules-8-6-6-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-6-6/prebuilt-rules-8-6-6-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.6.6. Please note these are meant to merge into 8.6 only and not backport.
> [Detection Rules] Adding Documents for v8.6.6 Pre-Built Detection Rules

- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rule-8-7-6-cron-job-created-or-changed-by-previously-unknown-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rule-8-7-6-new-systemd-service-created-by-previously-unknown-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rule-8-7-6-new-systemd-timer-created.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rule-8-7-6-remote-system-discovery-commands.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rule-8-7-6-suspicious-powershell-engine-imageload.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rule-8-7-6-unusual-file-creation-alternate-data-stream.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rule-8-7-6-wmi-incoming-lateral-movement.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rules-8-7-6-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-6/prebuilt-rules-8-7-6-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.7.6. Please note these are meant to merge into 8.7 only and not backport.
> [Detection Rules] Adding Documents for v8.7.6 Pre-Built Detection Rules

- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rule-8-8-4-cron-job-created-or-changed-by-previously-unknown-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rule-8-8-4-new-systemd-service-created-by-previously-unknown-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rule-8-8-4-new-systemd-timer-created.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rule-8-8-4-remote-system-discovery-commands.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rule-8-8-4-suspicious-powershell-engine-imageload.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rule-8-8-4-unusual-file-creation-alternate-data-stream.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rule-8-8-4-wmi-incoming-lateral-movement.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rules-8-8-4-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-4/prebuilt-rules-8-8-4-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.8.4. Please note these are meant to merge into 8.8 only and not backport.
> [Detection Rules] Adding Documents for v8.8.4 Pre-Built Detection Rules

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3413.
Previews:
- [Index page](https://security-docs_3415.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_3415.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.11)
> 7.17.11 Release notes

- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-azure-full-network-packet-capture-detected.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-deprecated-threat-intel-filebeat-module-v8-x-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-deprecated-threat-intel-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-potential-antimalware-scan-interface-bypass-via-powershell.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-powershell-keylogging-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-powershell-mailbox-collection-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-powershell-script-with-encryption-decryption-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-powershell-suspicious-script-with-clipboard-retrieval-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-threat-intel-hash-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-threat-intel-ip-address-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-threat-intel-url-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rule-8-5-8-threat-intel-windows-registry-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rules-8-5-8-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-5-8/prebuilt-rules-8-5-8-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.5.8. Please note these are meant to merge into 8.5 only and not backport.
> [Detection Rules] Adding Documents for v8.5.8 Pre-Built Detection Rules

- docs/detections/prebuilt-rules/downloadable-packages/8-8-5/prebuilt-rule-8-8-5-first-time-seen-aws-secret-value-accessed-in-secrets-manager.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-azure-full-network-packet-capture-detected.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-deprecated-threat-intel-filebeat-module-v8-x-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-deprecated-threat-intel-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-potential-antimalware-scan-interface-bypass-via-powershell.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-powershell-keylogging-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-powershell-mailbox-collection-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-powershell-script-with-encryption-decryption-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-powershell-suspicious-script-with-clipboard-retrieval-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-threat-intel-hash-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-threat-intel-ip-address-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-threat-intel-url-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rule-8-8-6-threat-intel-windows-registry-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rules-8-8-6-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-8-6/prebuilt-rules-8-8-6-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.8.6. Please note these are meant to merge into 8.8 only and not backport.
> [Detection Rules] Adding Documents for v8.8.6 Pre-Built Detection Rules

- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-azure-full-network-packet-capture-detected.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-deprecated-threat-intel-filebeat-module-v8-x-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-deprecated-threat-intel-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-potential-antimalware-scan-interface-bypass-via-powershell.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-powershell-keylogging-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-powershell-mailbox-collection-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-powershell-script-with-encryption-decryption-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-powershell-suspicious-script-with-clipboard-retrieval-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-threat-intel-hash-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-threat-intel-ip-address-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-threat-intel-url-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rule-8-9-1-threat-intel-windows-registry-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rules-8-9-1-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-9-1/prebuilt-rules-8-9-1-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.9.1. Please note these are meant to merge into 8.9 only and not backport.
> [Detection Rules] Adding Documents for v8.9.1 Pre-Built Detection Rules

- docs/detections/prebuilt-rules/downloadable-packages/8-7-7/prebuilt-rule-8-7-7-first-time-seen-aws-secret-value-accessed-in-secrets-manager.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-azure-full-network-packet-capture-detected.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-deprecated-threat-intel-filebeat-module-v8-x-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-deprecated-threat-intel-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-potential-antimalware-scan-interface-bypass-via-powershell.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-powershell-keylogging-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-powershell-mailbox-collection-script.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-powershell-script-with-encryption-decryption-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-powershell-suspicious-script-with-clipboard-retrieval-capabilities.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-threat-intel-hash-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-threat-intel-ip-address-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-threat-intel-url-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rule-8-7-8-threat-intel-windows-registry-indicator-match.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rules-8-7-8-appendix.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-7-8/prebuilt-rules-8-7-8-summary.asciidoc
- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- docs/index.asciidoc
Security Doc updates for prebuilt security rule integration package version v8.7.8. Please note these are meant to merge into 8.7 only and not backport.
> [Detection Rules] Adding Documents for v8.7.8 Pre-Built Detection Rules

- docs/management/api/get-endpoint-api.asciidoc
- docs/management/api/list-endpoints-api.asciidoc
Updates documentation for endpoint management APIs (get and lis endpoints)
Previews
https://security-docs_3519.docs-preview.app.elstc.co/guide/en/security/master/get-endpoint-api.html
https://security-docs_3519.docs-preview.app.elstc.co/guide/en/security/master/list-endpoints-api.html
refs elastic/kibana/pull/160506
> [8.10] Endpoint API documentation for get/list endpoints

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3548.
Preview:
- [Index](https://security-docs_3557.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_3557.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.12)
> 7.17.12 Release notes

- docs/detections/rules-ui-manage.asciidoc
Resolves #3525, backports to 8.8 - 8.5.
> Prebuilt rules tags documentation [8.8 - 8.5]

- docs/cases/cases-ui-integrations.asciidoc
* Resolves https://github.com/elastic/security-docs/issues/3655 
* PR for `7.17` branch: https://github.com/elastic/security-docs/pull/3660
Preview: [Configure external connections](https://security-docs_3659.docs-preview.app.elstc.co/guide/en/security/master/cases-ui-integrations.html)
> Removes outdated tutorials

- docs/cases/cases-ui-integrations.asciidoc
- docs/detections/rules-ui-manage.asciidoc
* Resolves https://github.com/elastic/security-docs/issues/3655 
* PR for `main`: https://github.com/elastic/security-docs/pull/3659
Previews:
* [Configure external connections](https://security-docs_3660.docs-preview.app.elstc.co/guide/en/security/7.17/cases-ui-integrations.html)
* [Manage detection rules](https://security-docs_3660.docs-preview.app.elstc.co/guide/en/security/7.17/rules-ui-management.html)
> [7.17] Removes outdated tutorials

- docs/cloud-native-security/cspm-benchmark-rules.asciidoc
> [Bugfix] CSPM doc typo 

- docs/cases/cases-manage.asciidoc
- docs/index.asciidoc
Backports https://github.com/elastic/security-docs/pull/3724
> [8.9][DOCS] Remove content reuse for cases (#3724)

- docs/cases/cases-manage.asciidoc
- docs/index.asciidoc
Backports https://github.com/elastic/security-docs/pull/3724
> [8.8][DOCS] Remove content reuse for cases (#3724)

- docs/cases/cases-manage.asciidoc
- docs/index.asciidoc
Backports https://github.com/elastic/security-docs/pull/3724
> [8.6][DOCS] Remove content reuse for cases (#3724)

- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
Updates the downloadable updates description for the `8.7.11` package for prebuilt detection rules.
> [Detection Rules] Update Downloadable Updates Description for 8.7.11 Package

- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
Updates the downloadable updates description for the `8.9.4` package for prebuilt detection rules.
> [Detection Rules] Update Downloadable Updates Description for 8.9.4 Package

- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
Updates the downloadable updates description for the `8.10.1` package for prebuilt detection rules.
> [Detection Rules] Update Downloadable Updates Description for 8.10.1 Package

- docs/detections/detections-index.asciidoc
- docs/detections/rules-coverage.asciidoc
Contributes to #3797, creates stub page for docs link.
> Create stub page for rules coverage page

- docs/dashboards/dashboards-overview.asciidoc
- Resolves #3366 
Preview: [Dashboards](https://security-docs_3739.docs-preview.app.elstc.co/guide/en/security/8.8/dashboards-overview.html)
_Note_: This is already documented in [8.9](https://www.elastic.co/guide/en/security/current/dashboards-overview.html). This PR backports the change to versions 8.4—8.8.
> Documents the Security Solution tag

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3802
Preview:
- [Index](https://security-docs_3821.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_3821.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.13)
> 7.17.13 Release notes

- docs/osquery/view-osquery-results.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3853.
Preview: Examine Osquery results
> [BUG] Minor typo in Osquery docs

- docs/release-notes/8.10.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3926.
[Preview](https://security-docs_3944.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.10.0.html#features-8.10.0) - See first bullet
> [BUG] Incorrect hyperlink for ticket id in 8.10 New Feature List

- docs/release-notes.asciidoc
- docs/release-notes/8.10.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3960
Preview:
- [Index page](https://security-docs_3962.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_3962.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.10.1.html#release-notes-8.10.1)
> 8.10.1 Release notes

- docs/release-notes.asciidoc
- docs/release-notes/8.10.asciidoc
- docs/release-notes/8.9.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3961.
Previews:
- [Index page](https://security-docs_3982.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_3982.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.10.1.html#release-notes-8.10.2)
> 8.10.2 Release notes 

- docs/cloud-native-security/cspm-get-started-aws.asciidoc
- docs/cloud-native-security/cspm-get-started-gcp.asciidoc
Fixes #3989, which identified a couple of recommendations for additional info to include in docs that we got from product after the 8.10 release.
Previews: 
[CSPM AWS onboarding](https://security-docs_3990.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started.html)
[CSPM GCP onboarding](https://security-docs_3990.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started-gcp.html)
> CSPM onboarding updates

- docs/getting-started/artifact-control.asciidoc
Fixes title of stub page added in #4003.
> Fix title of artifact control page

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4009. 
Previews:
- [Index page](https://security-docs_4010.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_4010.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.14)
> 7.17.14 Release notes

- docs/release-notes.asciidoc
- docs/release-notes/8.10.asciidoc
Fixes https://github.com/elastic/security-docs/issues/3991.
Previews:
- [Index page](https://security-docs_4011.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_4011.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.10.1.html#release-notes-8.10.3)
> 8.10.3 Release notes

- docs/cloud-native-security/cspm-get-started-aws.asciidoc
> Fixes a typo

- docs/detections/rules-ui-create.asciidoc
Removing a note that's still under development in  https://github.com/elastic/security-docs/issues/4195.
> Remove note that's in progress

- docs/release-notes.asciidoc
- docs/release-notes/8.11.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4241
Previews:
- [Index page](https://security-docs_4242.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_4242.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.11.0.html#release-notes-8.11.1)
> 8.11.1 Release notes

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes 
https://github.com/elastic/security-docs/issues/4243
Previews:
- [Index page](https://security-docs_4244.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_4244.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.15)
> 7.17.15 Release notes

- docs/getting-started/agent-tamper-protection.asciidoc
> Fix typo in agent-tamper-protection.asciidoc

- docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc
- docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc
- docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc
- docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc
- docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
> Update URLs in branch 7.13

- docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-account-configured-with-never-expiring-password.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-creation-of-a-hidden-local-user-account.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-remote-file-copy-via-teamviewer.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-suspicious-managed-code-hosting-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-suspicious-werfault-child-process.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-account-configured-with-never-expiring-password.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-creation-of-a-hidden-local-user-account.asciidoc
- docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-remote-file-copy-via-teamviewer.asciidoc
- docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc
- docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc
- docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc
- docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc
- docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
> Update Prebuilt Rule Links for Malicious Site in 8.1

- docs/getting-started/ers-req.asciidoc
Resolves #4307.
Preview: [Entity Risk Scoring prerequisites](https://security-docs_4361.docs-preview.app.elstc.co/guide/en/security/master/ers-requirements.html)
> Updates Entity Risk Scoring requirements

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4377
Previews:
- [Index page](https://security-docs_4378.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_4378.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.16)
> 7.17.16 Release notes

- docs/cloud-native-security/cloud-native-security-index.asciidoc
- docs/cloud-native-security/d4c-overview.asciidoc
Fixes #4409 and #4408 by making some minor tweaks to the existing documentation for Defend for Containers.
> D4C minor fixes

- docs/events/timeline-ui-overview.asciidoc
Resolves https://github.com/elastic/security-docs/issues/4309.
Development PR: https://github.com/elastic/kibana/pull/171027
Corresponding serverless docs PR (already merged): https://github.com/elastic/staging-serverless-security-docs/pull/234
PRs for the related 'Add timeline save button' feature :
- https://github.com/elastic/kibana/pull/169239 (dev)
- https://github.com/elastic/staging-serverless-security-docs/pull/226 (serverless docs)
- #4299 (ESS docs)
Preview: [Investigate events in Timeline](https://security-docs_bk_4437.docs-preview.app.elstc.co/guide/en/security/master/timelines-ui.html)
> Save timeline as new

- docs/advanced-entity-analytics/behavioral-detection-use-cases.asciidoc
Updates phrasing on the Behavioral detection use cases page to match the editorial suggestions applied in commit https://github.com/elastic/staging-serverless-security-docs/pull/248/commits/c551815f4450e1f5d1da796362aedc176929e9eb.
Preview: [Behavioral detection use cases](https://security-docs_bk_4494.docs-preview.app.elstc.co/guide/en/security/master/behavioral-detection-use-cases.html)
> Match phrasing with serverless docs

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4616
Previews:
- [Index](https://security-docs_bk_4617.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_4617.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.17)
> 7.17.17 Release notes

- docs/assistant/security-assistant.asciidoc
Fixes #4674 by updating an outdated reference to a button
Preview:
> AI "Magic Wand" button -> "Chat"

- docs/cloud-native-security/session-view.asciidoc
> Removes beta tags from terminal output doc

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4740
Preview:
- [Index](https://security-docs_bk_4750.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_4750.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.18)
> 7.17.18 Release notes

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/rules-ui-create.asciidoc
Contributes to https://github.com/elastic/security-docs/issues/4744
Previews:
- Create a detection rule | Create an event correlation rule
- Create rule | Optional fields for event correlation, query, threshold, indicator match, new terms, and ES|QL rules
> [Known Issue] Add docs to describe a known issue/limitation of EQL rule cross-cluster search 

- docs/release-notes.asciidoc
- docs/release-notes/8.12.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4794
Preview:
- [Index page](https://security-docs_bk_4834.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_bk_4834.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.12.0.html#release-notes-8.12.2)
> 8.12.2 Release notes

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/rules-ui-create.asciidoc
Backports the following commits to 8.8:
> [8.8] [Known Issue] Add docs to describe a known issue/limitation of EQL rule cross-cluster search (#4813)

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/rules-ui-create.asciidoc
Backports the following commits to 8.7:
> [8.7] [Known Issue] Add docs to describe a known issue/limitation of EQL rule cross-cluster search (#4813)

- docs/detections/api/rules/rules-api-create.asciidoc
- docs/detections/rules-ui-create.asciidoc
Backports the following commits to 8.6:
> [8.6] [Known Issue] Add docs to describe a known issue/limitation of EQL rule cross-cluster search (#4813)

- docs/cloud-native-security/cspm-faq.asciidoc
- docs/cloud-native-security/kspm-faq.asciidoc
Fixes #4969 by updating the CSPM and KSPM FAQ with current answers to questions.
Previews: [CSPM](https://security-docs_bk_4970.docs-preview.app.elstc.co/guide/en/security/master/cspm-security-posture-faq.html) FAQ, [KSPM](https://security-docs_bk_4970.docs-preview.app.elstc.co/guide/en/security/master/security-posture-faq.html) FAQ
> updates FAQ

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/4793
Previews:
- [Index page](https://security-docs_bk_4931.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_4931.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.19)
> 7.17.19 Release notes

- docs/release-notes/8.13.asciidoc
Fixes #5012 by adding release notes for 8.13.1
> 8.13.1 release notes

- docs/release-notes.asciidoc
- docs/release-notes/8.13.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5039
Previews:
- [Index page](https://security-docs_bk_5058.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_bk_5058.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.13.0.html#release-notes-8.13.2)
> 8.13.2 Release notes

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5055
Previews:
- [Index](https://security-docs_bk_5059.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_5059.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.20)
> 7.17.120 Release notes

- docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
- Add update notes for v8.9.15
- Issue details https://github.com/elastic/ia-trade-team/issues/328
> Add Update Notes for 8.9.15

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5123
Preview:
- [Index page](https://security-docs_bk_5140.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_5140.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.21)
> 7.17.21 Release notes 

- docs/release-notes.asciidoc
- docs/release-notes/8.13.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5159
Preview:
- [Index page](https://security-docs_bk_5160.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_bk_5160.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.13.0.html#release-notes-8.13.4)
> 8.13.4 Release notes

- docs/serverless/what-is-security-serverless.mdx
Adds a hidden span to trigger new builder workflow.
> Trigger builder

- docs/release-notes.asciidoc
- docs/release-notes/8.14.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5371
Previews:
- [Index page](https://security-docs_bk_5372.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html)
- [Release notes](https://security-docs_bk_5372.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.14.0.html#release-notes-8.14.1)
> 8.14.1 Release notes

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5278
Preview:
- [Index page](https://security-docs_bk_5279.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_5279.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.22)
> 7.17.22 Release notes

- .gitignore
> Update .gitignore file for `7.9` branch

- .gitignore
> Update .gitignore file for `7.10` branch

- .gitignore
Adds `.vs/` to `.gitignore` file.
> Update .gitignore file for `7.17` branch

- .gitignore
Updates `.gitignore` file for `7.16`.
> Updates .gitignore for `7.16` branch

- .gitignore
> Update .gitignore file for `7.15` branch 

- .gitignore
> Update .gitignore file for `7.14` branch 

- .gitignore
> Update .gitignore file for `7.13` branch

- .gitignore
> Update .gitignore file for `7.12` branch

- .gitignore
> Update .gitignore file for `7.11` branch

- docs/cloud-native-security/d4c-get-started.asciidoc
- docs/cloud-native-security/d4c-overview.asciidoc
Adds a beta tag to the D4C docs
Previews: [CWP overview](https://security-docs_bk_5519.docs-preview.app.elstc.co/guide/en/security/master/d4c-overview.html), [get started with CWP](https://security-docs_bk_5519.docs-preview.app.elstc.co/guide/en/security/master/d4c-get-started.html)
> [ESS] Adds beta tag to D4C

- docs/release-notes.asciidoc
Just like the title says!
Preview - https://security-docs_bk_5599.docs-preview.app.elstc.co/guide/en/security/master/release-notes.html
> [8.14.3] Adds link to the 8.14.3 RNs 

- docs/AI-for-security/llm-performance-matrix.asciidoc
- docs/serverless/AI-for-security/llm-performance-matrix.mdx
Fixes #5587
Updates the LLM Matrix [Serverless Preview](https://elastic-dot-co-docs-production-2zarmqopl-elastic-dev.vercel.app/current/serverless/security/llm-performance-matrix) / [ESS Preview](https://security-docs_bk_5614.docs-preview.app.elstc.co/guide/en/security/master/llm-performance-matrix.html)
> [8.14] [bug] Updates LLM Matrix

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5491
Preview:
- [Index page](https://security-docs_bk_5603.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_5603.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.23)
> 7.17.23 release notes 

- docs/AI-for-security/llm-performance-matrix.asciidoc
Fixes #5587. Minor update to LLM model performance matrix.
Preview: [LLM performance matrix](https://security-docs_bk_5622.docs-preview.app.elstc.co/guide/en/security/master/llm-performance-matrix.html)
> Updates ESS LLM recommended model matrix

- docs/AI-for-security/ai-security-assistant.asciidoc
- docs/serverless/AI-for-security/ai-assistant.mdx
Fixes https://github.com/elastic/security-docs/issues/5518
Previews:
- [8.15](https://security-docs_bk_5598.docs-preview.app.elstc.co/guide/en/security/master/security-assistant.html#start-chatting) - Updated the description of what users can do with AI Assistant when interacting with rules (see second item in the list)
- [Serverless](https://elastic-dot-co-docs-production-8av1pyyc6-elastic-dev.vercel.app/current/serverless/security/ai-assistant#start-chatting) - Same as above.
> [Request][8.15 & Serverless] AI Assistant for rule creation

- docs/cloud-native-security/cspm-get-started-aws.asciidoc
- docs/cloud-native-security/cspm-get-started-azure.asciidoc
- docs/cloud-native-security/cspm-get-started-gcp.asciidoc
- docs/cloud-native-security/cspm.asciidoc
Fixes #5725 by adding previously undocumented required privileges for CSPM in ESS.
Preview: [Get started with CSPM](https://security-docs_bk_5728.docs-preview.app.elstc.co/guide/en/security/master/cspm.html)
> Adds CSPM privilege reqs

- docs/management/admin/response-actions.asciidoc
- docs/serverless/endpoint-response-actions/response-actions.mdx
Follow-up for https://github.com/elastic/security-docs/pull/5737. More details in [this comment](https://github.com/elastic/security-docs/pull/5737#issuecomment-2307632908).
> Update setting name in response-actions.asciidoc

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5781
Previews:
- [Index](https://security-docs_bk_5782.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [Release notes](https://security-docs_bk_5782.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.24)
> 7.17.24 Release Notes

- .mergify.yml
Adds mergify option for 8.16, which is to branch 8x.
> Update .mergify.yml for `8.16`

- docs/management/admin/automated-response-actions.asciidoc
- docs/serverless/endpoint-response-actions/automated-response-actions.mdx
Resolves https://github.com/elastic/security-docs-internal/issues/45. Fixes and aligns requirements statements for automated response actions across both ESS and serverless.
- ESS: [Automated response actions](https://security-docs_bk_5852.docs-preview.app.elstc.co/guide/en/security/master/automated-response-actions.html)
- Serverless: Use the link in the **comment below**, navigate to the **Automated response actions** page.
> Fix automated response actions requirements

- .github/ISSUE_TEMPLATE/docs-request-internal.yaml
- .github/ISSUE_TEMPLATE/enhancement-request.yaml
> Fixes yaml template errors

- docs/release-notes/8.14.asciidoc
- docs/release-notes/8.15.asciidoc
Fixes https://github.com/elastic/security-docs-internal/issues/46
Previews:
- [8.14.x release notes](https://security-docs_bk_5884.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.14.0.html)
- [8.15.x release notes](https://security-docs_bk_5884.docs-preview.app.elstc.co/guide/en/security/master/release-notes-header-8.15.0.html)
> [Known Issue][Detection Engine] Alert tags maintain state

- docs/cloud-native-security/kspm-get-started.asciidoc
- docs/serverless/cloud-native-security/get-started-with-kspm.mdx
Fixes #5916 — minor update
Preview: [Get started with KSPM](https://elastic-dot-co-docs-production-puiurwkhl-elastic-dev.vercel.app/current/serverless/security/get-started-with-kspm)
> Get started with KSPM minor update

- .mergify.yml
Adds 8.17.0 to mergify and updates 8.16.
> [8.17][Main] Update .mergify.yml

- .mergify.yml
> [8.16] Update .mergify.yml

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5943
Previews:
- [Index page](https://security-docs_bk_5944.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes.html)
- [7.17.25 release notes](https://security-docs_bk_5944.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.25)
> 7.17.25 Release notes

- docs/serverless/ingest/auto-import.asciidoc
Serverless twin of https://github.com/elastic/security-docs/pull/6064
Preview: [Automatic import](https://security-docs_bk_6108.docs-preview.app.elstc.co/guide/en/serverless/main/security-automatic-import.html)
> [serverless] Automatic import serverless update

- docs/getting-started/configure-integration-policy.asciidoc
- docs/serverless/edr-install-config/configure-endpoint-integration-policy.asciidoc
Fixes https://github.com/elastic/security-docs/issues/5814 for both stateful and serverless.
- Configure an integration policy for Elastic Defend (ESS) (serverless)
> [BUG] - Inconsistency in Elastic Defend quarantine path

- .mergify.yml
Updates `main` branch. Adds `8.x` mergify for `v.8.18.0` branch; updates previous `8.x` to target `8.17`.
> [8.x] [main] Update .mergify.yml

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Fixes https://github.com/elastic/security-docs/issues/6263
Preview: [7.17.26 release notes](https://security-docs_bk_6264.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.26)
> 7.17.26 Release notes 

- docs/AI-for-security/llm-performance-matrix.asciidoc
- docs/serverless/AI-for-security/llm-performance-matrix.asciidoc
Fixes #5950 — updates the LLM performance matrix
Preview: LLM Performance matrix ([ESS](https://security-docs_bk_6268.docs-preview.app.elstc.co/guide/en/security/master/llm-performance-matrix.html)) ([Serverless](https://security-docs_bk_6268.docs-preview.app.elstc.co/guide/en/serverless/current/security-llm-performance-matrix.html))
> Updates LLM performance matrix

- docs/release-notes.asciidoc
- docs/release-notes/7.17.asciidoc
Addresses https://github.com/elastic/security-docs/issues/6390.
Preview: [7.17.27 release notes](https://security-docs_bk_6393.docs-preview.app.elstc.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.27)
> Release notes 7.17.27

- docs/cloud-native-security/cspm-findings.asciidoc
minor fix of a bug found during post-migration cleanup
> fixes list formatting on CSPM Findings page

- docs/detections/detection-engine-intro.asciidoc
- docs/getting-started/configure-integration-policy.asciidoc
Fixes docs-content/issues/794
Twin PR of https://github.com/elastic/docs-content/pull/794 — more info here.
> Removes outdated section
